newrelic/node-newrelic

lib/instrumentation/cassandra-driver.js
lib/instrumentation/core/globals.js

...because it's been bothering me for a year.

fixed wraped typo

---

lib/config/default.js

https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#slow-queries

Add missing env docs

---

README.md

* Added link to CONTRIBUTING.md file in README.md
None
Just a handy link in the Readme.

Add link to CONTRIBUTING.md to the README.md file

---

package-lock.json

Fixes/updates security vulnerabilities in npm packages for `minimist` and `mkdirp`.

fix: update deps to address security issue

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/PULL_REQUEST_TEMPLATE.md

* Updates PR template and adds initial issue templates.
These are consistent with the newrelic-winston-logenricher-node repo but obviously can be tweaked now or over time as we converge on what we want. Issue templates are based on the standard NR open source templates as of when we worked on the winston enricher.

Update GitHub templates

---

test/unit/collector/api-connect.test.js
test/unit/collector/api-login.test.js
test/unit/collector/api-run-lifecycle.test.js
test/unit/collector/api.test.js

* Converts most of the collector API unit tests to use the tap API. Splits larger test groupings into their own test files.

Converts most of the collector API unit tests to use the tap API.

---

test/unit/collector/parse-response.test.js

* Converts parse-response unit tests to tap API.

Converts parse-response unit tests to tap API.

---

test/integration/agent/lasp-send-trace.tap.js

* Test failed on my fork because I didn't have the license

Check for license before running test

---

test/unit/facts.test.js

Convert to tap test

---

test/unit/transaction.test.js

* Converted transaction 'finalizeName...' unit tests to use tap API.
Converting these tests up-front before I add/modify in this area. Doing as an initial PR instead with upcoming changes as goal is separate (convert all the things to tap) and to minimize reviewer context.

Converts transaction 'finalizeName...' unit tests to use tap API.

---

lib/errors/error-collector.js
test/integration/distributed-tracing/span-error-attributes.tap.js
test/unit/errors/error-collector.test.js

* Drops errors earlier during collection when error collection is disabled.
Error attributes will no longer show up on spans when error collection has been disabled. Other unnecessary work will also be avoided.

Moves error data collection checks up to where errors are added

---

lib/transaction/index.js
test/integration/distributed-tracing/span-error-attributes.tap.js

* Added 'error.expected' attribute to span active at time expected error was noticed.

Add expected error to span

---

lib/config/index.js
lib/grpc/connection.js
lib/spans/span-streamer.js
lib/spans/streaming-span-event-aggregator.js
test/integration/infinite-tracing-connection.tap.js
test/unit/grpc/connection.test.js

* Added connect response request_headers_map key-value pairs to Infinite Tracing gRPC connection metadata.
This PR is based off the same branch as https://github.com/newrelic/node-newrelic/pull/376 and should be reviewed/merged afterwards. This is to avoid painful conflicts with modifying parts of certain tests.
The keys MUST be sent as lowercase via the metadata per the spec.

Adds request headers map key-value paris to Infinite Tracing gRPC metadata

---

.github/workflows/ci-workflow.yml

* Updated force secret test runs to run on branch pushes to the main repository.
The previous setup would try to run on pull requests off of a forked 'master' branch.

Updates force secret run to only run on branch pushes to main repo.

---

test/unit/trace-segment.test.js

Converted trace-segment tests to tap

---

lib/transaction/trace/index.js
test/unit/trace.test.js

* Added the following parent attributes to span events:
* 'parent.type'
* 'parent.app'
* 'parent.account'
* 'parent.transportType'
* 'parent.transportDuration'

Parent span event attrs

---

test/unit/collector/key-parser.test.js
test/unit/hashes.test.js
test/unit/instrumentation/core/inspector.test.js
test/unit/metric/normalizer-tx-segment.test.js
test/unit/protocols.test.js
test/unit/util/hashes.test.js
test/unit/util/label-parser.test.js
test/unit/util/obfuscate-sql.test.js

* Converted some tests to Node-tap

Tap test conversions

---

LICENSE
THIRD_PARTY_NOTICES.md
package.json

- Updated LICENSE to Apache License

Update LICENSE to Apache License and move Symantec cert license

---

README.md

This will be covered under the license release notes.
Copied new boilerplate style we are likely going to adopt.

Updates readme to appropriately mention Apache 2.0.

---

README.md

- Streamlined README.md
- https://github.com/newrelic/node-newrelic/issues/399
Streamlines README.md by converting it to the New Standard New Relic format, and replacing previous documentation with links to appropriate docs.newrelic.com site.

Issue #399: New README.md

---

CONTRIBUTING.md

* Updated contributing guidelines
https://github.com/newrelic/newrelic-repo-template/blob/master/CONTRIBUTING.md
* Merged the New Relic contributing template with our existing contributing guidelines doc

Updated contributing guide

---

README.md

Reviewed the Readme

---

CONTRIBUTING.md

PR version verbage

---

.github/ISSUE_TEMPLATE/bug_report.md

* Closes: https://github.com/newrelic/node-newrelic/issues/406

Adds some additional guidance to bug issue template.

---

NEWS.md

Updates news wording.

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
test/unit/licenses.json
third_party_manifest.json

* Bumps @newrelic/koa to ^4.0.0.

Bump @newrelic/koa version

---

README.md

* Updated CI readme badges to link to each workflow.

Updates CI badges to link to each workflow page.

---

SECURITY.md

- Updated `SECURITY.md` with coordinated disclosure program link

Removing Old Security Language

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
test/unit/licenses.json
third_party_manifest.json

* Bumped @newrelic/superagent to ^3.0.0.

Bumps @newrelic/superagent to ^3.0.0.

---

package-lock.json
package.json

* Bumped node-test-utilities to ^4.0.0.

Bumps node-test-utilities to ^4.0.0.

---

THIRD_PARTY_NOTICES.md
third_party_manifest.json

Accidentally missed this with the test-utils version bump but works out to capture the async bump.

Updates third party notices to capture node-test-utilities and async version bumps

---

README.md

* Removed the "remove this section if it's not needed" language as that language was not needed :)

Removes the 'remove this...' language from readme.

---

LICENSE

Fixes first-line formatting for license file.

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
test/unit/licenses.json
third_party_manifest.json

* Bumped @newrelic/aws-sdk to ^2.0.0.

Bumps @newrelic/aws-sdk to ^2.0.0.

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
test/unit/licenses.json

* Bumped @newrelic/native-metrics to ^5.3.0.

Bumps @newrelic/native-metrics to ^5.3.0.

---

NEWS.md

* **Security fix:** Resolves an issue where transaction traces will still capture the request URI when the Node.js agent is configured to exclude the 'request.uri' attribute. This can be problematic for certain customers in environments where sensitive information is included in the URI. See security bulletin [NR20-02](https://docs.newrelic.com/docs/security/new-relic-security/security-bulletins/security-bulletin-nr20-02).
The request URI will now be excluded from transaction traces if the 'request.uri' attribute has been set to be excluded at either the top-level 'attributes.exclude' configuration or at the 'transaction_tracer.attributes.exclude' configuration.
* https://github.com/newrelic/node-newrelic/pull/465

Release v6.12.1

---

NEWS.md

* Added ability for the agent to write to a named pipe, instead of stdout, when in serverless mode.
* https://github.com/newrelic/node-newrelic/pull/464

Release 6.13.0.

---

README.md

- Update readme with community-plus header.
- Closes: #471

Update readme with community-plus header

---

CODE_OF_CONDUCT.md

* Removed repository CoC in favor of centralized CoC at org root.
* Fixes: https://github.com/newrelic/node-newrelic/issues/476
Changed my mind. Going to land-as is and then do a follow-up fix once I see some of the inherited link behaviors.

Removes repo's code of conduct as there's now a centralized one.

---

CONTRIBUTING.md

As expected, have to update the link in contrib. Unfortunately, there's not magic like the security link so just have to hard code.

Updates CoC link in contrib to central location.

---

NEWS.md

* Fixed named-pipe check for lambda invocations to avoid race-condition.
Named-pipe existence will now be checked just prior to first write and then cached.
* Updated README with community-plus header.
* Updated README config copy example.
* Added Open Source Policy workflow.
* Removed repository CoC in favor of centralized CoC at org root.
- https://github.com/newrelic/node-newrelic/pull/479
- https://github.com/newrelic/node-newrelic/pull/472
- https://github.com/newrelic/node-newrelic/pull/475
- https://github.com/newrelic/node-newrelic/pull/469
- https://github.com/newrelic/node-newrelic/pull/480
- https://github.com/newrelic/node-newrelic/pull/481

Release 6.13.1

---

examples/shim/Webframework-Simple.md

* Update shim documentation (thanks  @ronen-e -- closes #485)
#485 
https://raw.githubusercontent.com/newrelic/node-newrelic/main/examples/shim/Webframework-Simple.md

Shim documentation update

---

package-lock.json
package.json
test/integration/config/attribute-cat.tap.js
test/unit/high-security.test.js

* Removed lodash as a development dependency

Remove lodash

---

THIRD_PARTY_NOTICES.md
third_party_manifest.json

* Updates the third party notice files after removing lodash as a dependency.

Remove lodash from third party files

---

NEWS.md

* Removed lodash as a development dependency
* Check for named pipe existence before each flush
This removes the cached value used in 6.13.1
* Update shim documentation
Thank you to @ronen-e for the contribution!
* https://github.com/newrelic/node-newrelic/pull/491
* https://github.com/newrelic/node-newrelic/pull/490
* https://github.com/newrelic/node-newrelic/pull/489
* https://github.com/newrelic/node-newrelic/pull/486

Updates release notes for 6.13.2 release.

---

lib/grpc/connection.js
package-lock.json
package.json

* Fixed issue where gRPC connection used for infinite tracing could throw if the server shutdown during disconnect of an existing connection.
* Bumped @grpc/grpc-js to 1.1.7.
* Bumped @grpc/proto-loader to ^0.5.5.
* Fixes: https://github.com/newrelic/node-newrelic/issues/493
* Discovered via: https://github.com/newrelic/node-newrelic/pull/487
Node 14 testing showed an increased likelihood of an existing race condition in our gRPC/infinite tracing tests. In some cases, the server would be shut down while the `stream.end()` had not yet responded. In this scenario, a disconnected/error status code would be returned. Since there was no error handler (we removed in _disconnect), this error would throw and crash/break the test.
Instead of restructuring all the things, this PR takes a point-fix …

Fix gRPC disconnect error

---

lib/grpc/connection.js
lib/spans/span-streamer.js

* Increased logging level of certain infinite tracing / gRPC errors.
* Decreased logging interval of dropped span warning for infinite tracing.

Infinite tracing logging modifications

---

NEWS.md

* Noticed the headers were off-by-one for the last two release. Just a format fix

Standardize headers in NEWS.md

---

NEWS.md
THIRD_PARTY_NOTICES.md
third_party_manifest.json

* Updated README for consistency.
* Fixed issue where gRPC connection used for infinite tracing could throw if the server
shutdown during disconnect of an existing connection.
* Bumped @grpc/grpc-js to 1.1.7.
* Bumped @grpc/proto-loader to ^0.5.5.
* Infinite tracing logging and support metric improvements.
* Increased logging level of certain infinite tracing / gRPC errors.
* Decreased logging interval of dropped span warning for infinite tracing.
* Added additional support metrics and logging for infinite tracing.
* Fixed bug where errors would still be collected for transactions with ignored error
status codes in certain situations.
* Converted errors ignore unit tests to tap API.
* Added Node 14 to CI test coverage.
Many thanks to @jgeurts for the contribution.
- …

Release v6.14.0

---

lib/transaction/tracecontext.js

* Added additional logging to W3C Trace Context header creation.

Adds additional logging to W3C tracecontext header creation.

---

.github/workflows/ci-workflow.yml
package.json
test/versioned/amqplib/package.json
test/versioned/bluebird/package.json
test/versioned/cassandra-driver/package.json
test/versioned/cls/package.json
test/versioned/connect/package.json
test/versioned/director/package.json
test/versioned/express/package.json
test/versioned/fastify/package.json
test/versioned/generic-pool/package.json
test/versioned/hapi/hapi-17/package.json
test/versioned/hapi/hapi-post-18/package.json
test/versioned/hapi/hapi-pre-17/package.json
test/versioned/ioredis/package.json
test/versioned/mongodb/package.json
test/versioned/mysql/package.json
test/versioned/mysql2/package.json
test/versioned/pg/pg-post-7/package.json
test/versioned/pg/pg-pre-7/package.json
test/versioned/redis/package.json
test/versioned/restify/restify-pre-7/package.json

* Removed Node v8.x from CI (closes  #514)
#514

Remove Node v8 from CI

---

bin/run-versioned-tests.sh

Removes koa skip from version test run

Remove koa skip from version test runs

---

test/integration/agent/lasp-send-trace.tap.js
test/integration/lasp_connect.tap.js

* Skip LASP tests due to service issue

Skip LASP integration tests for now (issue with service)

---

package-lock.json
package.json

* Update `@grpc/grpc-js` to version v1.2.0

Update grpc-js version to v1.2.0

---

THIRD_PARTY_NOTICES.md
third_party_manifest.json

Updated third-party manifest and notices

Update third-party manifest and notices

---

NEWS.md
ROADMAP_Node.md
lib/collector/api.js
lib/collector/http-agents.js
lib/collector/remote-method.js
lib/config/attribute-filter.js
lib/config/default.js
lib/config/index.js
lib/db/parse-sql.js
lib/db/query-parsers/sql.js
lib/grpc/connection.js
lib/instrumentation/core/http.js
lib/instrumentation/fastify/spec-builders.js
lib/parse-proc-cpuinfo.js
lib/proxy/grpc.js
lib/shim/promise-shim.js
lib/shim/shim.js
lib/shim/transaction-shim.js
lib/shim/webframework-shim.js
lib/shimmer.js
lib/spans/create-span-event-aggregator.js
lib/timer.js
lib/transaction/dt-payload.js
lib/transaction/index.js
lib/transaction/tracecontext.js
lib/util/byte-limit.js
lib/utilization/common.js
stub_api.js

Fix typos in code comments, documentation, and debugging logger messages

Fix typos in code comments, docs and debug messages

---

NEWS.md

* Fixes a bug where the `http.statusCode` attribute was not being captured for an async invoked lambda.
* Fixed typos in code comments, documentation, and debugging logger messages.
Thank you @TysonAndre for the contribution.
https://github.com/newrelic/node-newrelic/pull/556
https://github.com/newrelic/node-newrelic/pull/549

Release v7.0.2

---

lib/instrumentation/fastify.js
test/integration/fastify/naming.tap.js

* Added support for fastify v3

Add fastify v3 support

---

index.js

* Fixed log message regarding Node minimum version
* #557

Fix Node minimum version message (fixes #557)

---

NEWS.md
THIRD_PARTY_NOTICES.md
third_party_manifest.json

* Upgrade @grpc/grpc-js to v1.2.5 to fix non-propagation of internal http2 errors
Now allows minor and patch auto-updates.
* Added workflow for publishing to npm when a v* tag is pushed to the repo.
* Fixes resolveMx test by using example.com for a valid exchange.
* PR: https://github.com/newrelic/node-newrelic/pull/606
* PR: https://github.com/newrelic/node-newrelic/pull/604
* PR: https://github.com/newrelic/node-newrelic/pull/603
* PR: https://github.com/newrelic/node-newrelic/pull/602
* PR: https://github.com/newrelic/node-newrelic/pull/594
* PR: https://github.com/newrelic/node-newrelic/pull/595

Update release notes

---

.github/workflows/create-release.yml
bin/check-workflow-run.js
bin/create-release.js
bin/generate-release-notes.js
bin/github.js
bin/update-changelog-version.js
package-lock.json
package.json

* Adds `Create Release` github actions workflow to create a release for `patch` or `minor` releases
* Updates agent version and adds release tags
Closes: #585

Adds create-release workflow and supporting scripts

---

.github/workflows/create-release.yml
bin/check-workflow-run.js
bin/create-release.js

* Update create-release action to use github.ref for branch input

Fix create-release action to use branch reference

---

lib/agent.js
lib/metrics/names.js

* Added support metric to be able to track usage of cert bundle via usage of custom certificates.
* Closes: https://github.com/newrelic/node-newrelic/issues/642
We always include the cert bundle if the certificates configuration item is populated. As such, tracking that as a proxy for the bundle.
Introduces a naming convention for tracking feature usage.

Adds support metric for cert usage.

---

.github/workflows/create-release-notes-pr.yml
bin/generate-release-notes.js

Allows just executing a GitHub action to generate the release notes & PR. This way we don't have to worry what state our local code is in for this part (still will for tagging/version-bump for now).
Example PR created: https://github.com/michaelgoin/node-newrelic/pull/10 (until fork deleted - i need to clean it up)
Example action run: https://github.com/michaelgoin/node-newrelic/runs/2035866658?check_suite_focus=true (util fork deleted)

Adds a GitHub action for generating the release notes PR.

---

.github/workflows/prepare-release.yml
bin/create-release-tag.js

* Updates prepare-release script name missed in previous update..
* Removes unnecessary null checks in create-release-tag script.

Minor release script tweaks

---

.github/workflows/prepare-release.yml

Adds input type to prepare release workflow.

---

.github/workflows/prepare-release.yml

Bad indentation resulted in workflow not parsing correctly. This should resolve.

Fixes inputs indentation in prepare-release workflow.

---

bin/prepare-release.js

Updates prepare-release PR name to Release vX.X.X.

---

docs/developer-setup.md
docs/function-wrapping.md
docs/module-instrumentations.md

* Added new developer documentation to /docs folder.
This information is ported over from private GHE wiki used prior to going open source. S/O @astorm for original versions of the function wrapping and module instrumentation docs. 
Made some tweaks to remove some internal-only deets, make code links work, etc. Hopefully I caught everything or didn't miss anything not true anymore.
Added some additional "how we work" notes to the developer setup doc just to give a high level summary. Would read through that and make sure nothing misleading/confusing there. We may eventually want a more robust writeup in its own doc.

Port New Developer Documentation

---

bin/.eslintrc.js
bin/check-workflow-run.js
bin/create-github-release.js
bin/create-release-tag.js
bin/prepare-release.js
bin/test-naming-rules.js
package.json

* Added linting to scripts in /bin folder.
Linting rules added are slightly more permissive than production rules and allow full ecma 8.

Adds linting to scripts in bin folder and cleans up existing.

---

lib/shim/shim.js

* Added module root to shim.require() logging to aid debugging.

Adds module root to shim.require() logging to make issues more clear.

---

THIRD_PARTY_NOTICES.md
third_party_manifest.json

Updates third party notices.

---

newrelic.js
test/lib/metrics_helper.js
test/unit/api/api-get-linking-metadata.test.js
test/unit/instrumentation/http/no-parallel/queue-time.test.js
test/unit/metrics-recorder/http.test.js
test/unit/metrics-recorder/queue-time-http.test.js
test/unit/shim/transaction-shim.test.js

* Distributed tracing is set to enabled in the `newrelic.js` template configuration file supplied with the agent.
Closes: #704

Distributed tracing is set to enabled in newrelic.js template configuration file

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Bumped @grpc/grpc-js to ^1.2.11.
* Bumped @grpc/proto-loader to ^0.5.6.

Bump grpc js dependencies

---

examples/shim/Messaging-Simple.md

- Fix images for improved reader experience.

Fix image links in Messaging-Simple.md

---

lib/collector/facts.js
test/unit/facts.test.js

* Log all New Relic metadata env vars at startup
Closes: #497

logged all new relic metadata to debug level in facts collector

---

README.md

are used within agent or used to accompany NR features
* Add resources to README to highlight external modules that customers should be aware of and possibly use for their applications.
Closes: #496

Added resources to Getting Started to highlight external modules that

---

lib/instrumentation/fastify.js

* Removed commented-out console log from fastify instrumentation.

Removes commented-out console log from fastify instrumentation.

---

package-lock.json
package.json

* Bumped `@newrelic/test-utilities` to ^5.1.0.

Bumps @newrelic/test-utilities to ^5.1.0.

---

test/integration/agent/lasp-send-trace.tap.js
test/integration/lasp_connect.tap.js

* Fixed LASP/CSP tests so they don't skip on runs where secrets are available.

Fixes LASP tests so they don't skip on main repo runs.

---

package-lock.json
package.json

* Upgraded https-proxy-agent to v5.0.0.

Upgrade https-proxy-agent to v5.0.0

---

lib/feature_flags.js

***BREAKING CHANGE***
* Defaulted `config.feature_flags.certificate_bundle` to false
Closes #665

flipped certifcate_bundle flag to default to false

---

index.js
package.json

* Added check for minimum `node` version >= 12.
* Set package.json engines `node` field >= 12 and `npm` field to >=6.
Closes: #797

Update Nodejs engines field to >=12

---

test/versioned/amqplib/package.json
test/versioned/bluebird/package.json
test/versioned/cassandra-driver/package.json
test/versioned/cls/package.json
test/versioned/connect/package.json
test/versioned/director/package.json
test/versioned/express/package.json
test/versioned/fastify/package.json
test/versioned/generic-pool/package.json
test/versioned/hapi/hapi-17/package.json
test/versioned/hapi/hapi-post-18/package.json
test/versioned/hapi/hapi-pre-17/package.json
test/versioned/ioredis/package.json
test/versioned/mongodb/package.json
test/versioned/mysql/package.json
test/versioned/mysql2/package.json
test/versioned/pg/pg-post-7/package.json
test/versioned/pg/pg-pre-7/package.json
test/versioned/redis/package.json
test/versioned/restify/restify-post-7/package.json
test/versioned/restify/restify-pre-7/package.json

* Updated engines stanza in versioned test modules
Closes #817 
A few updates created either redundant or non-applicable test suites.

updated engines stanzas in versioned tests

---

test/integration/instrumentation/http.tap.js
test/integration/instrumentation/q.tap.js
test/integration/instrumentation/when.tap.js
test/integration/transaction/tracer.tap.js
test/lib/agent_helper.js
test/unit/errors/error-collector.test.js
test/unit/instrumentation/core/domain.test.js
test/unit/instrumentation/core/globals.test.js
test/unit/instrumentation/http/http.test.js
test/unit/serverless/aws-lambda.test.js

* Removed comments around replacing `temporarilyOverrideTapUncaughtBehavior` test helper function.
* Closes: https://github.com/newrelic/node-newrelic/issues/799
Some other minor cleanup in http test to remove unnecessary items.

Removes comments around replacing uncaught tap override 

---

THIRD_PARTY_NOTICES.md
third_party_manifest.json

Not leaving a specific release note as this is inferred with the tap upgrade and we haven't shipped yet

Updates third party notices for recent tap and external module updates.

---

package.json

Shamelessly add myself to the contributors list

add myself to contributors list

---

lib/instrumentation/mongodb.js
test/integration/core/dns.tap.js
test/versioned/mongodb/collection-common.js
test/versioned/mongodb/db.tap.js
test/versioned/mongodb/package.json
test/versioned/mysql/basic-pool.tap.js
test/versioned/mysql2/basic-pool.tap.js

* Added additional instrumentation to properly set the collection on versions `>= 3.3.0`
* Updated mongo versioned stanzas to run all tests on versions `<4`
Closes #794 
Closes #793

fixed mongo issues related to 3.6.x

---

THIRD_PARTY_NOTICES.md
third_party_manifest.json

Update third party notices for release

update third party notices for release

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated `@newrelic/oss-cli` to `0.0.2` which fixed the `LICENSE`

fixed license for newrelic oss cli

---

test/unit/instrumentation/connect.test.js
test/unit/instrumentation/generic-pool.test.js
test/unit/instrumentation/hapi.test.js
test/unit/instrumentation/memcached.test.js
test/unit/instrumentation/postgresql.test.js
test/unit/instrumentation/redis-connection.js
test/unit/instrumentation/redis.test.js

* Ported remaining mocha tests in `test/unit/instrumentation` to exclusively use tap.

ported remaining instrumentation unit tests to use tap exclusively

---

test/unit/instrumentation/memcached.test.js

Removed stubbed out tests in memcached unit tests

removed todo tests in memcached

---

lib/spans/span-event-aggregator.js
test/unit/spans/span-event-aggregator.test.js

- Added supportability metric SpanEvent/Limit
- Closes https://github.com/newrelic/node-newrelic/issues/862

log SpanEvent/Limit

---

test/unit/util/byte-limit.test.js
test/unit/util/codec.test.js
test/unit/util/logger.test.js

* Migrated util unit tests from mocha to tap

migrated remaining utils unit tests to tap

---

lib/spans/span-event-aggregator.js
test/unit/spans/span-event-aggregator.test.js

* Updated default span event limit to 2000.
Closes: #854

Update default span event limit to 2000

---

test/unit/analytics_events.test.js

- Transitioned analytics_events.js to Tap from using Mocha globals.

transition analytics_events.js to tap from mocha globals

---

test/lib/agent_helper.js
test/unit/shim/message-shim.test.js
test/unit/shim/shim.test.js
test/unit/shim/transaction-shim.test.js
test/unit/shim/webframework-shim.test.js

* Ported `webframework-shim`, `shim`, and `transaction-shim` tests to use TAP

Shim tests to tap pt2

---

lib/config/default.js
test/integration/cat/background.tap.js
test/integration/cat/cat.tap.js
test/integration/cat/cross_process.tap.js
test/integration/cat/server2.js
test/unit/agent/intrinsics.test.js
test/unit/db/query-trace-aggregator.test.js
test/unit/errors/error-collector.test.js
test/unit/instrumentation/http/http.test.js
test/unit/instrumentation/http/outbound.test.js
test/unit/shim/message-shim.test.js
test/unit/transaction.test.js
test/versioned/amqplib/callback.tap.js
test/versioned/amqplib/promises.tap.js
test/versioned/express/segments.tap.js
test/versioned/hapi/hapi-17/segments.tap.js
test/versioned/hapi/hapi-post-18/segments.tap.js
test/versioned/hapi/hapi-pre-17/segments-v16.tap.js

* Distributed tracing enabled by default.
Closes: #855

Enable dt by default

---

test/unit/shim/message-shim.test.js

* Fixed `message-shim` test assertion to avoid flakiness based on precision differences(ms vs ns)

Message shim failure

---

lib/config/default.js

Update harvest interval in comments

---

lib/config/default.js
lib/config/index.js
test/unit/config/config-defaults.test.js
test/unit/config/config-server-side.test.js
test/unit/errors/error-collector.test.js
test/unit/instrumentation/http/http.test.js
test/unit/instrumentation/http/outbound.test.js
test/unit/instrumentation/http/synthetics.test.js
test/unit/shim/message-shim.test.js
test/unit/shim/transaction-shim.test.js
test/unit/transaction.test.js
test/versioned/amqplib/callback.tap.js
test/versioned/amqplib/promises.tap.js

* **Deprecation Warning**: Cross Application Tracing (CAT) has been deprecated and will be removed in a future major release. For applications that explicitly disable Distributed Tracing (DT) to leverage CAT, we recommend migrating to DT to avoid loss of cross-service visibility.
* Disables CAT by default. You must explicitly enable CAT along with turning off DT.
* Adds a deprecation warning when CAT is enabled and active (DT disabled).
* https://github.com/newrelic/node-newrelic/issues/895
Logs the following warning once, after applying server configuration:
```
[Deprecation Warning]: Cross Application Tracing (CAT) has been deprecated and will be removed in a future major release. CAT has been replaced by Distributed Tracing (DT). Enable DT by setting distributed_tracing: { enabled: …
```

Deprecates Cross Application Tracing (CAT).

---

lib/shim/transaction-shim.js
test/unit/shim/transaction-shim.test.js
test/versioned/amqplib/callback.tap.js
test/versioned/amqplib/promises.tap.js

* Fixed issue where DT headers would not be processed by `transaction-shim.handleCATHeaders()` when CAT was explicitly disabled. This primarily impacts `amqplib` instrumentation.
* Fixes: https://github.com/newrelic/node-newrelic/issues/900
Given our intent to rip out CAT, I opted for a pretty simple reorganization of the logic and added some TODO reminders.

Fixes transaction-shim.handleCATHeaders() handling of DT headers

---

test/integration/instrumentation/http-outbound.tap.js

* Replaced http-outbound test call to use example.com to avoid unpredictable connection resets.
My spellcheck was also unhappy so resolved some misspellings.

Resolve http outbound test flicker

---

examples/shim/Datastore-Simple.md

- Closes https://github.com/newrelic/node-newrelic/issues/564
- See also: https://github.com/newrelic/node-newrelic/pull/910
Updates the datastore example to reflect the current state of instrumentation. A different issue should cover a rearchitecture of our docs away from implementation-sensitive examples.

fix cassandra example

---

lib/collector/http-agents.js
lib/collector/remote-method.js
lib/config/attribute-filter.js
lib/db/parsed-statement.js
lib/metrics/mapper.js
lib/metrics/normalizer/tx_segment.js
lib/sampler.js
lib/shim/datastore-shim.js
lib/util/label-parser.js
lib/util/properties.js
test/unit/sampler.test.js

* Removed warnings from agent for `no-var` eslint rule.
We still have 65 warnings in tests but wanted to separate them

removed no-var warnings from code

---

package.json
third_party_manifest.json

🎉 Add Diana to the contributors list 🎉

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
test/versioned/fastify/add-hook.tap.js
test/versioned/fastify/common.js
test/versioned/fastify/errors.tap.js
test/versioned/fastify/fastify-2-naming.tap.js
test/versioned/fastify/fastify-3-naming.tap.js
test/versioned/fastify/naming-common.js
test/versioned/fastify/new-state-tracking.tap.js
test/versioned/fastify/package.json
third_party_manifest.json

* Added parameterized route transaction naming tests to Fastify versioned test suite
Closes #928 
I tried to refactor most of the copy pasta and encapsulate into common and naming-common.  I honestly have no idea what the errors.tap.js is testing or if it's just a sanity check.  But I did add an actual assertion instead of assuming if it doesn't reject a promise it's ok.

Fastify versioned tests

---

THIRD_PARTY_NOTICES.md
bin/run-versioned-tests.sh
package-lock.json
package.json
third_party_manifest.json

* Updated `@newrelic/test-utilities` to 6.1.1 and applied a global sampling value of 10 for versioned tests

updated test utils and applied global sampling at 10

---

README.md

* Updated README to favor using `-r` to load the agent vs `require('newrelic')`

favor -r vs require in app

---

test/unit/logger.test.js

* Migrated logger unit tests from mocha to tap

converted logger tests from mocha to tap

---

test/unit/utilization/common.test.js
test/unit/utilization/main.test.js

* Migrated utilization unit tests from mocha to tap

migrated utilization unit tests to use tap

---

lib/parse-proc-cpuinfo.js
lib/parse-proc-meminfo.js
test/unit/parse-proc-cpuinfo.test.js
test/unit/parse-proc-meminfo.test.js

* Fixed bug where failure to retrieve CPU/Memory details for certain Linux distros could result in a crash.
`parseProcCPUInfo` and `parseProcMeminfo` now check for `null` input prior to processing. 
* Fixes: https://github.com/newrelic/node-newrelic/issues/967
Also fixed a misspelling.

Adds graceful handling of null input to cpu and memory parse proc methods

---

test/versioned/mongodb/package.json

* Pinned mongo versioned tests to `<4.2.0` until we can address https://github.com/newrelic/node-newrelic/issues/982

pin mongo versioned tests to <4.2.0 as it no longer supports mongo v2

---

test/versioned/redis/package.json

Limits redis major version to get CI green. V4 was shipped 6 days ago and is causing failures. Will deep-dive into if this is just a test-setup issue or an instrumentation issue. Will either fix as a follow-up or submit a GitHub issue.

Limits redis version.

---

api.js
lib/shimmer.js
test/integration/api/instrument-loaded.tap.js
test/unit/api/api-instrument-loaded-module.test.js

* Fixed an issue where multiple calls to `instrumentLoadedModule` resulted in re-instrumenting the same module.
* Fixed issue where `instrumentLoadedModule` would return `true` even if the instrumentation handler indicated it did not apply instrumentation.
* Fixes: https://github.com/newrelic/node-newrelic/issues/905

Fixes an issue where multiple calls to instrumentLoadedModule resulted in reinstrumenting

---

lib/config/index.js

* Fixed issue where expected status code ranges would not be parsed until ignored status codes were also defined.

fix canonicalization if-condition

---

.github/workflows/add-to-board.yml
.github/workflows/board.yml

* Changed the event type from `pull_request` to `pull_request_target` to allow for auto assign of PRs to the Node.js Engineering Board

fixes the event type to use pull_request_target to allow for auto assign

---

.github/workflows/board.yml

* Fixed event name for adding PRs to board from `pull_request` to `pull_request_target`

changed event name from pull_request to pull_request_target

---

.github/workflows/prep-release.yml

* Added an input `changelog_file` to pass in name of changelog.  This defaults to `NEWS.md` but some repos use `CHANGELOG.md`

pass in changelog to prepare-release.js

---

.github/workflows/post-release.yml

* Added `workflow_dispatch` to Agent Post Release workflow for manual testing.

added workflow_dispatch on post release for testing or failure issues in future

---

package-lock.json

* `package-lock.json` updates to clear up dependabot and some npm audit warnings.

Cleans up resolvable npm audit / dependabot warnings.

---

.github/workflows/notify-release.yml

* Updated the pending-prs job to use the org level GitHub personal access token so we can report on private repos.
Closes #1061

Update token for pending prs job

---

.github/workflows/add-to-board.yml

* Updated `add-to-board` to use org level `NODE_AGENT_GH_TOKEN`
Fixes #1052

Changed secret for gh_token in add to board

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Bumps @newrelic/aws-sdk to ^4.1.1.
4.1.0 had a critical bug, so bump the desired deps greater than that.

Bumps @newrelic/aws-sdk to ^4.1.1. 

---

bin/create-docs-pr.js

* Fixed minor formatting and spelling issues in `create-docs-pr.js`.

Minor formatting and spelling fixes for create-docs-pr.js.

---

.github/workflows/post-release.yml

* Fixed conditions in post release workflow to function when triggered via successful release and manual invoked.
I tested this with `act`
```sh
act workflow_dispatch -e test.json -W .github/workflows/post-release.yml
```
```json
{
"workflow_dispatch": {
"action": "in_progress"
}
}
```
This started the workflow.
This also worked when I ran
```sh
act workflow_dispatch -e test.json -W .github/workflows/post-release.yml
```
```json
{
"workflow_run": {
"conclusion": "success"
}
}
```
It was skipped when payload was
```json
{
"workflow_run": {
"conclusion": "error"
}
}
```

Fix post release script 

---

README.md

* Updated README to include `@newrelic/pino-enricher` as an external module.

Updated external module list to include Pino enricher

---

package-lock.json

* Resolved several npm audit warnings for dev deps.

Fixes some npm audit warnings.

---

package-lock.json

* Bumped follow-redirects to resolve dev-dependency audit warning.

Bumps follow-redirects to resolve dev-dependency audit warning.

---

lib/shim/webframework-shim.js

* Added `Nextjs` to a framework constant within the webframework-shim.
Closes https://github.com/newrelic/newrelic-node-nextjs/issues/30

adding Nextjs to shim framework list

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Bumped `@newrelic/native-metrics` to ^7.1.1.

Bumps @newrelic/native-metrics to ^7.1.1.

---

test/versioned-external/external-repos.js

* Added newrelic-node-nextjs to external versioned tests to be run on every PR.
Closes [#32](https://github.com/newrelic/newrelic-node-nextjs/issues/32)
This cannot be merged until we make the newrelic-node-nextjs repo public.

added next repo for versioned testing with agent

---

test/integration/pricing/vendor-info-tests.js

* Added nock delay to test timeouts in utilization integration tests.
I noticed this while doing #1101.  We were patching http.get to return a timeout or a normal callback, thus overwriting business logic and also making it untestable.  This lead to less test coverage because the utilization/common implemented logic for aborting/timing out requests.  MOAR coverage ftw!

rely on nock delay instead of mocking http request to timeout in certain cases

---

README.md

* Added Next.js to External Modules list in README.

added nextjs to external module list

---

README.md

* Added link to New Relic Node.js Examples repository.

added link to example repo

---

.github/workflows/test-specific.yml

This PR adds a manual workflow for testing specific versioned test suites. This will allow us to isolate CI failures without running the whole CI job suite again.

add workflow to test specific versioned dirs

---

lib/instrumentation/@node-redis/client.js
lib/instrumentations.js
test/versioned/redis/package.json
test/versioned/redis/redis-v4.tap.js

- Support automatic instrumentation of Redis v4
- Closes https://github.com/newrelic/node-newrelic/issues/995

redis v4 instrumentation

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
test/versioned/winston/package.json
test/versioned/winston/winston.tap.js
third_party_manifest.json

This upgrades the agent to the proper version of log enricher to be used when we ship application logging.  I also added a versioned test that proves that the log enricher can co-exist with application logging

upgraded log enricher in agent and added versioned test around running agent with logging and log enricher

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Upgraded `@grpc/proto-loader` to fix a [CVE](https://security.snyk.io/vuln/SNYK-JS-PROTOBUFJS-2441248) with `protobufjs`.
* Upgraded `@newrelic/test-utilities` to resolve a dev-only audit warning.
Closes #1203

upgrades @grpc/proto-loader and @newrelic/test-utilities to fix known CVEs

---

lib/aggregators/log-aggregator.js
test/unit/aggregators/log-aggregator.test.js

* Do not aggregate or forward logs when the maximum sample size has been set to zero.
* https://github.com/newrelic/node-newrelic/issues/1194
* https://github.com/newrelic/newrelic-dotnet-agent/issues/1088
This is a draft PR meant to illustrate the issue. It will be marked ready for review once we are confident that it correctly models the problem and contains a robust solution.

Do not aggregate logs if log aggregation is disabled server-side.

---

lib/instrumentation/@grpc/grpc-js.js
lib/instrumentations.js
test/unit/grpc/client.test.js
test/versioned/grpc/grpc.tap.js
test/versioned/grpc/newrelic.js
test/versioned/grpc/package.json

- Closes https://github.com/newrelic/node-newrelic/issues/1246
This PR adds the basic files that will be necessary to prove correctness regarding gRPC client instrumentation. This includes an instrumentation file, a unit test file, and a versioned test apparatus. Some values or parameters have been commented out to satisfy the linter, but will need to be un-commented when these files are fleshed out by subsequent tickets.

scaffold grpc client instrumentation

---

bin/create-docs-pr.js
bin/create-github-release.js

* Added a support statement to our release notes (closes [NR-29755](https://issues.newrelic.com/browse/NR-29755))

gh-actions: add support statement to our automated release notes

---

.github/workflows/ci-workflow.yml
.github/workflows/smoke-test-workflow.yml
.github/workflows/test-specific.yml

* Added node 18 to CI workflows.
We will open a separate PR to drop node 12 but we have to wait until we release the agent with a few other changes first.

Add Node 18 to CI

---

lib/config/default.js
test/unit/config/config-defaults.test.js

* Enabled log forwarding by default.
Automatic application log forwarding is now enabled by default. This version of the agent will automatically send enriched application logs to New Relic. To learn more about about this feature, see the [APM logs in context documentation](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/get-started-logs-context/). For additional configuration options, see the [Node.js logs in context documentation](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-nodejs). To learn about how to toggle log ingestion on or off by account, see our documentation to [disable automatic logging](https://docs.newrelic.com/docs/logs/logs-context/disable-automatic-logging) via the UI or API.
* https://issues.newrelic.com/browse/NR-32288

Enables log forwarding by default.

---

.github/workflows/ci-workflow.yml
.github/workflows/publish-branch.yml
.github/workflows/smoke-test-workflow.yml
.github/workflows/test-specific.yml

Drops Node 12 from CI.

---

lib/util/application-logging.js
test/unit/util/application-logging.test.js

Backport of commit to the v8.17.0 tag

Added defensive code in util/applicationLogging truncate to check if value is string before checking its length

---

test/integration/distributed-tracing/dt.tap.js

Removed async library from distributed tracing integration test
https://issues.newrelic.com/browse/NR-35280

Refactored dt tap test to remove async lib

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Bumped external instrumentation to new major versions.
* Closes: https://issues.newrelic.com/browse/NR-35667
Test utils had already been updated with a separate PR.

Bumps minimum external instrumentation modules to new major versions.

---

test/versioned/cassandra-driver/query.tap.js
test/versioned/generic-pool/basic-v2.tap.js
test/versioned/generic-pool/basic.tap.js
test/versioned/mysql/helpers.js
test/versioned/mysql/setup.js
test/versioned/mysql2/setup.js
test/versioned/pg/pg.common.js

* Updated versioned tests to remove the use of the `async` module.
Closes https://issues.newrelic.com/browse/NR-39281

updated versioned tests to remove using the async module

---

test/.eslintrc.js
test/versioned/mongodb-esm/bulk.tap.mjs
test/versioned/mongodb-esm/collection-common.mjs
test/versioned/mongodb-esm/collection-find.tap.mjs
test/versioned/mongodb-esm/collection-index.tap.mjs
test/versioned/mongodb-esm/collection-misc.tap.mjs
test/versioned/mongodb-esm/collection-update.tap.mjs
test/versioned/mongodb-esm/common.cjs
test/versioned/mongodb-esm/cursor.tap.mjs
test/versioned/mongodb-esm/db.tap.mjs
test/versioned/mongodb-esm/newrelic.cjs
test/versioned/mongodb-esm/package.json

* Added mongodb ESM versioned tests
Closes NEWRELIC-3129

mongodb ESM versioned tests

---

test/.eslintrc.js
test/versioned/pg-esm/force-native.tap.mjs
test/versioned/pg-esm/native.tap.mjs
test/versioned/pg-esm/newrelic.cjs
test/versioned/pg-esm/package.json
test/versioned/pg-esm/pg.common.mjs
test/versioned/pg-esm/pg.tap.mjs

* Added Pg ESM versioned tests
Closes NEWRELIC-3128

Pg ESM versioned tests

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
test/.eslintrc.js
third_party_manifest.json

This removes the overrides of the `node/no-*-import` rules that have been added to our centralized ruleset for `test/versioned/**/**`.

updated eslint ruleset, removed overrides from agent

---

README.md
package.json
third_party_manifest.json

* Added information on using ESM loader to README.md
Closes NEWRELIC-3118

added info in readme around ESM

---

lib/config/default.js

We can't make this change until every other agent team does.

revert dcf904de3dc0c4c66d3bcf32cfe90b359d8d4a3c

---

README.md

* Added documentation about custom instrumentation in ES module applications
Part of [NEWRELIC-3777](https://issues.newrelic.com/browse/NEWRELIC-3777)

NEWRELIC-3777 esm instrumentation docs

---

test/versioned/mongodb-esm/collection-common.mjs
test/versioned/mongodb-esm/collection-index.tap.mjs
test/versioned/mongodb-esm/collection-misc.tap.mjs
test/versioned/mongodb-esm/common.cjs
test/versioned/mongodb-esm/cursor.tap.mjs
test/versioned/mongodb-esm/db.tap.mjs
test/versioned/mongodb/bulk.tap.js
test/versioned/mongodb/collection-common.js
test/versioned/mongodb/collection-find.tap.js
test/versioned/mongodb/collection-index.tap.js
test/versioned/mongodb/collection-misc.tap.js
test/versioned/mongodb/collection-update.tap.js
test/versioned/mongodb/common.js
test/versioned/mongodb/cursor.tap.js
test/versioned/mongodb/db.tap.js

We were getting random failures seemingly only on main.  I was able to reproduce but very unclear root cause.  I suspect it is because in db.tap.js we were dropping the database and it was the same for cjs and esm.  I updated esm to use a different database but also took the time to centralize both collections and databases in common.{js,cjs} so make this easier to maintain going forward.

Fixed mongo flapiness

---

documentation/feature-flags.md

Added a file and pattern for documenting current feature flags. 
https://issues.newrelic.com/browse/NEWRELIC-4457

Feature flag documentation

---

test/unit/shim/promise-shim.test.js
test/unit/trace-aggregator.test.js

Intended to drop async from promise shim test
https://issues.newrelic.com/browse/NR-39257
Currently in draft: this test still uses the async lib, as I'm running into failures in `tap` when I try to convert to async functions

NR-39257 dropping async from promise shim test

---

.github/workflows/repolinter.yml

We had upgraded most other workflows to remove deprecated versions of certain actions.  This updates the repolinter.

updated the version of github script to remove the deprecation warning

---

api.js
test/unit/rum.test.js

* addressed cognitive complexity and jsdoc issues in api.js
Closes NEWRELIC-5271
* Fixed all JSDoc warnings
* Removed cognitive-complexity override and brought all functions into compliance
* Added unit test to cover branch in RUM header generation that was missing

NEWRELIC-5271 api.js - addressed cognitive complexity and jsdoc issues

---

lib/agent.js
lib/util/attributes.js

* addressed cognitive complexity and jsdoc issues in lib/agent.js
Closes NEWRELIC-5273
* Fixed all JSDoc warnings
* Removed cognitive-complexity override and brought all functions into compliance

NEWRELIC-5273 lib/agent.js - address cognitive complexity and jsdoc issues

---

.eslintrc.js
lib/system-info.js
test/unit/facts.test.js
test/unit/system-info.test.js

Refactored `lib/system-info.js` to reduce complexity by switching to async/await instead of callbacks for async control
Closes NEWRELIC-5274
* Refactored `lib/system-info.js` to reduce complexity, specifically converted to using async/await from callbacks and breaking out logic branches into functions, main function `fetchSystemInfo` still accepts a callback to minimize change footprint
* Updated to use es2020 for eslint, need it for `?` operator and node14 has 95% compliance, should be safe
* Added unit tests to address drop in coverage from refactor
* Added JSDocs

NEWRELIC-5274 refactored system-info.js to reduce complexity

---

.eslintrc.js
lib/instrumentation/undici.js

Closes NEWRELIC-5284
The undici instrumentation was inline functions within a module.exports.  I reorganized slightly by calling a register hook function that sets up all the subscriptions to specific events but binds a function to execute.

Undici refactor

---

lib/config/attribute-filter.js

* Reduced cognitive complexity in lib/config/attribute-filter.js and enhance JSDocs
Closes NEWRELIC-5276
* Fixed JSDocs
* Refactored `_filter` function to be less complex (specifically, broke out the filtering bit)

NEWRELIC-5276 fix jsdocs and reduce complexity

---

lib/instrumentation/amqplib.js

Closes NEWRELIC-5281
Reduced redundant code by abstracting the channel instrumentation by passing in promise based branches.  I also added jsdoc and broke down inline functions

NEWRELIC-5281 refactored amqplib to be less complex and updated jsdoc

---

lib/instrumentation/mongodb/common.js

closes NEWRELIC-5291
Extracted out the logic to determine the host/port/db for relevant versions into their own functions to reduce the cognitive complexity.  I also updated the jsdoc to no longer have warnings.

mongo common refactor

---

lib/instrumentation/core/async-hooks.js
lib/instrumentation/core/globals.js
test/integration/core/native-promises/async-hooks.js

closes NEWRELIC-5287 
Honestly I wasn't going to do anything here as it's not really complex. The reason for the high measurement as the hook points are implemented within one object.  I extracted out the registration of the destroy hook as that's now optional.  I also renamed this file as it was bothering me that the case was snake when all other files are kebab.

async hooks instrumentation refactor

---

lib/agent.js
lib/errors/index.js

* Refactored the Exception class and its helpers to reduce the cognitive complexity. Additionally, fixed all JSDoc warnings.
Closes NEWRELIC-5280
Was able to leverage some of the abstraction work I did on the attribute-filters to simplify logic!

NEWRELIC-5280 refactored lib/errors/index.js to reduce complexity

---

bin/compare-bench-results.js
bin/run-bench.js
bin/utils.js
test/benchmark/shim/utilities.bench.js
test/benchmark/shimmer/instrumentation.bench.js
test/lib/benchmark.js

Removed deprecated and failing suites from benchmark tests. 
https://issues.newrelic.com/browse/NR-40029
This doesn't yet remove async, so it's a draft PR. But it might be useful if you're looking to run the benchmark tests.

drop async from benchmark

---

test/lib/agent_helper.js
test/versioned/express/segments.tap.js

This is intended to be used for all integration tests for CLM.  You can see it in action on express.

abstracted clm helper to assert the appropriate attrs on span

---

test/versioned/hapi/segments.tap.js

* Added versioned tests to assert that Code Level Metrics works with Hapi handlers, plugins, extensions, etc.
Closes NEWRELIC-5663

Hapi CLM tests

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated to latest version of `@newrelic/test-utilities`
* The koa versioned tests are pulled into the versioned test suite here, and has a need of a newly added assertion only available in the latest version (7.2.0) of the test utilities, so bumping the dep to fix the koa failures

Update to latest @newrelic/test-utilities

---

test/versioned/undici/requests.tap.js

Closes NEWRELIC-5504
If you look at the jira we have intermittent issues while running versioned tests with undici. It made calls to httpbin.org where apparently at times returns 500 errors.  The only versioned test coverage we lost is to a https url without port but we have unit tests that assert this logic. I could add a test that makes a request to https://example.com which we seem to do in the http outbound integration tests but I don't think it is worth the risk of it possibly failing even though I don't recall it ever failing in http outbound.

NEWRELIC-5504 replaces all external calls with a local http server instead of relying on httpbin.org

---

package-lock.json

This was brought to our attention from dependabot in #1473.  The only issue is for some reason the smoke tests are failing just in that branch. I cannot recreate locally so I'm going to try to open a PR myself for these fixes.

security fixes for dev deps

---

Migration Guide.md
NEWS.md
README.md

Fixing dead links in the docs.

docs: update API docs to remove docs/ path component

---

.eslintrc.js
THIRD_PARTY_NOTICES.md
api.js
package-lock.json
package.json
test/unit/api/api-obfuscate-sql.test.js
test/unit/api/stub.test.js
third_party_manifest.json

- WIP: add obfuscateSql to api
- updated eslint rules to get sonar from shared ruleset
* Exposed a method on API to obfuscate sql `newrelic.obfuscateSql`.
This will be used on the opentelemetry integration to obfuscate sql from OpenTelemetry database spans.

expose obfuscate

---

lib/metrics/normalizer.js

Reduced cognitive complexity in lib/metrics/normalizer.js
https://issues.newrelic.com/browse/NEWRELIC-5292
Closes NEWRELIC-5292

Reduced cognitive complexity

---

lib/config/default.js
test/unit/config/config-defaults.test.js
test/unit/config/config-env.test.js

* Added default configuration for security agent.
Closes NEWRELIC-7108

NEWRELIC-7108 added the base configuration for security agent

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

Upgraded @grpc/grpc-js from 1.8.9 to 1.8.10
Upgraded readable-stream from 3.6.0 to 3.6.1
https://issues.newrelic.com/browse/NEWRELIC-7616
Snyk PRs were failing versioned tests. This PR is an attempt to re-run and consolidate changes.
Closes NEWRELIC-7616

Updated @grpc/grpc-js, readable-stream

---

lib/metrics/normalizer/tx_segment.js

Reduced cognitive complexity in tx_segment.js
https://issues.newrelic.com/browse/NEWRELIC-5293

Reduced cognitive complexity in tx_segment.js

---

lib/transaction/index.js

* Reduced cognitive complexity in lib/transaction/index.js
https://issues.newrelic.com/browse/NEWRELIC-5301
Closes NEWRELIC-5301

Reduced cognitive complexity in transaction index

---

lib/transaction/trace/index.js

Refactored lib/transaction/trace/index.js to reduce cognitive complexity
https://issues.newrelic.com/browse/NEWRELIC-5303
Closes NEWRELIC-5303

Reduce cognitive complexity in lib/transaction/trace/index.js

---

lib/transaction/tracecontext.js

Refactored lib/transaction/tracecontext.js to reduce cognitive complexity
https://issues.newrelic.com/browse/NEWRELIC-5302
Closes NEWRELIC-5302

Reduced cognitive complexity in tracecontext

---

README.md
test/versioned-external/external-repos.js

This uses the koa branch that fixes issues when running full version matrix of koa tests

adds new branch for koa fixes

---

test/versioned-external/external-repos.js

All the fixes have landed so this restores the main branches to external repos.

restored branches of external versioned tests to main

---

lib/collector/serverless.js
lib/serverless/aws-lambda.js

Reduced cognitive complexity in lib/serverless/aws-lambda.js
Fixed JSDoc warnings in lib/collector/serverless
https://issues.newrelic.com/browse/NEWRELIC-5294
Closes NEWRELIC-5294
Smoke-tested on a Lambda function in Node 14, 16, and 18.

Reduced cognitive complexity in serverless lib

---

THIRD_PARTY_NOTICES.md
index.js
package-lock.json
package.json
test/integration/index/index-no-config.tap.js
test/unit/index.test.js
test/unit/mocks/agent.js
third_party_manifest.json

* Added ability to load security agent when `config.security.agent.enabled` is true.
Closes NEWRELIC-7110
I took this time to add a full unit test suite for index.js.  We have poor coverage and the lines covered weren't really asserted.
**Note**: This is merging into k2-release branch as we are working out details of landing functionality in main

feat: Added functionality to load security agent when config.security.agent.enabled is true

---

.github/workflows/post-release.yml

Updated token in post-release job
https://issues.newrelic.com/browse/NR-96240

fix: Updated post-release gh token

---

bin/test/conventional-changelog.test.js

Example failure: https://github.com/newrelic/node-newrelic/actions/runs/4917319600/jobs/8782254800
The markdown changelog is generated with a date, updated test harness to use Sinon's fake timers feature to lock the clock to a specific date so our assertion doesn't have to change every day.

test(scripts): fix failing changelog unit test

---

lib/config/index.js
test/unit/config/config-location.test.js
test/unit/config/config-server-side.test.js
test/unit/error_events.test.js
test/unit/errors/server-config.test.js
test/unit/facts.test.js

* Increased test coverage of `lib/config/index.js`
* NEWRELIC-5406
Also removes some dead code that isn't covered because it's dead.

fix(config): increase test coverage

---

changelog.json

We had to manually fix the docs website front matter [here](https://github.com/newrelic/docs-website/pull/13377). This just reconciles the source

ci: fixed changelog classification of a feature that was marked as a bug

---

test/unit/transaction.test.js

chore(tests): unmochaify transaction unit tests

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

Updated semver to 7.5.2
Updated @newrelic/native-metrics to 9.0.1
Updated @newrelic/test-utilities to 7.3.2
Closes #1682 
Closes NEWRELIC-9415

chore(deps): Updated semver, native-metrics, and test utils

---

test/unit/trace.test.js

Diff is easier to read if we ignore whitespace changes.
Closes #1677

chore(test): convert trace unit test to tap style

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated @newrelic/security-agent to v0.1.3 (NR-138580)

chore(deps): Updated security agent to v0.1.3

---

test/unit/errors/error-trace-aggregator.test.js
test/unit/errors/expected.test.js

Converted 'errors/expected.test.js' to tap-style
Closes #1691 
Closes NR-129164

chore(test): Converted 'errors/expected.test.js' to tap-style

---

test/unit/errors/server-config.test.js

Converted tests/unit/errors/server-config.test.js from mocha/chai to tap
Closes NR-139321

chore(test): Converted server-config.test.js to tap-style

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

There was a change in aws sdk 3.363.0.  We made a fix but we had a change queued up that was breaking, removing standalone functionality. We have to manually update the `@newrelic/aws-sdk` as it was a semver major.

build: updated `@newrelic/aws-sdk` to latest to get the instrumentation fixes for 3.363.0

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated @newrelic/security-agent to v0.2.0
* IAST data pull implementation
* Logging update
* Param fixes for mysql and file hooks.

chore(deps): Updated @newrelic/security-agent to v0.2.0

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated @newrelic/security-agent to v0.2.1
* Pinned check-disk-space to v3.3.1 to support Node.js v14
* deps: Updated semver to v7.5.4 and @aws-sdk/client-lambda to v3.363.0
* Add Node.js 20.x to CI

chore(deps): Updated @newrelic/security-agent to v0.2.1 

---

test/versioned-external/external-repos.js

We merged the PR to fix instrumentation in aws-sdk. I restored main for the aws-sdk versioned external tests.

chore: updated the aws-sdk external branch to be main now that the code is in there

---

THIRD_PARTY_NOTICES.md
lib/shimmer.js
package-lock.json
package.json
third_party_manifest.json

8.1.0 of test utils removed the patchModule and unpatchModule so I upgraded and removed those shimmer methods.

chore: upgraded test utils and removed unused shimmer.patchModule and shimmer.unpatchModule

---

lib/transaction/trace/index.js

perf: optimise Trace getTotalTimeDurationInMillis function (Complexity decreased from O(n^2) to O(n) where n=overall no. of segments)
It will optimise complexity of a function i.e. getTotalTimeDurationInMillis (which is used in endTransaction flow).
Context: 
https://github.com/newrelic/node-newrelic/issues/1775
Root cause:
We found a performance issue in newrelic agent code, where getTotalTimeDurationInMillis function's complexity  was of order O(n^2) which can be improved to O(n) with some simple code changes.
Currently, this function was using Array.concat function to append some other array elements, it's complexity is O(a+b) [a & b are array's lengths]. Since, this concat call was within a loop of segments, overall function's complexity is O(n^2) where n = overall no. of segments …

perf(Trace): optimise getTotalTimeDurationInMillis function to push to an array vs concat arrays.

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated @newrelic/security-agent to v0.3.0
* Last leg acknowledgement in IAST scanning.
* Fix for mysql query params in security events.
* Logging update for default log level and status file flags.
* Update in IAST batch size processing.
* Disable instrumentation when security enabled flag is set to false
* Readme update

chore(deps): Updated @newrelic/security-agent to v0.3.0

---

.eslintrc.js
test/lib/openai-mock-server.js
test/lib/openai-responses.js

This PR adds a mock OpenAI server utilizing the mock responses in the [python agent](https://github.com/newrelic/newrelic-python-agent/blob/02ad97def2808921f102dd7dc1b5e381d4ddaa7e/tests/mlmodel_openai/_mock_external_openai_server.py#L30-L166). This resolves #1846.

test: Added a mock server for openai testing

---

api.js
documentation/module-instrumentations.md
lib/instrumentation/openai.js
lib/llm-events/openai/feedback-message.js
lib/llm-events/tracked-ids.js
lib/transaction/index.js
test/unit/api/stub.test.js
test/unit/llm-events/openai/chat-completion-message.test.js
test/unit/llm-events/openai/feedback-message.test.js
test/versioned/openai/openai.tap.js

feat: Added API for tracking LLM feedback

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated @newrelic/security-agent to v0.5.0
* IAST support for NestJS framework
* Fixed constant in fs.open() hook
* Minor fix in applicationInfo for pod properties
* Upgraded ws to v8.14.2 and updated initialization of websocket for v8.x.
* Upgraded check-disk-space to v3.4.0
* Upgraded @aws-sdk/client-lambda to v3.436.0

chore(dep): Updated @newrelic/security-agent to v0.5.0

---

documentation/feature-flags.md
lib/feature_flags.js
test/unit/feature_flag.test.js

chore: Add AWS Bedrock feature flag

---

test/lib/agent_helper.js

Implemented [suggestion](https://github.com/newrelic/node-newrelic/pull/1919#discussion_r1432666980) from #1919.

refactor: updated how we get a random int in helper.randomPort by using crypto lib

---

lib/instrumentation/core/http.js

Chipping away at the remaining cognitive complexity violations. This refactors the core http instrumentation to remove the complexity violations.

refactor: Updated instrumentation/core/http.js to reduce the cognitive complexity to an allowable value

---

test/versioned/openai/chat-completions.tap.js
test/versioned/openai/embeddings.tap.js

missed it in the previous PR #1938

test: removed console log

---

lib/instrumentation/openai.js
test/versioned/openai/chat-completions.tap.js
test/versioned/openai/embeddings.tap.js

Add `llm: true` attribute to `Transactions` that contain llm spans. 
Added versioned tests. 
Closes #1944

feat: Add llm attribute to all transactions that contain llm spans for openai

---

package.json
third_party_manifest.json

We forgot to add James before and now Svetlana is onboard.

chore: updated contributors list to include james and svetlana 🎉

---

test/versioned/prisma/package.json

Prisma instrumentation broke, this is to free up CI to do other work until we can fix the issue.
#1984

test: pin prisma instrumentation testing to <5.9.0 until we can fix issues with instrumentation

---

documentation/feature-flags.md
lib/feature_flags.js
test/unit/feature_flag.test.js

feat: Add feature flag for LangChain instrumentation

---

lib/llm-events/event.js
lib/llm-events/langchain/chat-completion-message.js
lib/llm-events/langchain/chat-completion-summary.js
lib/llm-events/langchain/event.js
lib/llm-events/langchain/index.js
lib/llm-events/openai/event.js
test/unit/llm-events/langchain/chat-completion-message.test.js
test/unit/llm-events/langchain/chat-completion-summary.test.js
test/unit/llm-events/langchain/event.test.js

feat: Add message entities for LangChain

---

lib/llm-events/langchain/index.js
lib/llm-events/langchain/vector-search-result.js
lib/llm-events/langchain/vector-search.js
test/unit/llm-events/langchain/vector-search-result.test.js
test/unit/llm-events/langchain/vector-search.test.js

Based this pr on the message entities pr: https://github.com/newrelic/node-newrelic/pull/1983
Added unit tests. 
Closes #1978

feat: Add vectorsearch entities

---

THIRD_PARTY_NOTICES.md
package-lock.json
third_party_manifest.json

I noticed while reviewing #1997 the package-lock and third party notices were out of sync. This PR will fix that issue.

chore: Fixed third party notices and package-lock as they were out of sync.

---

README.md
THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* Updated @newrelic/security-agent to v1.0.1
* Reporting of framework in security event json 
* Updated software license to New Relic Software License Version 1.0
* Ability to send critical messages on successful startup of agent
* Updated Copyright headers
* Updated license in readme

chore(deps): Updated @newrelic/security agent to v1.0.1

---

THIRD_PARTY_NOTICES.md
lib/instrumentation/@elastic/elasticsearch.js
lib/instrumentation/@hapi/hapi.js
lib/instrumentation/@hapi/vision.js
lib/instrumentation/@node-redis/client.js
lib/instrumentation/@prisma/client.js
lib/instrumentation/amqplib/amqplib.js
lib/instrumentation/cassandra-driver.js
lib/instrumentation/connect.js
lib/shim/datastore-shim.js
lib/shim/shim.js
lib/shim/specs/index.js
lib/shim/specs/message.js
lib/shim/specs/operation.js
lib/shim/specs/params/datastore.js
lib/shim/specs/params/queue-message.js
package.json
test/unit/shim/shim.test.js
third_party_manifest.json

This PR is in service to https://github.com/newrelic/node-newrelic/issues/2022. I have skipped core to keep this specific PR manageable.
I am omitting the `cassandra-driver` update in this PR because, for some reason I cannot determine, the following test starts reporting `4` instead of `2`:
https://github.com/newrelic/node-newrelic/blob/f140ef1b7fba387cc10d183a855227981877738d/test/versioned/cassandra-driver/query.tap.js#L195

chore: Update specs @elastic through connect

---

test/versioned-external/external-repos.js

We had to update the versioned-external repo for aws-sdk instrumentation as there were dependent changes needed.  This has been merged so the branch has been restored to main.

test: Updated aws-sdk branch to main as the necessary code was merged.

---

lib/config/default.js
lib/llm-events/langchain/chat-completion-message.js
lib/llm-events/langchain/tool.js
lib/llm-events/langchain/vector-search-result.js
lib/llm-events/langchain/vector-search.js
lib/llm-events/openai/chat-completion-message.js
lib/llm-events/openai/embedding.js
test/unit/llm-events/langchain/chat-completion-message.test.js
test/unit/llm-events/langchain/tool.test.js
test/unit/llm-events/langchain/vector-search-result.test.js
test/unit/llm-events/langchain/vector-search.test.js
test/unit/llm-events/openai/chat-completion-message.test.js
test/unit/llm-events/openai/embedding.test.js

chore: Added ai_monitoring.record_content toggle

---

lib/instrumentation/langchain/tools.js
lib/llm-events/error-message.js
test/unit/llm-events/error.test.js
test/unit/llm-events/openai/error.test.js
test/versioned/langchain/tools.tap.js

Added `tool_id` to llm error message event. 
Updated tool versioned test
Closes #2063

feat: Added tool_id to langchain error event

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

Bump `@newrelic/aws-sdk` and `@newrelic/koa` to latest versions

chore: updated @newrelic/aws-sdk and @newrelic/koa to latest

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

* IAST support for grpc 
* Functionality to report API endpoints of the application
* IAST support for undici
* Updated permissions for file/directory created by security agent
* Bumped follow-redirects from v1.15.2 to v1.15.4  
* Updated axios to v1.6.8
* Bumped ip from v2.0.0 to v2.0.1
* Bumped undici from 5.28.2 to v5.28.3
* Readme update

chore(deps): Updated @newrelic/security-agent to v1.1.0

---

README.md

We are changing from HackerOne to BugCrowd for our bug bounty so the URL has changed

chore: Changed bug bounty URL

---

.github/workflows/prepare-release.yml

ci: Updated prepare release to provide a drop down for release type

---

.github/workflows/versioned-security-agent.yml

https://github.com/newrelic/node-newrelic/actions/runs/8628722440/job/23657242596#step:4:5
I'm not sure why it has suddenly started failing, but this should fix things.

chore: Fixed versioned security agent CI workflow

---

jsdoc-conf.jsonc

API docs broke in #2104. This re-includes api.js from the docs.

docs: Includes api.js in jsdoc generation

---

lib/instrumentation/openai.js
test/versioned/openai/common.js

This reverts commit d72d19bb3b4638fcf6324080bffd3f112fefb41f.

fix: Reverted openai instrumentation update to handle broken version of 4.40.1

---

.github/workflows/validate-pr.yml

Hopefully this fixes the stuck situation in #2185.

chore: Updated validate-pr workflow

---

.github/workflows/ci-workflow.yml

I messed up the logic on the "should_run" checks. This PR fixes it.

chore: Fixed conditionals in CI workflow

---

documentation/feature-flags.md
lib/feature_flags.js
test/unit/feature_flag.test.js

Adds a feature flag for `kafkajs` so we can ship things dark while we're working through the instrumentation.

feat: Added feature flag for `kafkajs` instrumentation

---

test/versioned/aws-sdk-v3/package.json

chore: Added a missing library we instrument to be picked up by the compatibility report

---

.github/workflows/ci-workflow.yml
THIRD_PARTY_NOTICES.md
package.json
third_party_manifest.json

Added Node 22 to CI
Closes #2171

ci: Added Node 22 to CI

---

index.js

feat: Updated minimum supported version to Node 22

---

package.json

Making it official, nice work @amychisholm03 👏

chore: Added @amychisholm03 to list of contributors 🎉

---

.github/workflows/smoke-test-workflow.yml
.github/workflows/versioned-coverage.yml
.github/workflows/versioned-security-agent.yml

ci: Added Node 22 to smoke tests and nightly versioned test runs

---

test/benchmark/datastore-shim/shared.js
test/benchmark/shim/record.bench.js
test/benchmark/shim/row-callbacks.bench.js
test/benchmark/shim/segments.bench.js
test/benchmark/webframework-shim/recordMiddleware.bench.js

The `recordMiddleware` got refactored to always require a spec and not a function to execute to get spec. This fixes the benchmark test
```
node test/benchmark/webframework-shim/recordMiddleware.bench.js
```
Closes NR-289151

test: Fixed recordMiddlewawre benchmark test

---

.github/workflows/board.yml

Testing out adding issues/PRs to new project board

ci: Changed the default project idea for our org board

---

.github/workflows/board.yml

Used [this doc](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions) to udpate our workflow to add items to board, not sure if it will work on not but ill test after merge.

ci: Updated board workflow to use new graphql calls to add items to project board

---

.github/workflows/board.yml

So the workflow I updated in #2354 and #2357 I didn't test properly. This time I replicated the flows locally and have confirmed it will add issues to Triage Needed and PRs to Needs PR Review.  In fact this PR should already work because that bit _was_ working.

ci: Fixed issue with obtaining node id for issues in add-to-board

---

.github/workflows/board.yml

ci: Fixed syntax issue with parsing jq

---

.github/workflows/board.yml

We migrated our project to a new project type. Yesterday I rushed to get a solution and realized there was a lot of redundant code.  This PR consolidates adding issue/pr to board and assigning it the appropriate status into one step of job.

refactor: consolidated adding issue/pr to board and assigning the appropriate status into 1 step

---

.github/workflows/board.yml

Next time we release, we have to remove all these rogue PRs, I'm sorry

chore: fix board refactor

---

lib/instrumentation/kafkajs/consumer.js
lib/instrumentation/kafkajs/index.js
lib/instrumentation/kafkajs/producer.js
lib/instrumentation/kafkajs/record-linking-metrics.js
lib/instrumentation/kafkajs/record-method-metric.js
test/versioned/kafkajs/kafka.tap.js

This PR resolves #2386.
I needed to refactor things a bit in order to record the brokers on client construction and then utilize those brokers across all of the instrumentation points.

chore: Added producer and consumer metrics to kafkajs instrumentation

---

lib/instrumentation/kafkajs/record-linking-metrics.js
test/versioned/kafkajs/kafka.tap.js

Fixes the metric names to properly link kafkajs calls with AWS MSK.
Closes #2457

fix: Updated the `kafkajs` node metrics to remove `/Named` from the name

---

test/versioned/koa/package.json

test: Skip `@koa/router@13.0.0` because of failures

---

test/unit/grpc/connection.test.js
test/unit/lib/logger.test.js
test/unit/utilization/common.test.js
test/unit/utilization/docker-info.test.js
test/unit/utilization/main.test.js

This PR resolves https://github.com/newrelic/node-newrelic/issues/2530.

test: Convert grpc, lib, and utilization tests to `node:test`

---

documentation/nextjs/faqs/cloud-providers.md

docs: Updated formatting of cloud-providers.md

---

SECURITY.md

This PR is to remove the SECURITY.md file from the repository, as SECURITY.md files are centrally managed in the organization's [.github](https://github.com/newrelic/.github) repository. This allows for easy updates made by security in the future.

docs: Remove SECURITY.md

---

lib/instrumentation/when/index.js
lib/shim/shim.js

This PR updates the 2 places that are not using the tracer to run a function with the context manager. The intention is to start centralizing/encapsulating certain actions to make it easier to deconstruct segments.

feat: Updated shim/when instrumentation to use tracer to run in context

---

lib/instrumentation/amqplib/nr-hooks.js
test/versioned/amqplib-esm/issue-2663.test.mjs
test/versioned/amqplib-esm/newrelic.cjs
test/versioned/amqplib-esm/package.json

fix: Fixed amqplib instrumentation via ESM

---

bin/run-bench.js
test/benchmark/Readme.md
test/benchmark/lib/db/query-parsers/sql.bench.js

chore: Added a benchmark script for our sql parser

---

lib/instrumentation/core/http-outbound.js
test/integration/instrumentation/http-outbound.tap.js

This enhancement would improve observability for applications using proxies, enabling us to monitor actual external service calls more accurately.
https://github.com/newrelic/node-newrelic/issues/2688

feat: Enhance Proxy Request Handling to Display Actual External URLs

---

test/versioned/mongodb-esm/test-assertions.mjs

Tiny change in mongodb-esm helper to removed an unused arg.

chore: Removed unused code

---

NEWS.md

chore: fixed changelog

---

test/smoke/agent/agent-restart-listener.test.js
test/smoke/agent/lasp-send-trace.test.js
test/smoke/agent/start-stop.test.js
test/smoke/e2e/express.test.js
test/smoke/index/index-bad-version.test.js
test/smoke/index/index.test.js

test: Migrated smoke tests in `test/smoke/agent`, `test/smoke/e2e`, and `test/smoke/index` to `node:test`

---

test/smoke/api/connection.test.js
test/smoke/api/error-data.test.js
test/smoke/api/metric-data.test.js
test/smoke/api/transaction-sample-data.test.js

test: Migrated `test/smoke/api` tests to `node:test`

---

NEWS.md
changelog.json

Group the tags in logs work to 1 bullet

docs: fixed changelog to group the labels in logs work

---

test/lib/test-reporter.mjs

As titled:
<details>
<summary>Example</summary>
```
❯ npm run unit                                                                       
> newrelic@12.8.0 unit
> rm -f newrelic_agent.log && time c8 -o ./coverage/unit borp --timeout 180000 --reporter ./test/lib/test-reporter.mjs 'test/unit/**/*.test.js'
passed: /Users/jsumners/Projects/team-repos/node-newrelic/test/unit/urltils.test.js (62.38 ms)
passed: /Users/jsumners/Projects/team-repos/node-newrelic/test/unit/transaction.test.js (442.3 ms)
passed: /Users/jsumners/Projects/team-repos/node-newrelic/test/unit/transaction-naming.test.js (11.19 ms)
passed: /Users/jsumners/Projects/team-repos/node-newrelic/test/unit/transaction-logs.test.js (1.239 ms)
passed: /Users/jsumners/Projects/team-repos/node-newrelic/test/unit/transaction-event-aggre …
```

chore: Added per test file timing to test reporter

---

test/integration/distributed-tracing/background.test.js
test/integration/distributed-tracing/dt.test.js
test/integration/distributed-tracing/span-error-attributes.tap.js
test/integration/distributed-tracing/trace-context-cross-agent.test.js
test/integration/distributed-tracing/transaction-span-attributes.test.js

chore: Updated distributed-tracing integration tests to node:test

---

test/lib/custom-assertions/assert-segments.js

chore: Improved documentation for assertSegments

---

lib/otel/rules.js
test/unit/lib/otel/rules.test.js

I found out that I didn't account correctly for the fallback rules in my original implementation. This fixes the problem.

chore: Updated rules engine to account for fallbacks

---

.borp.int-esm.yaml
.borp.int.yaml

chore: Updated borp configs to target tests correctly

---

test/versioned/mysql2/promises.test.js

chore: Cherry pick mysql2 fix to next branch

---

lib/otel/rules.json
lib/otel/segment-synthesis.js
lib/otel/segments/consumer.js
lib/otel/segments/index.js
lib/transaction/index.js
test/unit/lib/otel/consumer.test.js

This PR resolves #2651. It replaces #2834.

feat: Added otel consumer span processing

---

.github/workflows/ci-workflow.yml

We were out of date on the codecov-action and have seen random failures around posting coverage. Bumping this to the latest release to see if it fixes the issues.

ci: Updated codecov-action to latest released version sha

---

test/versioned/langchain/vectorstore.test.js

This test previously got the version of `@langchain/core` assuming all other deps shared it. However, the peer version of `@langchain/core` has diverged
between `@langchain/community` and `@langchain/openai`.  This PR just finds the tracking metric that starts with `Supportability/Nodejs/ML/Langchain` and asserts the call count. 
```sh
npm run versioned:internal langchain
```

test: Updated a langchain test to be less rigid on asserting the tracking metric by `@langchain/core` version

---

THIRD_PARTY_NOTICES.md
package.json
third_party_manifest.json

Bump of `import-in-the-middle` to support import attributes (through `acorn`).
Currently when using import attributes, the following error is logged:
```
Error: 'import-in-the-middle' failed to wrap '...'
```

chore: Updated import-in-the-middle version

---

THIRD_PARTY_NOTICES.md
lib/otel/constants.js
lib/otel/segments/consumer.js
lib/otel/segments/database.js
lib/otel/segments/http-external.js
lib/otel/segments/producer.js
lib/otel/segments/server.js
lib/otel/setup.js
lib/otel/span-processor.js
package.json
test/unit/lib/otel/consumer.test.js
test/unit/lib/otel/fixtures/db-sql.js
test/unit/lib/otel/fixtures/http-client.js
test/unit/lib/otel/fixtures/producer.js
test/unit/lib/otel/fixtures/server.js
test/unit/lib/otel/segment-synthesizer.test.js
third_party_manifest.json

chore: Localized OTEL attribute constants

---

lib/otel/segments/consumer.js
lib/otel/span-processor.js
lib/spans/span-event.js
test/unit/lib/otel/consumer.test.js
test/versioned/otel-bridge/span.test.js

chore: Added consumer attribute reconciliation

---

README.md

I also did some minor formatting cleanup for consistency

chore: Clarified supported next.js middleware versions in docs

---

test/integration/distributed-tracing/trace-context-cross-agent.test.js

While working on #2989 I noticed these loops that could be simplified.

chore: Refactored loops to be simpler

---

lib/transaction/tracer/index.js
test/unit/api/api-start-background-transaction.test.js

Properly handle creating new transaction in `tracer.transactionNestProxy`.
Closes #3006

fix: Fixed `tracer.transactionNestProxy` to create a new transaction if there is no transaction or transaction is not active

---

THIRD_PARTY_NOTICES.md
lib/agent.js
lib/config/default.js
lib/otel/segments/utils.js
lib/shim/message-shim/subscribe-consume.js
lib/transaction/index.js
lib/transaction/tracecontext.js
lib/w3c/traceparent.js
lib/w3c/tracestate-intrinsics.js
lib/w3c/tracestate.js
package.json
test/integration/distributed-tracing/trace-context-cross-agent.test.js
test/integration/distributed-tracing/traceparent-sampled-flag.test.js
test/lib/agent_helper.js
test/unit/config/config-defaults.test.js
test/unit/distributed_tracing/tracecontext.test.js
test/unit/instrumentation/http/outbound.test.js
test/unit/lib/otel/segment-utils.test.js
test/unit/lib/w3c/traceparent.test.js
test/unit/lib/w3c/tracestate.test.js
test/unit/transaction.test.js
third_party_manifest.json

feat: Support honoring W3C traceparent sampled flag

---

lib/util/logger.js
lib/utilization/aws-info.js
lib/utilization/azure-info.js
lib/utilization/azurefunction-info.js
lib/utilization/docker-info.js
lib/utilization/ecs-info.js
lib/utilization/gcp-info.js
lib/utilization/index.js
lib/utilization/kubernetes-info.js
lib/utilization/pcf-info.js
test/unit/util/logger.test.js
test/unit/utilization/docker-info.test.js
test/unit/utilization/ecs-info.test.js

This PR improves the logging withing the utilization detection code. With these changes in place, we should have a much easier time reviewing what was detected during util inspection.

chore: Improved logging within utilization detection

---

THIRD_PARTY_NOTICES.md
documentation/otel/metrics.md
lib/agent.js
lib/config/default.js
lib/otel/bootstrap-metrics.js
lib/otel/metrics/bootstrap-metrics.js
lib/otel/metrics/proxying-exporter.js
lib/otel/setup.js
package.json
test/integration/otel/metrics.test.js
test/integration/otel/schemas/Readme.md
test/integration/otel/schemas/opentelemetry/proto/collector/metrics/v1/metrics_service.proto
test/integration/otel/schemas/opentelemetry/proto/common/v1/common.proto
test/integration/otel/schemas/opentelemetry/proto/metrics/v1/metrics.proto
test/integration/otel/schemas/opentelemetry/proto/resource/v1/resource.proto
test/unit/config/config-defaults.test.js
test/unit/lib/otel/bootstrap-metrics.test.js
test/unit/lib/otel/metrics/bootstrap-metrics.test.js
test/unit/lib/otel/metrics/proxying-exporter.test.js
third_party_manifest.json

chore: Improved setup of OpenTelemetry metrics API

---

test/versioned/google-genai/package.json

1.5.0 was a broken release, they have since fixed in 1.5.1. This PR updates the range to continue to test on future versions and just skips 1.5.0.

test: unpinned google genai tests

---

lib/w3c/tracestate.js
test/unit/distributed_tracing/tracecontext.test.js

fix: Fixed error logging for undefined tracestate header

---

.github/workflows/board.yml

Someone renamed our todo column and broke adding issues to the project board.
Closes #3177

ci: Fixed the name of todo colum in add to board reusable workflow

---

lib/config/default.js
lib/spans/helpers.js
lib/spans/span-event-aggregator.js
lib/spans/span-event.js
lib/spans/streaming-span-event-aggregator.js
lib/spans/streaming-span-event.js
test/unit/api/api-custom-attributes.test.js
test/unit/spans/create-span-event-aggregator.test.js
test/unit/spans/span-event-aggregator.test.js
test/unit/spans/span-event.test.js
test/unit/spans/streaming-span-event-aggregator.test.js
test/unit/spans/streaming-span-event.test.js

feat: Added ability to only report on entry and exit spans

---

lib/config/default.js
lib/config/index.js
test/unit/collector/facts.test.js

chore: Rename gcp id config flag

---

NEWS.md

docs: restore removal of enty/exit spans feature

---

test/integration/instrumentation/http-outbound.test.js
test/unit/spans/span-event.test.js

We had 2 test suites that were failing in Node 18. It was trying to make real requests and this PR now mocks those requests to avoid trying to make live http calls.
```sh
nvm use 18
node tests/unit/spans/span-event.test.js
node tests/integration/instrumentation/http-outbound.test.js
```

test: Updated tests to mock outgoing calls to avoid issues in CI

---

bin/run-bench.js

Bob and I were reviewing our benchmark test code and noticed that the coordinating GH action was not reporting a failure if any of the benchmark tests fail. This PR aims to "propagate" the failure, so that GH actions properly reports failure for a test that errors or exits abnormally.
Review [this run on my fork](https://github.com/amychisholm03/node-newrelic/actions/runs/16581118949) to see it properly fail.

ci: Fail benchmark ci if tests fail

---

test/versioned/nestjs/package.json
test/versioned/nestjs/test-app-replacements/app.controller.ts

We had failing tests on [11.0.9](https://github.com/nestjs/nest-cli/releases/tag/11.0.9). It looks like this was the [commit](https://github.com/nestjs/nest-cli/commit/5bbd8f83448aebdd9a965b4c81b3c8e27b56ca89). The community already filed https://github.com/nestjs/nest-cli/issues/3110. We will unpin once this has been fixed.

test: pin nestjs to avoid failure with cli

---

test/benchmark/http/server.bench.js

See successful run [here](https://github.com/amychisholm03/node-newrelic/actions/runs/16629230391).

test: Fix failing http benchmark test

---

lib/subscribers/mcp-sdk/client.js
test/unit/shimmer.test.js
test/versioned/mcp-sdk/client.test.js

feat: Disable MCP if `ai_monitoring` disabled

---

lib/instrumentation/core/http-outbound.js
lib/util/urltils.js
test/unit/instrumentation/http/outbound.test.js

refactor: Parse url only once in `http-outbound`

---

bin/run-bench.js
test/benchmark/Readme.md
test/benchmark/shimmer/instrumentation.bench.js
test/benchmark/shimmer/subscribers.bench.js

This PR resolves #3345. I also added one small test suite for subscriber-based methods within `shimmer`.

test: Fix long running benchmark test and add `shimmer.subscribers` benchmark test

---

THIRD_PARTY_NOTICES.md
esm-loader.mjs
lib/subscribers/create-config.js
lib/subscribers/openai/base.js
lib/subscribers/openai/chat.js
lib/subscribers/openai/config.js
package.json
third_party_manifest.json

The tracing-hooks and code-transformer projects have had some improvements recently.  This PR updates to the latest of tracing-hooks.
**Note**: The signature of the hooks changed slightly, which is why you see updates there. We can't remove the data structure around configs as we still need to group them by package name to initialize our agent config around enabling/disabling instrumentation.

chore: Updated `@apm-js-collab/tracing-hooks` to latest to take advantage of wasm optimizations

---

lib/config/default.js
lib/config/index.js
test/unit/config/config-defaults.test.js

feat: Add `adaptive_sampling_target` to config
