- lib/instrumentation/core/globals.js
It wasn't clear at first why you would throw sometimes but others here, so I researched and added a comment to leave a hint for the next code reader.
> Add code comment to explain conditional throw on unCaught exceptions

- lib/instrumentation/express.js
When you want to log data after rendering the view to the user, in multiple cases it is logging the error: "Cannot read property transaction of null".
With this fix we check if there is any tracer segment before the transaction, if not we do the same as the transaction is not active.
> Fix Cannot read property transaction of null

- lib/transaction/handle.js
- stub_api.js
Return actual transaction instance stub.
`getTransaction` returns a class instead of an instance of that class, this PR should fix that. It has been happening since https://github.com/newrelic/node-newrelic/commit/81a9803bf1c3ae436188d8078a814ea3d2712876 (converted from object to class, but forgot to update the usage in the stub itself).
@lykkin please.
> fix(stub): return actual transaction instance stub

- CONTRIBUTING.md
- lib/instrumentation/memcached.js
I am getting these errors:
> TypeError: Cannot read property 'split' of undefined\n    at Client.commandWrapper (/usr/app/node_modules/newrelic/lib/instrumentation/memcached.js:51:51)
on this line of code: `mycache.del(key)`
The del() call was after a key (probably) timed out or potentially removed by another pod.  I cannot replicate this in dev/staging though! >:O
I attempted to write integration tests, but could not get it to fail in this process:
1. Deleting a key after a delete
2. Deleting a key after previous key timed out
3. Deleting a key after end() entire cache.
> Prevent Memcached undefined error

- lib/config/index.js
- Fix misspelling of configuration
> Fix spelling error /confguration/configuration/

- lib/config/index.js
- test/unit/config/config.test.js
* Adds whitespace trimming of license key configuration values.
Previously, when a license key was entered with leading or trailing whitespace, it would be used as-is and result in a validation failure. This most commonly occurred with environment variable based configuration.
Flagging as "medium" risk just cause touches license keys but actual change is straightforward.
> Adds trimming of license key string to help avoid copy-paste issues.

- package-lock.json
- package.json
* Bumps @newrelic/native-metrics to ^5.1.0.
Upgraded nan to ^2.14.1 to resolve 'GetContents' deprecation warning with Node 14. This version of the native metrics module is tested against Node 14 and includes a pre-built binary download backup for Node 14.
* https://github.com/newrelic/node-native-metrics/pull/73
> Bumps @newrelic/native-metrics to ^5.1.0.

- .github/workflows/ci-workflow.yml
- .github/workflows/smoke-test-workflow.yml
- test/smoke/newrelic.js
Isolates this grouping's need for full-setup smoke testing to non-forked repo runs. Executes on repo branch pushes and a once-a-day scheduled run. Scheduled run accounts for catching server changes (eventually) during periods of time without branch pushes.
These tests actually pass if not validly setup cause then the agent just doesn't do anything. Eventually, some more robust smoke testing would be good. 
Given the dependency on a key, it made for a good first-pass at what this sort of smoke test job will look like. Long-term vision being we isolate a collection of smoke tests that need secrets and exercise a proper server to catch issues from our standard functionality tests intended for all PR's, including from forked repos.
I verified that a purely forked PR, w/o branch existing in …
> Extracts smoke tests to separate workflow.

- NEWS.md
* Bumped @newrelic/native-metrics to ^5.1.0.
Upgraded nan to ^2.14.1 to resolve 'GetContents' deprecation warning with Node 14. This version of the native metrics module is tested against Node 14 and includes a pre-built binary download backup for Node 14.
* Added whitespace trimming of license key configuration values.
Previously, when a license key was entered with leading or trailing whitespace, it would be used as-is and result in a validation failure. This most commonly occurred with environment variable based configuration.
* Moved to GitHub actions for CI.
* Updated PR template and added initial issue templates.
* Converted most of the collector API unit tests to use the tap API. Split larger test groupings into their own test files.
* …
> Updates release notes for 6.8.0.

- .github/workflows/ci-workflow.yml
- test/helpers/secrets.js
- test/integration/agent/agent-restart-listener.tap.js
- test/integration/agent/lasp-send-trace.tap.js
- test/integration/agent/serverless-harvest.tap.js
- test/integration/agent/start-stop.tap.js
- test/integration/api/connection.tap.js
- test/integration/api/error-data.tap.js
- test/integration/api/metric-data.tap.js
- test/integration/api/transaction-sample-data.tap.js
- test/integration/index/index-bad-config.tap.js
- test/integration/index/index-bad-version.tap.js
- test/integration/index/index.tap.js
- test/integration/lasp_connect.tap.js
- test/integration/proxy-api-connection-noproxy.tap.js
- test/integration/proxy-api-connection-port.tap.js
- test/integration/proxy-api-connection-ssl.tap.js
* Another follow up to the CI stuff, adding a failsafe. It forces tests that need secrets to run when the branch being run is master even if the secret they need is not available. This will force tests to fail, we'll be notified, and we can see why our secrets aren't working.
> Don't skip tests if secrets should be available

- .npmignore
* Added several items to `.npmignore` to prevent accidental publishing.
* https://github.com/newrelic/node-newrelic/issues/368
When publishing from a new location, I caught a few other things but missed that I had a rogue `newrelic_agent.log` hanging out. Our current `.npmignore` doesn't filter that out.
Long-term, using the "files" configuration which gives an allow-list will save us from such things including not needing to update for all possible cases in the future.
There's a backlog item and a community PR hanging-out around using the "files" list. That sort of change is higher-risk, though, as we could break something fundamental when we convert. As such, doing the quick fix now and leaving that for a more dedicated/careful approach.
> Adds commonly skipped items to npmignore to avoid accidentally publishing

- lib/serverless/event-sources.json
AWS released a new version of their API Gateway service. This adds support for V2.
v1: https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/sample-apps/nodejs-apig/event.json
V2: https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/sample-apps/nodejs-apig/event-v2.json
> Add AWS API Gateway V2 Support

- test/versioned/redis/redis.tap.js
* Fixed Redis client w/o callback versioned test flicker.
Doesn't end transaction until error encountered. Increases wait time for first operation which has to complete for the second operation to be successful.
Should reduce test flickers by not having a hard-set 100ms sleep for the operation. Relies on test framework timeout to end if call hangs. Worst case, will be easier to debug.
Did find second issue. The first key has to exist for the second call to fail. Increasing the timeout will still be somewhat fragile but trying not to have to do major surgery here.
> Waits for error to trigger on test before ending transaction.

- lib/spans/span-context.js
- lib/spans/span-event.js
- lib/spans/streaming-span-event.js
- lib/transaction/index.js
- lib/transaction/trace/segment.js
- lib/transaction/tracer/index.js
- test/integration/distributed-tracing/transaction-span-attributes.tap.js
- test/unit/api/api-custom-attributes.test.js
- test/unit/spans/span-event-aggregator.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
- test/unit/trace-segment.test.js
- test/unit/transaction.test.js
* Added `transaction.name` intrinsic to active span at time transaction name is finalized.
This enables finding transaction name for traces that may not have a matching transaction event.
* Removed allocation of logging-only objects used by transaction naming when those log levels are disabled.
This softly introduces the concept of a "span context" as a baby step towards decoupling spans from segments as a concept.
This PR is built on top of https://github.com/newrelic/node-newrelic/pull/366, which shoudl be merged first.
> Add transaction name to span as intrinsic

- README.md
- lib/metrics/normalizer.js
- Some internal cleanup to make navigating our code base a little more straight forward. `./normalizer/rule` exports a `NormalizerRule` constructor function, so lets import it with the same name -- came from some real world head scratching where we couldn't find where `NormalizerRule` was used.
> Import NormalizerRule as NormalizerRule instead of Rule

- NEWS.md
* Added AWS API Gateway V2 Support to lambda instrumentation.
* Added 'transaction.name' intrinsic to active span at time transaction name is finalized.
This enables finding transaction name for traces that may not have a matching transaction event.
* Added 'error.expected' attribute to span active at time expected error was noticed.
* Dropped errors earlier during collection when error collection is disabled.
Error attributes will no longer show up on spans when error collection has been disabled. Other unnecessary work will also be avoided.
* Removed allocation of logging-only objects used by transaction naming when those log levels are disabled.
* Upgraded escodegen from 1.12.0 to 1.14.1.
* Upgraded readable-stream from 3.4.0 to 3.6.0.
* Upgraded @grpc/proto-loader from 0.5.3 to 0.5.4. …
> Release v6.9.0.

- lib/grpc/connection.js
- lib/spans/streaming-span-event-aggregator.js
- test/integration/grpc/reconnect.tap.js
- test/integration/infinite-tracing-connection.tap.js
- test/unit/grpc/connection.test.js
* Infinite tracing gRPC connection will now immediately reconnect on 200 OK status.
A reconnect delay will only be used when receiving an error status that is not `UNIMPLEMENTED` (which is a permanent disconnect).
Since we only need to delay on error statuses, we didn't really need the state tracking for reconnect delay and multiple types of disconnect. Much of the red is ripping that out in favor of a simple delay configuration.
`connectSpans()` does not force an async boundary now, so there's a slightly different ordering of the `emit` that impacts tests.
> Immediately reconnects to infinite tracing endpoint on 200 OK status.

- api.js
- lib/prioritized-attributes.js
- lib/spans/span-context.js
- lib/spans/span-event.js
- lib/spans/streaming-span-event.js
- lib/transaction/trace/segment.js
- test/benchmark/attributes/priority-add-max.js
- test/integration/api/custom-attribute-span-propogation.tap.js
- test/unit/attributes.test.js
- test/unit/high-security.test.js
- test/unit/prioritized-attributes.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
* Custom transaction attributes added via `API.addCustomAttribute` or `API.addCustomAttributes` will now be propagated to the currently active span, if available.
**Security Recommendation:** Review your Transaction Event attributes configuration. Any attribute include or exclude setting specific to Transaction Events should be applied to your Span Attributes configuration or global attributes configuration. Please see [Node.js agent attributes](https://docs.newrelic.com/docs/agents/nodejs-agent/attributes/nodejs-agent-attributes#configure-attributes) for more on how to configure.
* Added a priority attribute system. Much of the built-in attribute stuff isn't *really* required for where this is used but leaves open in case we want this to apply to other or prior usages of attributes. Kept …
> Custom transaction atts to span

- test/versioned/redis/redis.tap.js
* Modified redis callback-less versioned test to use `commandQueueLength` as indicator redis command has completed and test can continue. This is in effort to further reduce these test flickers. Additionally, added wait for client 'ready' before moving on to tests.
> Further redis test flicker reduction

- lib/instrumentation/core/http-outbound.js
- lib/transaction/index.js
- test/unit/error_events.test.js
- test/unit/instrumentation/http/outbound.test.js
Migrated the following attributes to Spans only
http.statusCode
http.statusText
error.message
error.class
error.expected
We should not be sending attributes intended for spans, and not segments, on segments.  This work is to make sure no attributes added to a segment intended for spans were properly scoped to the attribute filter SPAN_EVENT scope.
> Segment attributes intended for Spans should be explicitly added to Spans

- NEWS.md
- THIRD_PARTY_NOTICES.md
* Additional Transaction Information applied to Span Events
* When Distributed Tracing and/or Infinite Tracing are enabled, the Agent will now incorporate additional information from the Transaction Event on to the currently available Span Event of the transaction.
* The following items are affected:
* `aws-lambda` related attributes
* `error.message`
* `error.class`
* `error.expected`
* `http.statusCode`
* `http.statusText`
* `message.*`
* `parent.type`
* `parent.app`
* `parent.account`
* `parent.transportType`
* `parent.transportDuration`
* Request Parameters `request.parameters.*`
* `request.header.*`
* `request.method`
* `request.uri`
* Custom Attributes
* Custom transaction attributes added via `API.addCustomAttribute` or `API.addCustomAttributes` will now be propagated to the …
> Release v6.10.0

- lib/environment.js
- package-lock.json
- package.json
- test/integration/instrumentation/oracle.tap.js
Closes #343
Upgraded following [async's release note](https://github.com/caolan/async/blob/master/CHANGELOG.md#v300).
It was surprisingly easy : We only had two test functions in `whilst` that had to be asynchronous.
I didn't know if we supported async/await, so I used old school callbacks. Let me know if you want me to change it to async functions.
> Issue #343: Upgrade async to 3.2.0

- lib/shimmer.js
- test/integration/shimmer/module-load-fixture-errored.js
- test/integration/shimmer/module-load.test.js
- test/unit/shimmer.test.js
* Adjusted instrumentation error handling to only make one attempt
https://support.newrelic.com/tickets/416443 - There is a 10 minute video in this ticket that shows the problem in our codebase. I highly suggest watching it.
While debugging a very confusing memory leak, I uncovered the problem was with our newrelic instrumentation. I made a change elsewhere in our codebase, which caused the instrumentation to fail halfway through, after already recording several shims. When the onRequire function fails, it never sets the flag to tell itself that the code has already been (or at least has already attempted to) wrapped. If you require that same module with failed instrumentation several times, you end up re-shimming the code over and over. This causes excessively high CPU% and memory usage, …
> On failed instrumentation, prevent multiple requires from re-wrapping shims

- lib/util/sql/obfuscate.js
- test/unit/util/obfuscate-sql.test.js
Based on discussion from https://github.com/newrelic/node-newrelic/issues/446
creating a PR to fix `RangeError: Maximum call stack size exceeded error on big queries` caused by obfuscation RegEx
Fixes obfuscation of SQL queries with large data inserts
https://github.com/newrelic/node-newrelic/issues/446
Fixes `Obfuscation causes RangeError: Maximum call stack size exceeded error on big queries`
> Fix large JSON inserts obfuscation

- lib/attributes.js
- lib/prioritized-attributes.js
- lib/transaction/trace/index.js
- test/unit/attributes.test.js
- test/unit/prioritized-attributes.test.js
- test/unit/trace.test.js
* **Security fix:** Resolves an issue where transaction traces will still capture the request URI when the Node.js agent is configured to exclude the 'request.uri' attribute. This can be problematic for certain customers in environments where sensitive information is included in the URI. See security bulletin [NR20-02](https://docs.newrelic.com/docs/security/new-relic-security/security-bulletins/security-bulletin-nr20-02).
The request URI will now be excluded from transaction traces if the 'request.uri' attribute has been set to be excluded at either the top-level 'attributes.exclude' configuration or at the 'transaction_tracer.attributes.exclude' configuration. 
This impacts all versions of the agent that I am aware of.
It will now set the URI to `null` when the attribute has been …
> Fixes transaction trace request uri handling.

- lib/collector/serverless.js
The addition of writing to a named pipe included a check for the pipe from the serverless collector's constructor. In practice, this is susceptible to a race condition, so there would be times when the pipe's been created after the constructor exits. Given that the agent currently writes one payload (and any future additional payloads are likely to be limited in number), this solves the problem of the race condition with minimal effect on performance. 
Tagging @michaelgoin for visibility.
> fix: Check for named pipe before each payload write

- lib/collector/serverless.js
There may be some situations in which a named pipe's presence (or absence) changes during an invocation; checking for that before flushing output would guarantee that the payload is written to the correct output. (Submitted in advance of a discussion on best approach.)
> fix: Check for named pipe before each flush

- lib/errors/error-collector.js
- lib/errors/index.js
- lib/spans/span-context.js
- lib/spans/span-event.js
- lib/spans/streaming-span-event.js
- lib/transaction/index.js
- test/integration/distributed-tracing/span-error-attributes.tap.js
- test/unit/error_events.test.js
- test/unit/errors/ignore.test.js
* Fixed bug where errors would still be collected for transactions with ignored error status codes in certain situations.
* Converted errors ignore unit tests to tap API.
* Fixes: https://github.com/newrelic/node-newrelic/issues/500
Errors should now be properly ignored regardless of when we notice the status code for the transaction.
In order to avoid capturing error attributes on span events for errors that should be ignored due to the later noticed status code, span error attributes are now created when the span is created. Error details for these attributes are added to the span context at error-time (last wins) and then used when creating a span from the segment.
The error code really could use some TLC to further simplify and de-duplicate. It has many moving pieces. Span events …
> Fix ignored status codes

- lib/instrumentation/core/http.js
- lib/serverless/aws-lambda.js
- test/integration/transaction/errors.tap.js
- test/lib/fixtures.js
- test/unit/serverless/aws-lambda.test.js
* Removed deprecated httpResponseCode, response.status and httpResponseMessage http response attributes.
Closes: #508
> Remove deprecated http response attributes

- lib/instrumentation/core/http.js
* **BREAKING** strictly uses `global.URL` class in http core instrumentation
* **BREAKING** removes Nodejs 8.x.x - 9.x.x checks
Closes: #511
> Remove node <=9.x.x version checks on http instrumentation

- test/unit/instrumentation/http/outbound.test.js
* Removed node v10 check from http outbound unit test.
Closes: #513
> Remove node v10 check from http outbound test.

- lib/config/default.js
- lib/config/env.js
- lib/config/index.js
* **BREAKING** Removed the `api.custom_parameters_enabled configuration` item and associated environment variable `NEW_RELIC_API_CUSTOM_PARAMETERS`. Please use `api.custom_attributes_enabled` instead.
Closes: #518
> Remove api.custom_parameters_enabled config item

- lib/config/index.js
* Removed deprecation warning for invalid config items, `ignored_params` and `capture_params`.  Use `attributes.exclude` and `attributes.enabled` instead.
Closes: #509
> Removed deprecation warnings invalid config items

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
* **BREAKING** Update New Relic Dependencies dropping support for Node v8 and adding support for Node v14
* `@newrelic/aws-sdk` v3.0.0
* `@newrelic/koa` v5.0.0
* `@newrelic/native-metrics` v6.0.0
* `@newrelic/superagent` v4.0.0
* `@newrelic/test-utilities` v5.0.0
Closes: #515
> Update New Relic dependencies

- examples/api/distributed-tracing/example1-background.js
- lib/transaction/dt-payload.js
- lib/transaction/handle.js
- lib/transaction/index.js
- test/unit/analytics_events.test.js
- test/unit/api/api-transaction-handle.test.js
- test/unit/db/trace.test.js
- test/unit/distributed_tracing/dt-cats.test.js
- test/unit/error_events.test.js
- test/unit/errors/error-collector.test.js
- test/unit/metrics-recorder/distributed-trace.test.js
- test/unit/metrics-recorder/http.test.js
- test/unit/trace.test.js
- test/unit/transaction.test.js
* **BREAKING** Removed deprecated Distributed Tracing API methods
#510 
`createDistributedTracePayload()` and `acceptDistributedTracePayload()` were on the `TransactionHandle` class and intended to be used by end users. Methods by the same name were also on the `Transaction` class itself, and called by both the methods on the `TransactionHandle` class and by the `insertDistributedTraceHeaders()` and `acceptDistributedTraceHeaders()` on the `Transaction` class. These "headers" methods can accept W3C Trace Context headers and New Relic DT headers.
The "payload" methods were deprecated and are now removed from the API/`TransactionHandle`. End users should use the "headers" methods.
When processing New Relic DT headers, the "headers" methods use the the "payload" methods internally. This PR …
> Remove dt methods

- NEWS.md
- third_party_manifest.json
* Added official parity support for Node 14
* Dropped Node v8.x support. For further information on our support policy,
see: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.
* Removed Node v8.x from CI
* Adds check that minimum Node version is >=10 and warns if >=15
* Sets Node engine to >=10
* **BREAKING** Dropped support for Node v8.x HTTP get() function signature
* strictly uses global.URL class in http core instrumentation
* removes Nodejs 8.x - 9.x checks
* Update New Relic Dependencies to versions with updated Node version support
* @newrelic/aws-sdk v3.0.0
* @newrelic/koa v5.0.0
* @newrelic/native-metrics v6.0.0
* @newrelic/superagent v4.0.0
* @newrelic/test-utilities v5.0.0
* **BREAKING** Removed deprecated …
> Release v7.0.0

- lib/spans/span-streamer.js
- test/unit/spans/span-streamer.test.js
* Fixed a bug where spans sent to infinite tracing from an internal queue were not properly formatted.
* Closes: #534
> Format spans drained from queue

- NEWS.md
* Fixed a bug where spans queued up during backpressure situations would be improperly formatted and ultimately dropped when sent to an Infinite Tracing trace observer.
* Updated @grpc/grpc-js to version v1.2.0.
* Updated tap to clear up npm audit issues around lodash sub-dependency.
https://github.com/newrelic/node-newrelic/pull/551
https://github.com/newrelic/node-newrelic/pull/550
https://github.com/newrelic/node-newrelic/pull/548
https://github.com/newrelic/node-newrelic/pull/545
https://github.com/newrelic/node-newrelic/pull/542
> Release v7.0.1

- lib/serverless/aws-lambda.js
- test/unit/serverless/aws-lambda.test.js
* Fixes a bug where the `http.statusCode` attribute was not being captured for an async invoked lambda.
* Closes: #554
> Capture http.statusCode on web response of async invoked lambda

- lib/spans/streaming-span-event-aggregator.js
- test/unit/db/query-sample.test.js
* Fixed empty log message
`warnOnce()` needs a key as the first argument, and the logging message as the second argument
> Fix empty log message

- lib/db/slow-query.js
- test/unit/db/query-trace-aggregator.test.js
- test/unit/parsed-statement.test.js
* Modified SQL trace ID generation to fit in a signed long
#567 
I converted the test file for query traces to tap (first commit). Then I updated the tests to have a query that would generate an ID that is ```> 2^63 - 1``` and added a test that would fail for this larger ID (second commit). Then the fix is simply taking 15 hex characters instead of 16 (third commit). I believe we're limiting IDs to 2^60, but still plenty of ID space I think.
> Use 15 char hex to guarantee signed long fit

- test/integration/core/dns.tap.js
* Fixes resolveMx test by using example.com for a valid exchange.
Updated the test to point to example.com which returns an exchange. The test previously pointed at a personal domain which expired.
> Fixes resolveMx test by using example.com for a valid exchange.

- package-lock.json
- package.json
* Bumped grpc-js version to ^1.2.4. 
Now allows minor and patch auto-updates.
* Closes: https://github.com/newrelic/node-newrelic/issues/583
We've yet to encounter any fundamental issues with grpc-js updates past the 1.x version. Seems time to loosen that restriction and reduce some toil. We can revisit if an issue occurs.
> Bumped grpc-js version to ^1.2.4

- bin/generate-release-notes.js
- bin/github.js
- package-lock.json
- package.json
Added golden-path release note generation script intended for manual run.
Grabs PR's merged since the last release in GitHub and then inserts new release notes into News.md.
Last release date determined from the date of the commit associated with the tag of the release, instead of date release was 'published' to avoid missing changes that may happen mid-process.
Long-term, will probably add ability to manually set a release or tag to handle non-standard cases such as having most recently published an emergency backport.
To run: `node ./bin/generate-release-notes.js`
As this evolves and potentially is made more generic, more of the hard-coded details should be parameterized.
> Adds golden-path release note generation script.

- bin/update-changelog-version.js
- package.json
When npm version is ran, the package.json version gets updated and then executes our 'version' script in package.json.
Example when running `npm version patch` w/ some release notes:
```
Updating vNext header to:  ### v7.1.1 (2021-01-26)
*** [SUCCESS] ***
```
> Adds script to auto-update NEWS.md version header from vNext.

- .github/workflows/publish-release-tag.yml
* Added workflow for publishing to npm when a v* tag is pushed to the repo.
Auto-publishes when a new tag is pushed in the form v*. 
Can also trigger manually via workflow dispatch but there's one big limitation. Via the UI, only branches are available as ref. So if we ever need to manually publish we'll need to do from a branch. Could do main if clean/same version but may want ot create a branch from the tag being released and then publish that... if comes up. Hopefully longer-term GitHub will expand this (I think they may have already via the workflow dispatch API).
Could potentially modify the checkout action to take a param for ref to enable setting to a tag or such.
> Adds workflow for publishing to npm when a v* tag is pushed to the repo.

- package-lock.json
- package.json
* Upgrade @grpc/grpc-js to v1.2.5 to fix non-propagation of internal http2 errors
Closes: #605 
gprc-js fix PR: https://github.com/grpc/grpc-node/pull/1658
> bump grpc-js version to v1.2.5

- NEWS.md
- package-lock.json
- package.json
Revert changes from failed `npm run version` run under Node version 15
> revert from failed npm version run on node v15

- lib/agent.js
- lib/spans/streaming-span-event-aggregator.js
* Removed initial harvest send() call on streaming span event aggregator to prevent warning in logs.
Longer-term, would be nice if the code was restructured so we didn't need to check for streaming VS non streaming but going with the minimal effort for now.
> Stops calling send() on streaming span aggregator on initial harvest.

- lib/grpc/connection.js
- test/integration/grpc/reconnect.tap.js
* Fixed bug where the agent failed to reconnect to Infinite Tracing grpc streams on Status OK at higher log levels.
Node streams require all data be consumed for the end/status events to fire. We were only reading data at lower log levels where we'd use/log the data. This resulted in a failure to reconnect and 'ERR_STREAM_WRITE_AFTER_END' errors. The agent now always listens to the 'data' event, even if not logging, and will also reconnect (with 15 second delay) on any 'ERR_STREAM_WRITE_AFTER_END' error.
* Fixes: https://github.com/newrelic/node-newrelic/issues/620
* https://nodejs.org/api/stream.html#stream_event_end
> Fixes infinite tracing reconnect handling

- NEWS.md
- THIRD_PARTY_NOTICES.md
- third_party_manifest.json
* Fixed bug where the agent failed to reconnect to Infinite Tracing gRPC streams on Status OK at higher log levels.
Node streams require all data be consumed for the end/status events to fire. We were only reading data at lower log levels where we'd use/log the data. This resulted in a failure to reconnect and 'ERR_STREAM_WRITE_AFTER_END' errors. The agent now always listens to the 'data' event, even if not logging, and will also reconnect (with 15 second delay) on any 'ERR_STREAM_WRITE_AFTER_END' error.
* Removed initial harvest send() call on streaming span event aggregator to prevent warning in logs.
* Bumped @newrelic/aws-sdk to ^3.1.0.
* PR: https://github.com/newrelic/node-newrelic/pull/621
* PR: https://github.com/newrelic/node-newrelic/pull/622
* PR: …
> Prepare release

- index.js
- lib/config/index.js
* Improved clarity of logging between 'no log file' or disabled agent startup issues.
* Logs no-config file error to initialized logger (stdout) in addition to existing console.error() logging. 
* Adds specific message to no config file separate from being disabled.
* Fixes: https://github.com/newrelic/node-newrelic/issues/612
We did have existing logging around what went wrong when no config file but it is likely in some/many cases New Relic logs were particularly parsed out of an applications stdout logging and thus the message would not be seen. As such, also logged to our logger stream.
Due to the config being loaded by logger and agent loading process, what was being logged twice just to console will now be logged twice to console and logged twice to the logger stream. While ideally …
> Improves clarity of what went wrong with no log file or disabled agent.

- lib/transaction/index.js
- test/lib/cross_agent_tests/distributed_tracing/distributed_tracing.json
- test/unit/transaction.test.js
* Fixed issue where a call to `transaction.acceptDistributedTraceHeaders` would throw an error when the `headers` parameter is a string.
Closes: #637
> Do not throw error when headers is string passed into acceptDistributedTraceHeaders

- lib/collector/api.js
- lib/collector/remote-method.js
- test/integration/collector-remote-method.tap.js
- test/integration/keep-alive.tap.js
- test/unit/collector/api-connect.test.js
- test/unit/collector/remote-method.test.js
* Fixed bug where agent would attempt to call the 'preconnect' endpoint on the redirect host returned by the previous 'preconnect' call when reconnecting to the New Relic servers.
The 'preconnect' calls will now always use the original agent configuration value. Subsequent endpoints (connect, harvest endpoints, etc.) will continue to leverage the new redirect host value returned by 'preconnect.' The original config values are no-longer overridden.
* Fixes: https://github.com/newrelic/node-newrelic/issues/462
Given this impacts our initial handshake and continued functioning, this is slightly higher risk than say instrumentation changes.
When the new redirect-host comes in, all RemoteMethod instances except 'preconnect' are now updated with the new host and port endpoint values. The …
> Do not redirect preconnect

- lib/instrumentation/core/timers.js
- test/integration/core/timers.tap.js
* Stopped binding/propagating segments via `setImmediate` for ended transactions.
* Closes: https://github.com/newrelic/node-newrelic/issues/579
Straightforward spot-fix for setImmediate. Going to set up a follow-up story to look at doing this in general for our various binding/wrapping methods. Seems if the associated transaction has ended we should be doing as little work as possible. Handling these cases obviously are a bit more edge-case but we don't control the environments we run in and we want to clean up our memory usage quickly and not do unnecessary work.
> setImmediate no longer binds/propagates segments for an ended transaction

- lib/config/index.js
- test/unit/config/config.test.js
* Removed requirement to configure application name when running in AWS Lambda (serverless mode).
Application name is not currently leveraged by New Relic for Lambda invocations. The agent now defaults the application name in serverless mode to remove the requirement of end-user configuration while handling cases if it were to be leveraged in the future. 
* Closes: https://github.com/newrelic/node-newrelic/issues/477
> Defaults the application name when running in serverless mode.

- .github/workflows/publish-release-tag.yml
- bin/create-github-release.js
- bin/github.js
* Closes: https://github.com/newrelic/node-newrelic/issues/587
* Adds script which will take a tag and then automatically create a release in GitHub.
* Body of release is pulled from the release notes matching the tag.
* Adds execution of script to publish workflow which executes after npm publish.
Unfortunately, since workflow_dispatch doesn't allow setting a tag instead of a branch... that workflow will fail on manual execution for the create release. We could consider eventually adding a tag input on workflow dispatch and then executing against that for code checkout and release creation but not tackling yet.
> Automate GitHub release creation

- lib/spans/span-event.js
- lib/spans/streaming-span-event.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
* Fixed bug where truncated http (external) or datastore segments would generate generic spans instead of appropriate http or datastore spans.
* fixes: https://github.com/newrelic/node-newrelic/issues/439
Don't know for sure if datastore operations are impacted (harder to repro) but seemed possible so have a somewhat manufactured test case.
A digression: these tests aren't really unit tests and should be moved to integration tests at some point.
I think a more ideal way to handle this would be for a segment's span context to have the category set when we determine a segment is an external or a datastore. That being said, the datastore instrumentation didn't really lend itself to this in a straightforward manner. So still looking at segment names which is a bit brittle.
On the plus side, …
> Fixes bug where truncated segments/spans would not have appropriate category

- lib/collector/http-agents.js
- lib/collector/remote-method.js
- lib/feature_flags.js
- test/integration/collector-remote-method.tap.js
- test/integration/keep-alive.tap.js
- test/unit/feature_flag.test.js
* Added feature flag to allow disabling of certificate bundle usage.
**Deprecation Warning:** The certificate bundle included by New Relic will be disabled by default and then fully removed in later major versions. We recommend testing with the certificate_bundle feature flag set to `false` to determine if you will need to modify your environment or setup your own appropriate bundle. Example configuration: `feature_flag: { certificate_bundle: false }`
* Closes: https://github.com/newrelic/node-newrelic/issues/664
> Add certificate_bundle feature flag to enable deprecation and removal efforts

- test/unit/collector/remote-method.test.js
- test/unit/collector/serverless.test.js
* Converted remaining collector unit tests to use tap API.
One of the tests (flushPayloadSync) wasn't actually hitting several assertions and was modified for the current data format.
flushPayload had to be modified to use a spy as you'll get a tap failure when stdout writing is suppressed.
Fixed errant async code setup with the pipe tests.
Likely other small fixes I don't remember at this point but everything else shoudl be mostly 1:1 conversion.
Pure tap API usage will naturally have more 'asserts'.
New Results:
```
Suites:   1 passed, 1 of 1 completed
Asserts:  66 passed, of 66
Time:     1s
```
---
Previous:
```
Suites:   1 passed, 1 of 1 completed
Asserts:  55 passed, of 55
Time:     2s
```
New results:
```
Suites:   1 passed, 1 of 1 completed
Asserts:  49 passed, of 49
Time:     2s …
```
> Finish converting collector tests to tap API

- lib/config/index.js
- test/integration/logger.tap.js
- test/unit/config/config.test.js
* The `NEW_RELIC_NO_CONFIG_FILE` environment variable is no longer needed to run the agent without a configuration file.
* If a configuration file is used with agent configuration environment variables, the environment variables will override the corresponding configuration file settings.
Closes: #627 
There are a few environment variables that do not have a corresponding configuration file setting, but those are set by the environment they run in (ie AWS Lambda).
> The NEW_RELIC_NO_CONFIG_FILE env var is now not needed to run the agent without config file

- .github/workflows/prepare-release.yml
Missed updating the workflow in the prepare-script update. Updates wording to not flag major as unsupported (but still somewhat show not standard i.e. for breaking changes.)
> Change prepare workflow working to allow major releases.

- lib/instrumentation/core/http.js
- lib/transaction/index.js
- test/unit/transaction.test.js
* Fixed issue where capturing axios request errors could result in a memory leak.
The agent now clears error references on transaction end, which are not used for later processing. Errors returned from 'axios' requests contain a reference to the request object which deeper down has a handle to a promise in `handleRequestError`. The TraceSegment associated with that promise has a handle to the transaction, which through the error capture ultimately kept the promise in memory and prevented it from being destroyed to free-up the TraceSegment from the segment map. This change also has the benefit of  freeing up some memory early for transactions held onto for transaction traces.
* Added active transaction check to `wrappedResEnd` to prevent unecessary work for ended transactions in the case …
> Clears error collections on transaction end after processing.

- lib/instrumentation/core/async_hooks.js
- test/integration/core/async_hooks.js
* Agent no longer propagates segments for promises via async-hooks when the transaction associated with the parentSegment has ended.
This change reduces the amount of context tracking work needed for certain rare edge-case scenarios involving promises.
Also moved type check up earlier for faster short-circuiting (as well as just checking agent.getTransaction() in the if statement). These are unlikely to have a noticeable impact but given the frequency of execution of the hooks and added check, seemed good to go ahead and do.
> Adds active transaction check for parentSegment to promise tracking

- package-lock.json
* Dev-only sub-dependency bump of 'y18n' to clear npm audit warnings.
> Bumps dev sup-dep to get rid of npm audit warning.

- lib/grpc/connection.js
- lib/spans/create-span-event-aggregator.js
- test/integration/grpc/reconnect.tap.js
- test/integration/infinite-tracing-connection.tap.js
- test/unit/grpc/connection.test.js
- test/unit/spans/create-span-event-aggregator.test.js
- test/unit/trace.test.js
* Fixed memory leak introduced when Infinite Tracing is enabled.
When Infinite Tracing endpoints reconnected they would instantiate a new gRPC client prior to calling `client.recordSpan()`. It appears several objects created by grpc-js (`ChannelImplementation` and child objects, promises, etc.) are held in memory indefinitely due to scheduled timers even when the client is no-longer referenced and the associated stream closed. We now avoid this situation by only creating the client once and then reusing it to establish new stream connections. 
* Fixes: https://github.com/newrelic/node-newrelic/issues/725
I could think of any meaningful tests that would catch/prevent reintroducing the issue in a meaningful way. So relying on code comments for now.
Fixed a couple tests that when they would …
> Fixes infinite tracing reconnect memory leak

- lib/feature_flags.js
- lib/instrumentation/core/async_hooks.js
- test/integration/core/async_hooks-new-promise.js
- test/integration/core/async_hooks-new-promise.tap.js
- test/unit/feature_flag.test.js
* Added new feature-flag 'new_promise_tracking' which enables cleaning up of segment references on native promise resolve instead of destroy. Includes usage of async-await. This can be enabled via `feature_flag: { new_promise_tracking: true }` in the config file or `NEW_RELIC_FEATURE_FLAG_NEW_PROMISE_TRACKING=1` in your ENV vars.
Applications with heavy promise usage or high-throughput applications with some promise usage should see moderate to high reduction in memory usage and may see a slight reduction in CPU usage. A bump in throughput may also be noticed in some cases. Results will vary by application.
If you are experiencing high overhead levels with your promise usage and the agent attached, we recommend testing your application with  'new_promise_tracking' set to true to see if …
> feature-flag: clean up segment references on promise resolve

- lib/instrumentation/core/async_hooks.js
- package-lock.json
- package.json
- test/integration/fastify/errors.tap.js
- test/integration/fastify/naming.tap.js
- test/integration/fastify/new-state-tracking.tap.js
- test/versioned/fastify/integration.tap.js
* Fixed issue with 'new_promise_tracking' feature flag functionality where segments for ended transactions would get propagated in certain cases by promises that had no continuations scheduled (via await or manually).
* Likely same problem as: https://github.com/newrelic/node-newrelic/issues/729
~While the code to reproduce this locally is pretty straightforward, I cannot get a test to reproduce this. I'm wondering if the underlying test framework implementation is having an impact. I'll continue to poke at it but I figured it was better get something out there to resolve than hold-off given this is being a feature-flag anyways. I'm hoping this resolves the one issue we've seen (linked above) but it may not as haven't seen all the details there yet.~
Was able to get tests going by using …
> Only propagates null segments on resolve to prevent reuse of transaction

- bin/prepare-release.js
In some cases, appears the commit date can be earlier than the same PR's merge date which resulted in the PR coming back for the 'merged after' query. This filters that out.
> Filters out PR that created release tag commit on merge.

- test/versioned/redis/redis.tap.js
* Bumped timeout for redis versioned tests.
Looks like a few failures I could track down were hitting the 10K timeout while only having attempted the polling retry once. As such bumping the timeout. I doubled to just be done with it. If it still fails at this timeout, will try a different approach altogether.
I added some additional commenting for when the hset is actually executed to confirm nothing unexpected is happening.
> Bumps redis versioned test timeout to 20s.

- test/versioned/hapi/hapi-17/package.json
* Properly pinned hapi 17 versioned tests to only minor/patch versions within 17.x
This was discovered when running the versioned tests with npm 7.  It installs peer deps by default and vision@5.1.0 required hapi@17.x
> pinned hapi17 tests to the 17 semver range

- test/lib/agent_helper.js
- test/versioned/ioredis/ioredis-3.tap.js
- test/versioned/ioredis/ioredis.tap.js
- test/versioned/redis/redis.tap.js
* Updated redis versioned tests to use unique DB indexes per file to avoid collisions and flushing of in-progress tests.
All of the redis tests use the same DB index and regularly the same keys. At the start of each test file, the redis DB index is cleared for the test, instead of say cleaning up after each key operation. While currently (just for versioned tests) this would be fine as I believe we run the individual files in series for a single suite, the causes issues when ioredis and redis tests are both running because they run in parallel. We'd also have issues if these were integration tests all all files run in parallel.
I discovered this while debugging the current flicker by accidentally making things worse. Turns out one of the ioredis test files was clearing the DB mid-test for …
> Uses unique DB index for redis tests to avoid conflicts

- lib/instrumentation/core/async_hooks.js
- test/integration/core/async_hooks-new-promise.js
* Fixed issue when using the 'new_promise_tracking' feature flag where segment mapping may not get cleaned up for promises which never resolve but have all references removed (and thus get cleaned up by GC).
Adds segment cleanup on 'destroy' when using 'new_promise_tracking' feature flag in addition to the existing 'promiseResolve' hook. Unfortunately, preventing leaks for this edge-case does come with a small amount of additional overhead due to adding another hook. Memory gains from feature flag usage should still be worth the trade-off and reduced garbage collection may offset perf/CPU impacts or event still result in net gain, depending on the application.
* Fixes: https://github.com/newrelic/node-newrelic/issues/745
I'm guessing we can't get away with getting rid of the before/after …
> Adds destroy hook segment removal to handle non-resolved promise cleanup.

- lib/config/index.js
- test/unit/config/config.test.js
- default support for config files named `newrelic.js` and `newrelic.cjs`. Config file name can also be specified with the NEW_RELIC_CONFIG_FILENAME environment variable.
Fixes: https://github.com/newrelic/node-newrelic/issues/344
We need to have the newrelic config file end with `.cjs` since our package using newrelic is of type module. This will also give users the ability to specify an arbitrary config file name instead of being limited to only `newrelic.js`
> Support .js .cjs and custom config filename

- package.json
* Properly bootstrap husky as a `prepare` script
husky changed their bootstrap process in v6.  It is now recommended to add a prepare script that creates the hooks when running `husky install`.  Prepare runs after every `npm install`.
> add husky install as prepare script to properly bootstrap husky

- lib/shim/shim.js
* removes unused `listenerCount` method on `Shim`.
Closes #766 
You can see in the issue originally logged, I discovered this was unused when I noticed it was using deprecated methods on `events.EventEmitter`
> removes unused listenerCount function on shim

- lib/instrumentation/core/http-outbound.js
- lib/instrumentation/core/http.js
- lib/util/cat.js
* Replaced deprecated `util.isArray` with `Array.isArray`
closes #764 
cleanup as this method has been deprecated since v4.0.0 of Node.js
> replace util.isArray with Array.isArray

- lib/config/index.js
- test/unit/config/config.test.js
- Fix loading config from the main module's directory.
N/A
Hey 👋  - thanks for your work on this package!
Prior to v7.5.0 config files stored at the same filepath as the main module's filename would be correctly loaded, however [this commit](https://github.com/newrelic/node-newrelic/commit/3931f69cbc66629d65423b6419d69f5f7f3cdf0d) introduced a regression on the behaviour by no longer including the `path.dirname(process.mainModule.filename)` in the config file location candidates.
The effect of this is that if the New Relic config file is stored in the same directory as the main module, it may not be loaded in. My workaround for the time being will be to manually set the `NEW_RELIC_HOME` env var to my main module's directory.
This fix addresses the regression, and adds some additional test …
> Fixes loading config from the main module's directory

- lib/instrumentation/mongodb.js
- test/versioned/mongodb/cursor-duration.tap.js
- test/versioned/mongodb/package.json
* Binds cursor methods when they are promises to properly measure the duration of execution
Closes #788 
This was a simple addition of `promise: true` to the spec of all cursor methods within mongodb.  The 2 integration tests added verify that the exclusive duration of the cursor method is greater than its parent which will properly assert the fix.  See #788 comments for more info around the issues and screenshots confirming the fixes within the comments by me.
> added option to bind promises for cursor methods in mongodb

- test/versioned/mongodb/package.json
* Pinned mongodb versioned tests to <4.0.0.
Mongodb 4.0.0 was released on 7/13/2021 and is breaking one of the versioned tests. There seems to be several breaking changes in the [changelog](https://github.com/mongodb/node-mongodb-native/blob/v4.0.0/HISTORY.md) that may have to be addressed with a focused effort.
> Pin mongodb versioned tests <4

- .github/workflows/ci-workflow.yml
- .github/workflows/smoke-test-workflow.yml
* Removed Node v10 from ci workflow and smoke-test version matrix.
* Set ci workflow linting check to use Node v16.
> Remove Node v10 from ci version matrix.

- .github/workflows/ci-workflow.yml
- .github/workflows/smoke-test-workflow.yml
* Updated linting to always use latest LTS Node version.
* CI and Smoke Test scripts now use setup-node@v2.
> Linting always uses latest LTS. Bumped to setup-node@v2.

- test/versioned/hapi/hapi-post-18/errors.tap.js
- test/versioned/hapi/hapi-post-18/package.json
* Added hapi 19 and 20 to versioned tests for Node.js `>=12` and `<16`
* Added hapi `^20.1.2` to versioned tests for for Node.js `>=16`
Closes #771 
Hapi 19 and <20.1.2 crashes on Node.js 16 because of https://github.com/hapijs/hapi/issues/4208.  They fixed this and shipped a release in 20.1.2: https://github.com/hapijs/hapi/pull/4225#issuecomment-828841511.
> Add hapi 19 20

- package.json
* Fixed the `homepage` field in package.json to use `https` in the link to the github repo
I think this will fix the `URL` field display when downstream services, such as `yarn outdated` consume this, newrelic was the odd one out of a sample in a project I was looking at:
> Change to https protocol in homepage of package.json

- lib/agent.js
- lib/collector/api.js
- test/integration/api/shutdown.tap.js
- test/integration/newrelic-response-handling.tap.js
- test/unit/agent/agent.test.js
* Fixed bug where `API.shutdown` would not harvest or keep process active effectively after an agent restart.
The agent will now correctly update its state to 'started' after a reconnect has completed.
* Fixes: https://github.com/newrelic/node-newrelic/issues/789
Did a minor refactor to consolidate the agent's handling of connection to try to avoid similar issues in the future.
Flagging as 'medium' risk because this is a code path that can impact all data. I have manually tested on a few flavors of application as well as added additional test coverage but worth extra care in review.
> Set agent to 'started' upon completing reconnect to New Relic servers

- lib/instrumentation/pg.js
- test/unit/instrumentation/postgresql.test.js
- test/versioned/pg/pg-post-7/pg.common.js
* Fixed issue where Promise based `pg.Client.query` timings were always in sub-millisecond range.
* Closes: #786 
For this work, I had to support instrumentation/recordQuery timings for Callback, Promise and 'Submittable' style pg.Client.query function calls. Submittable style calls are documented at the bottom of this [pg document](https://node-postgres.com/guides/upgrading).  The different styles are outlined below:
Callback:
`client.query('select * from stuff', function cb (err, data) {})`
Promise:
`const data = await client.query('select * from stuff')`
Submittable:
```
const query = client.query(new Query('select * from stuff'))
query.on('row', () => {})
query.on('end', () => {})
```
When the pg library was updated to version 7.0, they dropped support for the event based row output …
> Fix postgres pg module Promise based query timings

- test/versioned/mongodb/collection-common.js
* Refactored `dropTestCollections` in mongo versioned tests to await for all `dropCollection` operations to be finished before closing connection and returning.
We've had intermittent failures in CI around mongo tests. Most are around collections already existing, I think this is the culprit
> refactor dropTestCollections in mongo versioned tests

- lib/instrumentation/connect.js
- test/versioned/connect/error-intercept.tap.js
- test/versioned/connect/package.json
- test/versioned/connect/route.tap.js
* Support using `connect` to route middleware calls.
Closes #846 
I added router tests which we lacked before which would've shown this never worked.  In the issue I logged, our docs state we don't support the router but honestly I have no idea why.  This fix is trivial.
> fixed connect to properly set transaction name with url of route

- lib/feature_flags.js
- lib/instrumentation/core/async_hooks.js
- test/integration/core/async_hooks-new-promise-unresolved.tap.js
- test/integration/core/async_hooks-new-promise.js
- test/unit/feature_flag.test.js
* Added a new feature flag `unresolved_promise_cleanup` that defaults to true only when `new_promise_tracking` feature flag is set to `true`.  If disabled, this will help with performance of agent when an application has a lot of promises.  To disable set in your config `feature_flag.unresolved_promise_cleanup` to `false` or pass in the env var of `NEW_RELIC_FEATURE_FLAG_UNRESOLVED_PROMISE_CLEANUP=false` when starting application with agent. 
**WARNING**: If you set `unresolved_promise_cleanup` to `false`, failure to resolve all promises in your application will result in memory leaks even if those promises are garbage collected
Closes #848 
Due to the tap test structure the title of the test cannot be changed https://github.com/newrelic/node-newrelic/pull/849/files#diff-1c796fb285ebfee00b …
> added new feature flag to remove the promise destroy hook

- lib/config/index.js
- lib/spans/span-event-aggregator.js
- test/unit/config/config-server-side.test.js
- test/unit/spans/span-event-aggregator.test.js
* Handled setting the `span_event_harvest_config` from server and using in `SpanEventAggregator` to enforce the queue size and harvest cycle duration.
Closes #851 
The `span_event_harvest_config` is currently behind a feature flag but this code is built to work without that getting passed in by using defaults.  Also this overlaps code the @michaelgoin has done for #852 so there will definitely be conflicts
> Connect harvest limit

- test/unit/priority-queue.test.js
- Transitioned priority-queue.test.js to use tap rather than Mocha globals.
> transition priority-queue.test.js from mocha to tap

- test/unit/parse-sql.test.js
- Transitioned parse-sql.test.js to use tap over Mocha globals.
> transition parse-sql.test.js to use tap over mocha globals

- test/integration/instrumentation/http.tap.js
- test/versioned/express/render.tap.js
* Changed assertions for 2 http error msg tests to work with all versions of Node.js
In Node.js v16.9.0 2 tests broke because the error message in a http response changed from:
```
"Cannot read property '<prop name>' of undefined",
```
to
```
"Cannot read properties of undefined (reading '<prop name>')"
```
This appears to have been a v8 changed that was address in Node.js core here https://github.com/nodejs/node/commit/f43c292520c
> fixed tests that broke when running on Node.js v16.9.0

- test/lib/agent_helper.js
- test/unit/shim/conglomerate-shim.test.js
- test/unit/shim/datastore-shim.test.js
- test/unit/shim/message-shim.test.js
- test/unit/shim/promise-shim.js
- test/unit/shim/promise-shim.test.js
tests to use tap
* Migrated `conglomerate-shim`, `datastore-shim`, `message-shim`, and `promise-shim` to use tap
Big thanks to @michaelgoin for digging into the promise-shim issue when migrating to tap.
> ported conglomerate-shim, datastore-shim, message-shim, and promise-shim

- test/unit/high-security.test.js
- Transitioned high-security.test.js to use tap instead of mocha syntax.
> convert high-security.test.js to use tap syntax

- lib/config/default.js
- test/unit/config/config-defaults.test.js
- Changed default for `span_events.max_samples_stored` from 1000 to 2000.
- Closes https://github.com/newrelic/node-newrelic/issues/883
> change span_events.max_samples_stored default 1000 -> 2000

- test/unit/db/query-parsers/sql.test.js
* Migrated sql query parser tests to tap
I did this because I noticed we had 15 skipped tests in this file. I thought for some reason it was because of the tests using `chai.should`.  However, it was because we have functionality not built into our parser, should we create a ticket to address this?  The two use cases:
* should strip database from table when you do `select * from db.table`(I'm just basing this off the comment in the parser code the spec doesn't call this out here https://source.datanerd.us/agents/agent-specs/blob/master/APIs/datastore_segment.md#reporting-as-datastore
* parsing nested sql does not work properly: `select * from (select * from table) where x > y` displays the collection as `select`. I don't see any mention in spec on how it should handle nested sql
> ported query-parsers/sql to tap

- lib/instrumentation/core/http-outbound.js
- lib/instrumentation/core/http.js
- lib/shim/transaction-shim.js
- lib/util/cat.js
- test/unit/agent/intrinsics.test.js
- test/unit/header-attributes.test.js
- test/unit/shim/transaction-shim.test.js
* Refactored `transaction-shim`, `http` and `http-outbound` to use centralized CAT methods in `util/cat`
Closes #913 
There is still code in transaction-shim and http-outbound that could be abstracted but I didn't want to go too far.  This code will also help seed an upcoming undici PR that you can see copied some of the code here #901.
> Centralized CAT logic into util/cat

- lib/instrumentation/cassandra-driver.js
- package-lock.json
- test/versioned/cassandra-driver/package.json
- test/versioned/cassandra-driver/query.tap.js
- Support Cassandra driver v4.0.0 and above.
- Closes https://github.com/newrelic/node-newrelic/issues/909
This PR adds support for Cassandra v4. In v4.4.0, the private method `_innerExecute` was replaced with `_execute`. Because our tests were pinned to test only *up to but not including* v4, we only detected this failure once it was [reported to us](https://github.com/newrelic/node-newrelic/issues/564). This PR creates query hooks on `_execute` if `_innerExecute` does not exist. As well, the test suite has been updated
> support cassandra-driver >4

- test/unit/serverless/aws-lambda.test.js
- Transitioned aws-lambda.test.js to use Tap over Mocha.
This is a big one. There seems to be a duplicate test suite, with this leading comment:
> // TODO: A duplicate of above while in hybrid mocha DSL state. Cleanup when go full tap.
Being so new to the project, I'm not sure what to do with this duplicate test suite. I suppose my first guess is to simply merge them as I'm able... or perhaps, this conversion is not necessary at all, and the duplicate test suite should simply replace the original. Guidance appreciated!
> begin to transition aws-lambda.test.js to tap from mocha

- lib/instrumentation/core/timers.js
- test/integration/core/timers.tap.js
- test/lib/agent_helper.js
- test/versioned/mongodb/collection-common.js
- test/versioned/mongodb/cursor.tap.js
* Fixes issue with `clearTimeout` that could result in dropping parent segments or spans.
This bug resulted in some MongoDB calls being dropped from Transaction Traces and Distributed Traces (spans): https://github.com/newrelic/node-newrelic/issues/922.
* Fixes: https://github.com/newrelic/node-newrelic/issues/922
I looked at the pre-shim code and it had the same issue. I think ideally we could avoid doing work when the parent is opaque for the timers but we currently have to based on the existing context propagation mechanisms. If we successfully switch to newer context mechanisms, perhaps we can have a more obvious means of detecting we are not in this context. We could potentially use another mechanism for identifying it is in fact a timer span.
For now, I went with matching against …
> Fix opaque timer issue

- lib/feature_flags.js
- lib/instrumentation/core/http-outbound.js
- lib/instrumentation/undici.js
- lib/instrumentations.js
- test/unit/feature_flag.test.js
- test/unit/instrumentation/undici.test.js
* Added instrumentation for the [undici](https://github.com/nodejs/undici) http client.  The instrumentation is behind a feature flag.  To enable, add the following into your config `{ feature_flag: { undici_instrumentation: true } }`.  The support for undici client is Node.js 16.x as it takes advantage of the [diagnostics_channel](https://nodejs.org/dist/latest-v16.x/docs/api/diagnostics_channel.html).  Lastly, you must be using [v4.7.0+](https://github.com/nodejs/undici/releases/tag/v4.7.0) of the undici client for any of the instrumentation to work.
Closes #730 
You can use this repo [undici-http-app](https://github.com/bizob2828/undici-http-app) and follow the README to get it up and running.  As you can see the spans for httpbin.org are identical and the traces are properly nested. …
> Undici prototype

- lib/instrumentation/fastify.js
- lib/instrumentation/fastify/spec-builders.js
- test/unit/instrumentation/fastify/spec-builders.test.js
- test/versioned/fastify/fastify-2-naming.tap.js
- test/versioned/fastify/fastify-3-naming.tap.js
* Fixed the WebFramework spec definitions for Fastify middleware and route handlers to properly retrieve the IncomingMessage from a request object.  Also, added proper definition to middleware handlers so that the relationship to consecutive middleware and route handler are siblings and not direct children.
Closes #926 
There is overlap with this PR and https://github.com/newrelic/node-newrelic/pull/931/files.  The tests will need to be reconciled.  We also will be adding more test cases scenarios when this MMF is close to being done in #928
> fixed fastify spec builders, added unit tests for code as well

- lib/feature_flags.js
- lib/instrumentation/undici.js
- test/unit/feature_flag.test.js
- test/unit/instrumentation/undici.test.js
* Fixed an issue with undici instrumentation where the parent segment wasn't always correct.  
* Fixed an issue where undici instrumentation would crash if transaction got ended before undici external segment was added
* Removed instrumentation for undici connections as it did not provide any additional context from what we already have with the net module and socket connections
I added a new feature flag `undici_async_tracking` that defaults to true.  This relies on async hooks' executionAsyncId to get the proper async context for storing the current active segment before an undici request is made.  
**Note**: This poses issues if requests to an app are made with keep alive and you have multiple undici requests being made in paralell.  If this is a use case of yours, set `feature_flag: { …
> Undici fixes for parallel requests

- lib/instrumentation/fastify.js
- lib/instrumentation/fastify/spec-builders.js
- test/versioned/fastify/fastify-2-naming.tap.js
- test/versioned/fastify/fastify-3-naming.tap.js
* Added middleware mounting for fastify v3.
* Fixed capturing of mount point for middleware naming.
* Closes: https://github.com/newrelic/node-newrelic/issues/927
Note: the inclusion of the hook that fires the middleware 'onRequest' does result in awkward UI formatting with the old UI which does auto formatting.
Without it, you would see something like `Middleware: pathMountedMiddleware /async-return`. With it, you see: `Middleware: onRequest pathMountedMiddleware//async-return`.
The newer UI doesn't do any formatting currently so has no impact.
> Adds fastify v3 middleware mounting and fixes mount location naming

- .github/workflows/ci-workflow.yml
I mistakenly check `github.ref` with branch name but based on [docs](https://docs.github.com/en/actions/learn-github-actions/contexts) it needs to be `refs/head/<branch>`
> fixed github.ref check

- lib/serverless/aws-lambda.js
- test/unit/serverless/aws-lambda.test.js
* Fixed issue where unhandled promise rejections were not getting logged as errors in a lambda execution
Closes #970 
I manually built our newrelic layer with this version of node agent and re-ran my lambda that was not logging errors and it works 🎉 .  
[Permalink](https://onenr.io/0e1wZYODAQ6)
> added logic to add error when unhandledRejection occurs during lambda handler

- lib/agent.js
- lib/context-manager/create-context-manager.js
- lib/context-manager/diagnostics/legacy-diagnostic-context-manager.js
- lib/context-manager/legacy-context-manager.js
- lib/instrumentation/promise.js
- lib/shim/shim.js
- lib/shim/transaction-shim.js
- lib/transaction/tracer/index.js
- package.json
- test/unit/context-manager/create-context-manager.test.js
- test/unit/context-manager/legacy-context-manager.test.js
- test/unit/context-manager/legacy-context-tests.js
- test/unit/context-manager/legacy-diagnostic-context-manager.test.js
- third_party_manifest.json
* Introduced a context management API to be used in place of manually calling tracer.segment get/set.
* Closes: https://github.com/newrelic/node-newrelic/issues/962
* Context will always be a segment, currently, for parity support. I've kept targeted as 'context', though, as we likely will expand this in the future after migrations. There's allocation/perf considerations there though which warrant not tackling too early.
* Intend to rip out tracer.segment get/set in a follow-up PR. Need to validate no external uses. Also, will result in touching many test files so will be nice to limit the scope of review to what is critical.
* I split the diagnostics / probe functionality into a separate implementation to keep the primary path as simple/bare-bones as possible.
* There will be further …
> Introduces a context tracking API.

- lib/shim/message-shim.js
- test/unit/shim/message-shim.test.js
* Fixed issue where `recordConsume` was not binding consumer if it was a promise
Closes #977 
It looks like it cannot use the simple `shim.record` method as the spec contains different keys to handle in the consumer.  I also added a test to `recordConsume` which was failling before fix.
> added code to properly bind promises in recordConsume

- api.js
- lib/shimmer.js
- test/integration/module-loading/module-loading.tap.js
- test/lib/agent_helper.js
- test/unit/shimmer.test.js
* Added `onResolved` instrumentation hook to apply instrumentation prior to module load.
This hook fires after the module filepath has been resolved just prior to the module being loaded by the CommonJS module loader.
* Closes: https://github.com/newrelic/node-newrelic/issues/978
Flagging high-risk as if anything breaks in module loading everything breaks for a customer.
onResolved instrumentation accepts the following arguments: `(shim, moduleName, resolvedFilepath)`.
Due to both Node.js filepath caching (and our own) this instrumentation does not have special protections against multiple runs. If for some reason this changes in the future (or there is an unknown case where multiple runs could occur), I might recommend augmenting the onResolved handler itself since there's no module …
> Adds a hook prior to module load for doing early-instrumentation

- lib/transaction/tracer/index.js
- test/benchmark/shim/record.bench.js
- test/benchmark/tracer/bindFunction.bench.js
- test/benchmark/tracer/segments.bench.js
- test/benchmark/tracer/transaction.bench.js
- test/benchmark/tracer/utilities.bench.js
- test/benchmark/webframework-shim/recordMiddleware.bench.js
- test/integration/core/async_hooks-new-promise.js
- test/integration/core/async_hooks.js
- test/integration/core/net.tap.js
- test/integration/core/timers.tap.js
- test/integration/instrumentation/promises/methods.js
- test/integration/transaction/tracer.tap.js
- test/lib/agent_helper.js
- test/unit/api/api-start-background-transaction.test.js
- test/unit/api/api-start-web-transaction.test.js
- test/unit/instrumentation/core/promises.test.js
- test/unit/instrumentation/http/outbound.test.js
- test/unit/shim/shim.test.js
- test/unit/transaction.test.js
* Removed `tracer.segment` in place of direct usage of context manager.
Patch release as this is internal API (even though some usages of tracer have unfortunately bled outside the core agent).
Only test code was still using `tracer.segment`. I did not find any usages in external modules.
I cleaned up some usage of `tracer.getSegment()` in the test files touched but did not attempt a full cleanup. That can be a follow-up.
`getContextManager()` was added to the agent helper to try to avoid grabbing directly off the agent all over the place. It does currently soft-rely on the agent being loaded first which is brittle. I think ideally we'd have helper APIs that generally returned both but we can see how things evolve. I'll also need to add this to the external test helper. At some point, I'd …
> Removes tracer.segment

- test/versioned/bluebird/methods.js
- test/versioned/bluebird/methods.tap.js
* Moved `methods.js` under bluebird versioned test folder.
Our BlueBird versioned tests were the only current usage of `methods.js`.  Moved under that folder to make the relationship clear. The methods file does leverage a file still from the integration tests but that is also used for when, so I left all of that as-is. This has come up a couple times so getting moved for clarity.  Extracting into the `methods.tap.js` didn't seem worth the effort at this point.
> Moves methods.js under bluebird versioned test folder.

- lib/metrics/names.js
- lib/shimmer.js
- test/integration/module-loading/module-loading.tap.js
- test/integration/module-loading/node_modules/customTestPackage/package.json
- test/versioned/express/ignoring.tap.js
- test/versioned/hapi/hapi-17/ignoring.tap.js
- test/versioned/hapi/hapi-post-18/ignoring.tap.js
- test/versioned/hapi/hapi-pre-17/ignoring.tap.js
- test/versioned/restify/restify-post-7/ignoring.tap.js
- test/versioned/restify/restify-pre-7/ignoring.tap.js
* Added support metrics for tracking when instrumentation was applied per module.
* `Supportability/Features/Instrumentation/OnResolved/<module-name>`
* `Supportability/Features/Instrumentation/OnResolved/<module-name>/Version/<major version>`
* `Supportability/Features/Instrumentation/OnRequire/<module-name>`
* `Supportability/Features/Instrumentation/OnRequire/<module-name>/Version/<major version>`
Examples:
- 'Supportability/Features/Instrumentation/OnRequire/domain', 
- 'Supportability/Features/Instrumentation/OnRequire/restify', 
- 'Supportability/Features/Instrumentation/OnRequire/restify/Version/6'
Only attempts to grab the version if the shim found a module root to avoid grabbing the agent version. Version doesn't apply to 'domain' either, for example.
> Adds metrics for tracking when instrumentation is applied 

- .github/workflows/add-to-board.yml
- .github/workflows/board.yml
* Added a reusable workflow to automatically add issues to the Node.js Engineering Board when created.  
* Closes #866 
This leverages the GitHub cli to use the api to find the column in project and add the relevant issue or PR.  This creates a reusable workflow but also adds a reference to it for the node agent repo.  I figured we can keep the reusable workflow in main agent.  I will create follow up PRs to reference this workflow for all of our other repos.  This will add all new issues to the `Triage Needed: Unprioritized Features` and all new PRs to `Needs PR Review` columns.  These are defaults and you can provide whatever string is needed for the "todo" and "pr" columns.  Lastly, shout out to the docs team for the lovely [copy …
> Added a reusable workflow to add issues and PRs to project boards

- .gitignore
- bin/git-commands.js
- bin/run-versioned-tests.sh
- package-lock.json
- package.json
- test/versioned-external/checkout-external-tests.js
- test/versioned-external/external-repos.js
- test/versioned-external/readme.md
- third_party_manifest.json
* Runs versioned tests for external modules against tests defined in the external repository instead of tests published in npm modules.
New setup output
```
> newrelic@8.6.0 versioned:npm7
> npm run checkout-external-versioned && npm run prepare-test && NPM7=1 time ./bin/run-versioned-tests.sh
> newrelic@8.6.0 checkout-external-versioned
> node ./test/versioned-external/checkout-external-tests.js
Creating new TEMP_TESTS folder.
Executing: 'git clone --filter=blob:none --no-checkout --depth 1 --sparse https://github.com/newrelic/node-newrelic-aws-sdk.git aws-sdk'
Executing: 'git sparse-checkout set lib tests/versioned'
Executing: 'git checkout main'
Executing: 'git clone --filter=blob:none --no-checkout --depth 1 --sparse https://github.com/newrelic/node-newrelic-koa.git koa'
Executing: …
```
> Updates to run external module versioned tests cloned from repos 

- .github/workflows/board.yml
* Changes token used to post issues to org level project board
We merged #999 and the workflow wasn't working.  When I was testing locally I was using a personal access token that had access to the org.  Also when I tested in my node-newrelic fork the project was at the repo which github actions has access to with the `GITHUB_TOKEN`.  The issue is that you cannot get perms outside the given repo, probably for good reason.  The only workaround is to generate a personal access token and add to secrets.  I did that, updated the code and documented in a secure note in last pass about the value, how to update it and context that's its on my account.
https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp
> changes secret to post to org level project board

- .github/workflows/add-to-board.yml
- .github/workflows/board.yml
* Fixed add to board workflow to properly pass repository secrets into reusable board workflow.
Ok I'm confident this is the last PR on this effort.  Unfortunately we have to pass in `secrets.gh_token` with an org level PAT.  This means that in external repos we'll have to specify the same PAT.  I was hoping the reusable workflow would just reference this repo's `secrets.GH_ORG_TOKEN` but this is a limitation of reusable workflows, see: https://github.community/t/reusable-workflows-secrets-and-environments/203695/4.
> Pass in environment secrets from caller workflow

- .github/workflows/create-release.yml
- .github/workflows/post-release.yml
- .github/workflows/release-creation.yml
- bin/create-github-release.js
- bin/create-release-tag.js
* Added a reusable workflow to create a release tag, publish to NPM and publish a GitHub release.
* Updated agent release workflow to reference reusable workflow.
* Added a new workflow to update RPM and publish API docs on a published release event type.
Closes #1049 
* Every repo using this will need to add a new secret `NPM_TOKEN` which is stored in LastPass.
* I wasn't able to completely test this as it would make a new release. We may need to fix random issues when we actually use it the first time
To use reusable workflow:
```sh
jobs:
fake-release:
uses: newrelic/node-newrelic/.github/workflows/release-creation.yml@main
with:
changelog_file: CHANGELOG.md #Only need to pass this in if the changelog file is not NEWS.md
```
> Abstract release creation

- .github/workflows/release-creation.yml
- bin/check-workflow-run.js
- bin/create-github-release.js
- bin/create-release-tag.js
and not always running against node-newrelic
* Fixed release creation reusable workflow by passing in repo to `bin/create-release-tag.js` and `bin/create-github-release.js`.
Closes #1053
Pretty confident this is the last of the changes as I tested it against node-test-utilities: https://github.com/newrelic/node-test-utilities/actions/runs/1679480457
> fixed check workflow and release creation by passing in repo

- .github/workflows/post-release.yml
* Changed the trigger for post release jobs.
I was made aware the workflows do not trigger when relying on the [GITHUB_TOKEN](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token).
We have two options:
* Pass in a personal access token in workflows that will trigger others.
* Use [workflow_run](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run) to reference the specific workflow it is relying on.
I opted for the latter to avoid using Personal Access Tokens as much as possible.
> change how we invoke post release activities to work around not using PAT

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
* Upgraded `@newrelic/test-utilities` to latest to get `helpers.getShim` so sub packages properly execute.
We updated sub packages like `@newrelic/koa` and its versioned tests use `helpers.getShim`.  That didn't exist until 6.3.0.
> upgraded test utils so sub packages properly run versioned tests

- bin/create-docs-pr.js
- bin/git-commands.js
* Added a script to be used by agent developers to add a PR to `docs-website` after the release of agent.
Closes #590
Currently this relies on the fact you have a fork of docs-website on your local machine.  Once we get a machine user we can remove some code around specifying the username as we will be cloning the repo in CI and adding PR from the repo itself.
To run script:
```sh
GITHUB_TOKEN=<redacted> node bin/create-docs-pr.js --username bizob2828 --tag v8.7.0 --repo-path /path/to/docs-website
```
You can also use the `--dry-run` flag to run through script but it will not create the branch, push to origin and create PR.
> Script to add release notes to docs-website

- bin/create-docs-pr.js
* Fixed an issue with the docs PR script that assumed `\n` in the NEWS.md file when extract version and release date
> fixed regex to use `\s` instead of \n to get release date

- bin/docker-services.sh
- test/lib/params.js
- test/versioned/mongodb/collection-index.tap.js
- test/versioned/mongodb/common.js
- test/versioned/mongodb/package.json
* Added a new `mongo:5` container to `npm run sevices` to test mongodb driver >=4.2.0.
Closes #982
This just adds a new config stanza in `lib/params` so if the db driver >=4.2.0 it will connect to the mongo:5 container.
> Added support for mongodb driver > 4.2.0

- examples/shim/Datastore-Simple.md
It was not computing the time spent by the operation without passing the third parameter as true.
Documentation fix in a sample of the Datastore Instrumentation for Node.js.
The [tedious-newrelic](https://github.com/CKarper/tedious-newrelic) lib was not computing query times. When I was analyzing the code, everything was fine following this Datastore Instrumentation documentation. After quite a while of debugging and studying the API documentation, I found this fix. That's why I am opening this pull request and another [pull request](https://github.com/CKarper/tedious-newrelic/pull/3/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R15) in the lib.
It would also be nice to better explain the third parameter of the `shim.bindSegment` function and the direct effect …
> Fix to compute time when using shim.bindSegment.

- .github/workflows/post-release.yml
- bin/update-system-config-pages.js
* Updated method for retrieving agent version from repository by using `cat package.json | jq .version`
Closes #1071 
I tested this via act `act -j update-rpm-and-docs` with a modified workflow.
Output here
```sh
[Agent Post Release/update-rpm-and-docs]   ⚙  ::set-output:: latest_tag="8.7.1"
[Agent Post Release/update-rpm-and-docs]   ✅  Success - Get Created Tag
[Agent Post Release/update-rpm-and-docs] ⭐  Run Test output
[Agent Post Release/update-rpm-and-docs]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/revans/code/node-newrelic/workflow/3] user= workdir=
| Value of output 8.7.1
```
> updates method for retrieving current agent version from repo

- .github/workflows/post-release.yml
- bin/publish-docs.sh
- package.json
- third_party_manifest.json
* Fixed Post Release workflow by properly configuring git credentials so it can push API docs to branch
* Added `set -e` in publish docs script to exit on possible failures
* Removed redundant `npm ci` in publish API docs script
Closes #1077
> Fixed post release workflow, removed re-installing deps in publish api docs

- .github/workflows/notify-release.yml
- bin/pending-prs.js
* Added ability to ignore certain PRs in `bin/pending-prs.js` report to slack
Closes #1082
I will create an environmental secret to house the `ignoredLabels`.  Right now my thought is to apply the following:
* `dev:automation`
* `documentation`
* `dev:tests`
I also added a `dry-run` flag to the script so it won't post to slack.  
```sh
GITHUB_TOKEN=<redacted> node bin/pending-prs.js --repos node-newrelic --dry-run --ignore-labels dev:automation,documentation,dev:tests
```
> added ability to not include PRs that have certain labels

- lib/shim/shim.js
- test/unit/shim/shim.test.js
* Updated shim to pass active segment to inContext callback.
This provides convenience for instrumentation that needs to decorate the active segment without having to call to retrieve it.
> Pass Active Segment to inContext callback

- lib/utilization/aws-info.js
- lib/utilization/common.js
- test/integration/pricing/system-info.tap.js
- test/integration/pricing/vendor-info-tests.js
- test/lib/cross_agent_tests/utilization_vendor_specific/aws.json
- test/unit/utilization/common.test.js
* Updated AWS metadata capture to utilize IMDSv2.
Closes #1100
I verified this by enforcing http tokens on my EC2 instance
```sh
aws ec2 --region us-east-1 modify-instance-metadata-options --instance-id <instance-id> --http-tokens required --http-endpoint enabled
```
I ran the agent on this branch on my EC2 and still saw the vendors info in the connect message.
```json
{"vendors":{"aws":{"availabilityZone":"us-east-1e","instanceId":"<redacted>","instanceType":"t2.micro"}}}
```
I also verified that when IMDSv2 was on that it failed without the fixes in this PR
```json
{"v":0,"level":20,"name":"newrelic","hostname":"<redacted>","pid":6012,"time":"2022-02-18T18:01:38.294Z","msg":"Got 401 Unauthorized from metadata request \"{\\\"protocol\\\":\\\"http:\\\",\\\"slashes\\\":true,\\\"auth\\\":nul …
```
> IMDS v2 support for AWS Metadata

- .eslintrc.js
- test/versioned-external/checkout-external-tests.js
* Updated external version test running to support more test scenarios.
* Adds `test/versioned-external` to lint ignore to avoid issues for scripts in tests that auto run linting tools (next/react).
* Adds `index.js` and `nr-hooks.js` to files automatically checked-out for test runs.
* Resolves build issues for: https://github.com/newrelic/node-newrelic/pull/1102
The compilation of the next application for the Next.js instrumentation versioned tests results in scripts that attempt to run linting and fail both linting setup and attempt to compile in weird ways (failing on import, etc.) likely due to lack of the correct eslint plugin. We do not want/need linting on the test application and also do not want/need linting from the main agent for items pulled in for external versioned test …
> Allow external versioned testing to run more scenarios

- lib/utilization/aws-info.js
- test/integration/pricing/system-info.tap.js
- test/lib/cross_agent_tests/utilization_vendor_specific/aws.json
* Updated the AWS IMDBS v2 endpoint to use `latest` to align with the internal agent specification.
The agent teams got around to updating spec and we landed on using `latest` instead of `2016-09-02`.  This PR will update the cross agent tests and code to stay in sync.  Relevant PRs in GHE: https://source.datanerd.us/agents/agent-specs/pull/569/files, and https://source.datanerd.us/agents/cross_agent_tests/pull/147/files.
> updated aws imdbs v2 uri to use latest instead of 2016-09-02

- test/versioned/hapi/hapi-post-18/package.json
* Updated @hapi/hapi Node 16 versioned test runs to run against @hapi/hapi >=20.1.2 so future major releases will be ran.
For versioned tests we typically are setup to always test newest. If a new major version breaks and it isn't a quick fix, then we ensure we have a GitHub issue for adding support prior to limiting the upper bound of the version run.
> Updates @hapi/hapi node 16 test perumutatinos to use @hapi/hapi >=20

- bin/git-commands.js
- test/versioned-external/external-repos.js
* Fixed sparse checkout of non-default branch for external versioned tests.
* Added external versioned tests for the Apollo Server plugin instrumentation.
* Blocked by: https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/177
This won't pass until https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/177 is merged.
In the meantime, can manually test locally against that branch by changing the configuration to:
```
{
name: 'apollo-server',
repository: 'https://github.com/michaelgoin/newrelic-node-apollo-server-plugin/',
branch: 'use-latest-newrelic',
additionalFiles: [
'tests/agent-testing.js',
'tests/create-apollo-server-setup.js',
'tests/data-definitions.js',
'tests/test-client.js'
]
}
```
Running `npm run versioned:major` should result in something like:
``` …
```
> Add apollo server plugin external tests

- test/versioned/mysql/basic-pool.tap.js
- test/versioned/mysql/pooling.tap.js
- test/versioned/mysql/setup.js
- test/versioned/mysql/transactions.tap.js
- test/versioned/mysql2/basic-pool.tap.js
- test/versioned/mysql2/pooling.tap.js
- test/versioned/mysql2/setup.js
- test/versioned/mysql2/transaction.tap.js
* Updated mysql and mysql2 versioned tests to run against their own databases on the MySQL instance.
Recently starting getting failures rotating between mysql and mysql2 tests which led me to assume contention on a table. Looking at the setup, these use the same user/database/table combination and part of the setup is to TRUNCATE (clear) the table. One of the failures was querying data from this table, so the theory seems to check out.
Often, I'll introduce generated GUID table names and such to prevent collisions but in this case we'll only ever have a single file from each running at a time. So to get a quick fix in, I instead have each suite run in their own database within the MySQL Server instance. I've wired these up to exposed variables exported from the `setup` files so this …
> Fix mysql test resource contention

- test/bin/install_sub_deps
* Excluded installing dependencies in `versioned-external` folders when running integration tests.
I noticed this while running integration tests.
```sh
installing deps in /Users/revans/code/node-newrelic/test/helpers
installing deps in /Users/revans/code/node-newrelic/test/integration/uninstrumented
installing deps in /Users/revans/code/node-newrelic/test/versioned-external/TEMP_TESTS/apollo-server/tests/versioned/apollo-federation
installing deps in /Users/revans/code/node-newrelic/test/versioned-external/TEMP_TESTS/apollo-server/tests/versioned/apollo-server-express
installing deps in /Users/revans/code/node-newrelic/test/versioned-external/TEMP_TESTS/apollo-server/tests/versioned/apollo-server-fastify
installing deps in /Users/revans/code/node-newrelic/test/versioned-external/TEMP_TEST …
```
> exclude versioned-external from install sub deps when running integration tests

- lib/shim/shim.js
- test/unit/shim/shim.test.js
* Fixed `shim.wrapReturn` to call `Reflect.construct` in construct Proxy trap.  Also including `newTarget` to work with inherited classes.
Closes #1126
I noticed we don't use `Reflect.` for any proxy traps.  Historically I've always used those but I don't know if it makes a different. In this case it definitely does because it allows passing in the `newTarget` to work with inheriting classes.  [Proxy construct docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/construct)
> use Reflect.construct to call constructor in wrapReturn

- THIRD_PARTY_NOTICES.md
- lib/sampler.js
- package-lock.json
- package.json
- third_party_manifest.json
This is available via `process.cpuUsage` since Node 12, which is now
the lowest version we support. We have removed the corresponding code
in @newrelic/native-metrics since version 8.0.0, so this removes its
only calling site in the main agent.
* Removed native CPU metric sampler
* Fixes https://github.com/newrelic/node-native-metrics/issues/154
> lib/sampler.js: removed native CPU metric sampler

- documentation/transaction-naming-philosophy.md
* Added transaction naming documentation ported from a discussion forum post: https://discuss.newrelic.com/t/relic-solution-the-philosophy-of-naming-your-node-agent-transactions/.
* https://discuss.newrelic.com/t/relic-solution-the-philosophy-of-naming-your-node-agent-transactions/58071
For the most part, I maintained the same content and formatting from the original. I just removed one phrase that was unnecessary and fixed a couple links. Its possible I missed some things, though.
We may eventually want to explain where the approach differs more broadly. For example, koa routing is async-await based so may pop all the way back out of a middleware chain to the original in order to send a response. Since this would result in poor naming, especially in error cases, transactions are now …
> Adds document porting transaction naming philosophy from forum

- lib/serverless/aws-lambda.js
- lib/shim/shim.js
- test/unit/shim/shim.test.js
* Fixed promise interceptor from re-throwing errors.
Closes #566
Our promise interceptors change behavior of code for the worst.  By adding then and catch handlers to promises we are adding additional links on the promise chain.  By re-throwing errors we're trying to solve a case where a customer may not have a catch handler and an unhandledRejection would occur.  However, there are side effects like this bug that occur.
The big change here is if you have unhandledRejections and were listening with `process.on('unhandledRejection')` they will now be `process.on('uncaughtException')`
A simple test case shows this behavior
```js
let prom = new Promise((resolve, reject) => {
setTimeout(() => {
const err = new Error('no soup for you')
reject(err)
}, 10)
})
function wrapPromise(promise) { …
```
> stop propagating errors in promise interceptor

- lib/instrumentation/mysql/mysql.js
- lib/instrumentation/mysql/nr-hooks.js
- lib/instrumentations.js
- test/versioned/mysql2/promises.tap.js
* Added instrumentation for `mysql2/promise`.
* This previously only existed in our standalone `@newrelic/mysql`, but now gives feature partiy between the two.
Closes https://github.com/newrelic/node-newrelic-mysql/issues/47
With this PR and https://github.com/newrelic/node-newrelic-mysql/pull/70, we now have feature parity between the agent and external module.  It'll make it easier to decide if we remove the code from agent or scrap the external `@newrelic/mysql` module.
> ported mysql2/promise instrumentation + tests from the external @newrelic/mysql repo

- bin/run-versioned-tests.sh
* Added `--strict` flag to versioned test runner to properly fail CI runs when test files are not included.
Closes #1140
> pass in --strict flag to ensure CI runs fail when forgetting to add a new test file

- test/versioned/mongodb/package.json
Looks like there were a few versions of the `mongodb` client that didn't play well with our instrumentation. These haven't been getting hit due to the 10 version sampling but some started to on full runs. I haven't looked into the "why" but recent versions all work.
> Skips mongo versions 4.0.0 through 4.1.3 in versioned tests.

- test/versioned/hapi/hapi-post-18/package.json
- test/versioned/hapi/hapi-pre-17/package.json
* Limits permutations of hapi tests.
A lot of these will go away when we rip out support for most deprecated versions of hapi in the next major release. In the meantime, this will speed up some of the hapi testing.
Hapi post 18 was the slowest non-aws versioned. I noticed it was testing hapi versions against "vision" versions. So 10 x 5 permutations. Seems enough to know vision is continuing to work so set that to latest.
Limited samples of older runs. Newer (18+) got more runs. Older (pre 17) got around the number of major versions + 1 extra (didn't follow this exactly).
> Limits the number of test permutations for some hapi versions.

- test/versioned/express/package.json
Specifies a specific version of `ejs` to reduce express test runs down to 160.
The `2.5` was resulting in two versions of `ejs` being tested: 2.5.5, 2.5.9. Given the 10 versions of express being tested + large number of test files this was resulting in 320 test runs when testing "minor" versions on main branch runs. Unless something comes up, I don't believe we need to test multiple 2.x versions of `ejs` and don't think that was the intention of how it was configured.
Unsure if this is an npm thing or versioned runner thing or if it is new due to recent enhancements or has always been that way.
> Sets a more specific version of ejs for express tests to reduce permutations

- lib/agent.js
- lib/config/default.js
- test/unit/agent/agent.test.js
- test/unit/config/config-defaults.test.js
* Changed default value of `application_logging.enabled` to be true.
* Fixed check to ensure both `application_logging.enabled` and `application_logging.forwarding.enabled` are true before registering the log aggregator.
This was a misinterpretation of the spec originally.  It should be an inclusive check and not a switch where the value of `application_logging.enabled` takes precedence. Also `application_logging.enabled` should default to true to allow customers to configure fowarding, metrics, and decorating accordingly without having to change 2 config values.  However, they can disable all by setting `application_logging.enabled` to `false`.
> fix logging config checks

- lib/instrumentation/@redis/client.js
- lib/instrumentations.js
- test/versioned/redis/package.json
- test/versioned/redis/redis-v4.tap.js
- added @redis/client folder to account for changes in packages in 4.1.0 of redis
- explicity call t.end to end each test
- check if client exists in afterEach before flushing and disconnecting
* Added instrumentation for `@redis/client`.  In 4.1.0 of redis it switched from using `@node-redis/client` to `@redis/client`. This meant instrumentation was not registering because it relies on package name.
I also refactored the tap tests to explicity call `t.end()`.  There was a mix of `t.plan`, `t.autoend` and `t.end`.  It seemed to cause inconsistencies in test runs.  When I changed that the segment array in the last test changed because of the setTimeouts tap creates when calling `t.autoend`.
> Add @redis/client instrumentation

- newrelic.js
* Removed distributed tracing setting from example config
This feature is now on by default. So there's no need to recommend it.
The docstring here is also wrong anyway about default being false,
anyway.
> newrelic.js: remove distributed tracing from sample config

- newrelic.js
local_decorating is mutually exclusive with forwarding, and we want to recommend forwarding as the default method.
> newrelic.js: remove local_decorating

- lib/agent.js
- lib/aggregators/log-aggregator.js
- lib/transaction/index.js
- lib/transaction/logs.js
- test/unit/aggregators/log-aggregator.test.js
- test/unit/transaction-logs.test.js
- test/unit/transaction.test.js
…n context, updated transaction to store logs until it ends then flush by adding to log aggregator
* Added a storage mechanisms to transactions to keep logs until transaction ends.
* Updated log aggregator to check transaction context before adding.  Otherwise it adds to transaction and then transaction will add batch to aggregator when it ends with the appropriate priority.
Closes #1172 
This will fulfill the 2 items from spec we were in violation of for a bit:
* Logs **MUST** be treated like other data types recorded within transactions. If the transaction is ignored for instance, these logs should be excluded from capture.
* Logs **MUST** be prioritized using the existing [Priority Sampling](./Priority-Sampling.md) approach. This aims to increase the chances that traces in the product …
> refactored log aggregator to only add to queue when not in transaction context

- lib/config/hsm.js
- test/unit/high-security.test.js
* Set `application_logging.forwarding.enabled` to false when HSM is set.
Closes #1169
I verified this by using an account that has HSM enabled(account 2733645 in production).  I also added `high_security: true` in my local config.  Then started app with `application_logging.forwarding.enabled: true` and verified it gets set to false and that logs are not enriched with linking metadata nor forwarded to log aggregator.
> Disable application logging fowarding in HSM 

- lib/collector/facts.js
- lib/metrics/names.js
- test/unit/facts.test.js
* Added supportability metrics for some popular logging frameworks
Closes #1148 
I am not quite sure but I think the environment's packages seems to be
the right place to look for these. Those are logging libraries
directly mentioned in packages.json, as far as I can tell. This is as
opposed to the environment's dependencies which seems to be all the
packages the current packages depend on.
> facts: add supportability for some popular logging libraries

- .github/workflows/post-release.yml
By default, github's actions/checkout action will do a shallow clone
of a single commit, without history. Since our workflow requires a
merge, we need the full history in order to be able to perform the
merge.
> post-release: fetch the full repo, not a shallow clone

- lib/instrumentation/winston.js
- test/versioned/winston/winston.tap.js
* Fixed an issue when creating a winston logger with an already instantiated logger.
Closes #1190
We had some missing logic around instrumenting `winston.createLogger`.  You can create a logger from an instianted logger.  When this is the case the transports are read-only and we caused the application to crash. The customer, graciously provide a clear [reproduction case](https://github.com/DenisSlapelis/newrelic-sample).  I added 2 tests around composing loggers and verifying it doesn't create extra log lines in aggregator and more importantly does not crash.
If you comment out the `isStream` bit in instrumentation the tests will fail/crash like bug
```sh
not ok 1 - Cannot set property transports of \#<Logger> which has only a getter
---
stack: >
Object.createWrappedLogger [as …
```
> Handle composable loggers

- api.js
- test/unit/rum.test.js
* Added an optional way to avoid wrapping browser agent script with <script> tag when using `api.getBrowserTimingHeader`.  This will ease usage with Component based libraries like React.  
* https://github.com/newrelic/newrelic-node-nextjs
* Based on usage of NewRelic inside NextJs (https://github.com/newrelic/newrelic-node-nextjs) it would be relevant to not wrap the browser agent script with `<script>` to let developers to use their own React component or the built in `<Script>` component from NextJs (https://nextjs.org/docs/basic-features/script)
> Add a way to import agent script without wrapping tag

- THIRD_PARTY_NOTICES.md
- lib/instrumentation/nr-winston-transport.js
- lib/instrumentation/winston.js
- package-lock.json
- package.json
- test/unit/licenses.json
- test/versioned/winston/helpers.js
- test/versioned/winston/winston.tap.js
- third_party_manifest.json
* Moved log forwarding logic to a transport so customer transports are not polluted with NR linking metadata and timestamp and error manipulations.
Closes #1209
This is our evolution of automagical instrumentation of winston.  This feels like the _best_ solution for the log forwarding use case.  When log forwarding is enabled, we will add a transport and all that transport does is clones a log line and adds NR linking metadata and reformat errors and timestamps to fit the requirements for application logging.  This solutin will not affect customer transports/formatters and they can continue to co-exist with 0 issue.  The formatter still exists but it will just be used to collect logging metrics and to decorate the message with `NR-LINKING` piped metadata when local log decorating is …
> New Relic Log Forwarding Transport

- test/unit/collector/serverless.test.js
- test/unit/serverless/aws-lambda.test.js
This requires a small change to output monitoring to ensure that we
are still attempting to output the right things, despite the
redirection.
* Silenced stdout from serverless tests
* Closes #1212
> serverless tests: silence stdout output by piping to /dev/null

- lib/instrumentation/winston.js
- Fixes passing undefined as a formatter options to `winston.format.combine` 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in#using_in_with_deleted_or_undefined_properties
After upgrading `v8.13.0` my company  repos started to see this error
```
TypeError: Exception Setting Global Vars. Cannot read properties of undefined (reading 'transform')
at isValidFormat (/Users/[OMITTED]/Desktop/signup-apis/node_modules/logform/combine.js:37:18)
at Array.every (<anonymous>)
at cascade (/Users/[OMITTED]/Desktop/signup-apis/node_modules/logform/combine.js:14:16)
at module.exports (/Users/[OMITTED]/Desktop/signup-apis/node_modules/logform/combine.js:57:33)
at registerFormatter (/Users/[OMITTED]/Desktop/signup-apis/node_modules/newrelic/lib/instrumentation/winston.js:73:34 …
```
> fix: uses opts.format instead of in operator

- package-lock.json
Closed #1227
* Fixes CVE-2022-25878
* closes #1227
* [Snyk report](https://snyk.io/vuln/SNYK-JS-PROTOBUFJS-2441248)
> package-lock.json: update protobufjs version

- test/unit/agent/agent.test.js
If a unit test uses mock there seems to be common patterns in afterEach
```js
t.afterEach(() => {
helper.unloadAgent(agent)
agent = null
if (!nock.isDone()) {
/* eslint-disable-next-line no-console */
console.error('Cleaning pending mocks: %j', nock.pendingMocks())
nock.cleanAll()
}
nock.enableNetConnect()
})
```
The cleaning pending mocks is a nice addition to help inform the engineer that they are mocking too much or something isn't finished and should probably wait.  We had 2 tests in agent that logged this but the pending calls were expected because that was the purpose of the test.  Instead of outputting this message, I explicitly cleaned all mocks in the tests to avoid this log.
Before
```sh
test/unit/agent/agent.test.js 2> Cleaning pending mocks: ["POST …
```
> clear pending mocks

- test/integration/newrelic-response-handling.tap.js
Closes #1164
This test asserts that when the agent re-connects it pulls the harvest limits from the original config max_samples_stored for every piece of data. This is done so on restart loops we aren't using the new harvest limit value from server that has been down sampled.  It could result in harvest limits being 0 if enough restarts occur.
> Harvest limits reconnect integration test

- test/versioned/amqplib/package.json
* Removed latest amqplib (v0.10.0) from versioned testing, as it fails to instrument properly.
* Schließt nicht https://github.com/newrelic/node-newrelic/issues/1236
This library is breaking CI and figuring out how to fix our instrumentation is not simple or obvious, so we're going to ignore it for now and come back to it after current blocked PRs are merged.
> ignore latest amqplib which breaks instrumentation

- test/versioned/amqplib/amqp-utils.js
- test/versioned/amqplib/package.json
- removed pinning amplib version
- added logic to handle differences in where segments live with native promies in > 0.10.0 of amqplib
Closes #1236
amqplib [0.10.0](https://github.com/amqp-node/amqplib/blob/main/CHANGELOG.md#chagnes-in-v0100) ripped out bluebird in favor of native promies.  This broke some of our test assertions because the segment tree had been flattened.  It was simliar to changes in 0.9.0 but for other reasons.  This PR creates a `NATIVE_PROMISES` flag and accesses the approrpiate segments within a tree when executing promise based methods in 0.10.0+.
> fix amplib tests

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
Update @grpc/proto-loader to v0.6.13 to pickup security fixes in protobufjs.
Solves this security issue: https://github.com/advisories/GHSA-g954-5hwp-pp24
@grpc/proto-loader uses a fixed version of protobufjs.
The package protobufjs before 6.11.3 are vulnerable to Prototype Pollution which can allow an attacker to add/modify properties of the Object.prototype.
> upgrades to patch vulnerability in protobufjs

- test/unit/errors/error-collector.test.js
Removed mocha and chai constructs in favour of pure tap from `error-collector.tests.js`.  Most of this is straightforward translation, with some caveats:
1. Due to `beforeEach` running on each test *and* subtest, we now
check for agents before attempting to load them again.
2. The tests for`request.uri` were incorrect and were checking for a
property that has been removed from error traces since
38ea6045552ed370cb02c82f7818e1de84cd93a7.
3. Had to pass down the `t` tap object to some helper functions since
we no longer have globals.
> error-collector.tests: removed mocha and chai constructs in favour of pure tap

- test/versioned/fastify/package.json
Fastify 4 was just released yesterday and it drops support for node 12.  We have to update our version tests to skip the 4.x line for node 12. It was noticed here in [CI](https://github.com/newrelic/node-newrelic/runs/6815110614?check_suite_focus=true)
> pin fastify 4.x to node 14+

- bin/git-commands.js
- test/versioned-external/checkout-external-tests.js
* Fixed how we clone external repos to account for newer versions of git
Closes #1276
In git 2.37.1 sparse-checkout changed one of the default options to use sparsecheckoutcone which breaks when specifying files.
> Update sparse-checkout command

- bin/docker-services.sh
When we run `npm run services` on a Mac M1 it fails to run mysql
```
docker run --name nr_node_mysql -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" -e "MYSQL_ROOT_PASSWORD=" -p 3306:3306 mysql:5
Unable to find image 'mysql:5' locally
5: Pulling from library/mysql
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```
If you pass in the `--platform` flag it works 🎉
```
❯ docker run --platform linux/amd64 --name nr_node_mysql -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" -e "MYSQL_ROOT_PASSWORD=" -p 3306:3306 mysql:5
2022-07-13 20:54:33+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.38-1.el7 started.
2022-07-13 20:54:33+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-07-13 20:54:33+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server …
```
> pass in platform flag to get mysql 5 to run on mac m1

- test/versioned/restify/restify-post-7/package.json
* https://github.com/newrelic/node-newrelic/runs/7328944572?check_suite_focus=true
* https://github.com/restify/node-restify/pull/1906
Restify currently attempts to patch Request.prototype.closed which is no-longer valid in Node 18. This will break our versioned tests as Node 18 is added to CI.
Someone has submitted a PR to start Node 18 support: https://github.com/restify/node-restify/pull/1906
> Limits restify-post-7 tests to < Node 18 as restify throws.

- test/integration/core/dns.tap.js
* Updated dns.lookup testing to explicitly verify both verbatim (IPv4, IPv6) states.
* https://github.com/newrelic/node-newrelic/runs/7324812831?check_suite_focus=true
Looks like Node 18 (17) switched `dns.lookup` to default `verbatim: true` when not provided. As such, the test that assumed IPv4 failed. I went ahead and tested both explicitly to ensure our instrumentation didn't munge anything.
> Updates dns.lookup tests to explicit check both verbatim states.

- test/unit/shimmer.test.js
* https://github.com/newrelic/node-newrelic/runs/7340877781?check_suite_focus=true
When adding node 18 to CI there were shimmer unit tests failing for `of deep modules` suite.  It is because we were using `chai` and it defines exports in package.json which are not being enforced.  So we were trying to instrument `chai/lib/chai.js` which was not an export and failed with
```
test/unit/shimmer.test.js ........................... 50/55
shimmer > custom instrumentation > of deep modules > should be sent a shim and the loaded module
not ok Package subpath './lib/chai' is not defined by "exports" in /home/runner/work/node-newrelic/node-newrelic/node_modules/chai/package.json
stack: |
Function.wrappedResolveFilename [as _resolveFilename] (lib/shimmer.js:291:42)
Function.wrappedLoad [as _load] …
```
> change module to "unit" test as chai defines exports which get enforced in node 18

- bin/ssl.sh
- test/lib/test-ca.conf
* Updated self-signed test cert to use sha256 and default size.
* https://issues.newrelic.com/browse/NR-33629
Node 18 requires a hiring minimum cert algorithm than sha1. This caused tests to break with: `error:0A00018E:SSL routines::ca md too weak`.
Developers will need to clear out these files:
* `test/lib/self-signed-test-certificate.crt`
* `test/lib/test-key.key`
* test/lib/ca-*`
Then run `npm run prepare-test`.
> Bumps test self-signed cert to use sha256 and default size.

- lib/instrumentation/mongodb/common.js
- lib/instrumentation/mongodb/v4-mongo.js
* Updated mongodb instrumentation to properly set host and port when connections are made to IPv6 addresses.
* Closes https://issues.newrelic.com/browse/NR-33645
There might be a better way to do this but I didn't want to pull in an external module.
> update mongo instrumentation to account for IPv6 addresses when setting host/port

- bin/docker-services.sh
- lib/instrumentation/mongodb/common.js
- lib/instrumentation/mongodb/v3-mongo.js
- test/versioned/mongodb/collection-common.js
- test/versioned/mongodb/collection-misc.tap.js
- test/versioned/mongodb/db.tap.js
- Upgraded the test container for mongo to mongo v 3 to work with Mac M1. In the process I had to fix both instrumentation and tests to account for the server differences.
- update grep for mongo to not conflate 3 and 5 containers
* Updated mongo server container to v3 so it can run locally on Mac M1s.
* Updated instrumentation of mongodb to account for assumptions being made when running mongo server 2.
* Closes https://issues.newrelic.com/browse/NR-34648
For all devs that are running containers locally you'll have to run the following to clear out the older mongo v2 container:
```sh
docker rm nr_node_mongodb -f
docker rmi mongo:2 -f
```
As you can see from PR I had to update both instrumentation and tests.  The instrumentation still works if you're running v2 of mongo server.  It seems …
> update mongo server container

- test/integration/core/dns.tap.js
- test/integration/core/timers.tap.js
- test/integration/distributed-tracing/trace-context-cross-agent.tap.js
- test/integration/grpc/reconnect.tap.js
- test/integration/instrumentation/hapi/capture-params.js
- test/integration/instrumentation/http-outbound.tap.js
- test/integration/instrumentation/memcached.tap.js
- test/integration/instrumentation/when.tap.js
- test/integration/shimmer/module-load.test.js
- test/integration/transaction/errors.tap.js
- test/integration/transaction/trace-async-propagation.tap.js
- test/integration/transaction/tracer.tap.js
When I was running tests for cert removal I noticed a few deprecated tap assertions and was feeling motivated.  This should remove the last of the depcrecation warnings from tap.
> updated remaining integration tests to no longer use deprecated tap methods

- test/unit/collector/serverless.test.js
- test/unit/config/config-location.test.js
- test/unit/serverless/aws-lambda.test.js
- test/versioned-external/checkout-external-tests.js
Converted `/dev/null` to `os.devNull` in 
- test/unit/collector/serverless.test.js
- test/unit/serverless/aws-lambda.test.js
and converted `fs.promises.rmdir` to `fs.promises.rm` in 
- test/unit/config/config-location.test.js
- test/versioned-external/checkout-external-tests.js
as part of Node 12 deprecation.
https://issues.newrelic.com/browse/NR-35263
TODOs in test code noted these changes for when Node 12 support was dropped. Recursive use of fs.rmdir was deprecated, and its replacement fs.rm was introduced in Node 14.
> Node 12 deprecation todos

- lib/instrumentation/core/http-outbound.js
- test/integration/instrumentation/http-outbound.tap.js
- test/unit/instrumentation/http/outbound.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
* **BREAKING**: Exclude port when making external HTTPS requests to port 443.
Previous external segments would be named `External/example.com:443` when using default HTTPS port.
The external segment will now be named `External/example.com`.
Closes https://issues.newrelic.com/browse/NR-35652
> Exclude :443 on external segments

- index.js
* Updated unsupported odd-numbered release from 17.x to 19.x to prepare for Node 18 support.
I am not sure how to word this changelog entry but we missed a ticket for this.  Even though 19.x won't be released until 10/22 we will add this now so when it does customers will get this warning to use at your own risk.
> Update experimental node version in agent init

- test/unit/config/config-location.test.js
Converted `fs.rmdirSync` to `fs.rmSync` in `test/unit/config/config-location.test.js` as part of Node 12 deprecation.
https://issues.newrelic.com/browse/NR-38203
https://issues.newrelic.com/browse/NR-35263
TODOs in test code noted these changes for when Node 12 support was dropped. Recursive use of `fs.rmdirSync` was deprecated, and its replacement `fs.rmSync` was introduced in Node 14.
> Replaced rmdirSync with rmSync in config location test

- lib/util/application-logging.js
- test/unit/util/application-logging.test.js
* Fixed issue with `truncate` in lib/util/application-logging.js`.  It now checks that the argument is a string before checking its length.
Closes #1308
I will open a separate PR to get this branched off the 8.17.0 tag as we now have breaking changes on main in preparation for Node 18 support.
> Added defensive code in util/applicationLogging truncate to check if value is string before checking its length

- lib/instrumentation/grpc-js/grpc.js
- test/versioned/grpc/client-streaming.tap.js
- test/versioned/grpc/client-unary.tap.js
* grpc: bound the external client segment to the onReceiveStatus listener to propagate transaction context to the grpc client callbacks.
* Closes #1306
We were losing context in async callbacks made after a unary or
client-streaming request ended. Binding the segment during the
instrumentation fixes this.
> grpc: bind the client segment to the onReceiveStatus listener

- NEWS.md
The commit explains it.  We could not merge release/v8.17.1 back into main because it was branched off the v8.17.0 tag.  There would've been conflicts with third party notices.  The relevant code fixes were already merged into main.  The tag has been pushed but this is the only outstanding thing that needs backported.
> backported 8.17.1 changelog section as we could not merge the release branch since it was made out of band from main

- test/integration/pricing/proc_cpuinfo.tap.js
- test/integration/pricing/proc_meminfo.tap.js
Removed async library from pricing integration tests
https://issues.newrelic.com/browse/NR-35280
Affected tests: 
test/integration/pricing/proc_cpuinfo.tap.js
test/integration/pricing/proc_meminfo.tap.js
> Dropped async lib from pricing meminfo and cpu tests

- NEWS.md
- package-lock.json
- package.json
* Added official parity support for Node 18.
* **BREAKING**: Dropped Node 12.x support.  For further information on our support policy,
see: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent
* Upgraded `@newrelic/superagent` `@newrelic/aws-sdk` `@newrelic/koa` `@newrelic/native-metrics` and `@newrelic/test-utilities` to the latest major versions
* Removed Node 12 from CI workflows.
* Updated engines stanza to be `>=14`.
* Updated all versioned tests stanza to be `>=14`
* Converted `fs.rmdirSync` to `fs.rmSync` in `test/unit/config/config-location.test.js`.
* Converted uses of `/dev/null` to `os.devNull` in tests.
* **BREAKING**: Removed certificate bundle from agent. The configuration value `config.feature_flag.certificate_bundle` …
> Release v9.0.0

- lib/util/application-logging.js
- test/unit/util/application-logging.test.js
- test/versioned/pino/pino.tap.js
- test/versioned/winston/winston.tap.js
* Fixed properly setting logging metrics when using custom levels with winston.
This was a follow up from #1329.  A member of the community fixed the issue with pino and I mentioned I would add more test coverage to the utility.  I then decided to add the equivalent versioned test for winston and realized there was another bug with the utility, so I fixed that and added MOAR tests!
> Fix logging metrics for custom levels in winston

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
* Fixed public jsdoc generation.
Added`minami` back as a dev dependency for use with `jsdoc-conf.js`.
* https://github.com/newrelic/node-newrelic/pull/1316
`minami` is referenced by jsdoc-conf as a template. This was accidentally removed in the cleanup PR: https://github.com/newrelic/node-newrelic/pull/1316.
> Re-adds minami as a dev dependency.

- lib/collector/remote-method.js
- lib/config/default.js
- lib/config/env.js
- lib/config/index.js
- test/unit/collector/remote-method.test.js
* Expose  `compressed_content_encoding` configuration and defaulted it to "gzip"
* Closes #1137 
This also makes the setting actually configurable instead of being
internally hard-coded to deflate
> Change compression method to gzip by default

- test/integration/config/index.tap.js
- test/unit/lib/logger.test.js
* Added unit test suite for `lib/logger.js`
* Added destructive integration test for Configuration instantiation
Closes #1112 
The first part is pretty self explanatory, the destructive integration test is for ensuring that if we fail to initialize the config, that we don't crash the process 😬
> Added unit test suite + integration test

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/troubleshooting.md
I noticed during a grooming session we have a troubleshooting.md that was never getting referenced.  I looked at how we handle this in other repos and updated it to be like [apollo plugin](https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/main/.github/ISSUE_TEMPLATE/config.yml)
> fix troubleshooting template

- lib/transaction/index.js
- test/unit/transaction-naming.test.js
- test/unit/transaction.test.js
* Fixed transaction name finalization to properly copy the appropriate transaction name to root segment.
Closes https://issues.newrelic.com/browse/NEWRELIC-3089
A customer reported not being able to find transactions that were displaying as the transaction.name attribute on base span/segments.  After digging I realized it was because they had both custom naming rules and using the `setTransactionName` API to name transactions.  Our transaction finalization logic to copy the transaction name to the root segment was broken.  It favored custom naming rules over API based transaction naming.  I was able to determine a mismatch in logic around transaction name resolution and adding transactions to intrinsic events.  The latter was relying on transaction.getFullName() to extract name which as …
> Fixed transaction name finalization to properly copy the appropriate transaction name to baseSegment

- .lintstagedrc.json
- THIRD_PARTY_NOTICES.md
- esm-loader.mjs
- package-lock.json
- package.json
- test/unit/esm-loader.test.mjs
- third_party_manifest.json
* Updated ESM loader to pass in all arguments to parent resolve methods.
Closes NEWRELIC-3588
It was found during tests of node 14 and 16 that our ESM loader would not work.  Due to the experimental nature of the loader API this fix will add support for Node 16.12.0+.  We do not intend to support any versions less than that with the ESM loader because the resolve hook point does not return format for a given module.  We rely on it to update the path in shimmer for cjs instrumentation.  It's technically not needed right now because we don't support any ES module instrumentation but when we do this will be a requirement.
> Fix esm loader to work in Node < 18

- lib/instrumentation/mongodb/v4-mongo.js
* Updated the alias for localhost in mongodb instrumentation when dealing with IPv6 addresses.
In #1288 we added support for IPv6 address parsing.  At that time `::1` was the the localhost alias.  However mongodb just released 4.10.0 and [IPv6 host connection fix](https://jira.mongodb.org/browse/NODE-4621) broke our tests.  I'm debating on if I should add the `::1` back to the list but I removed and ran `npm run versioned:minor mongodb` and had 0 failing tests.
> Fix handling ipv6 localhost alias for mongodb instrumentation

- esm-loader.mjs
After manually testing I figured it'd be good to also add a warning when using an unsupported Node.js version with ESM loader.  We will have the `Supportability/Features/ESM/UnsupportedLoader` but not as obvious.
Here's what a line in log will look like
```sh
{"v":0,"level":40,"name":"newrelic","hostname":"TK46XHNX04","pid":4945,"time":"2022-09-21T20:05:23.676Z","msg":"New Relic for Node.js ESM loader requires a version of Node >= v16.12.0, your version is v14.20.0.  Instrumentation will not be registered.","component":"esm-loader"}
```
> added a warning message when running on an unsupported version of node with esm loader

- test/versioned/mongodb-esm/bulk.tap.mjs
- test/versioned/mongodb-esm/collection-common.mjs
- test/versioned/mongodb-esm/collection-find.tap.mjs
- test/versioned/mongodb-esm/collection-index.tap.mjs
- test/versioned/mongodb-esm/collection-misc.tap.mjs
- test/versioned/mongodb-esm/collection-update.tap.mjs
- test/versioned/mongodb-esm/common.cjs
- test/versioned/mongodb-esm/cursor.tap.mjs
- test/versioned/mongodb-esm/db.tap.mjs
We have had instability with versioned tests for a few days.  I think it is related to the db.tap tests sharing collection names between ESM and CJS.  This PR updates the esm tests to use a centralized constant only used in esm to avoid this collision.
> Stabilize mongo tests

- NEWS.md
* Added [experimental loader](https://nodejs.org/api/esm.html#loaders) to support instrumentation of CommonJS packages in ECMAScript Module(ESM) applications.
* It only supports versions of Node.js >= `16.12.0`.
* It is subject to change due to its experimental stability.
* Enhanced supportability metrics for ESM support.
* Added new metrics to track usage of ESM loader(`Supportability/Features/ESM/Loader` and `Supportability/Features/ESM/UnsupportedLoader`).
* Updated instrumentation map to include an optional "friendly name" for tracking metrics.
* Enabled re-throwing ESM import errors of `newrelic.js` so that the user is informed to rename it to `newrelic.cjs`
* Fixed an issue with mongodb instrumentation where IPv6 address([::1]) was not getting mapped to localhost when setting the …
> Release v9.1.0 Redux

- lib/collector/remote-method.js
- test/unit/collector/remote-method.test.js
* Added supportability metric of `Supportability/Nodejs/Collector/MaxPayloadSizeLimit/<endpoint>` when `max_payload_size_in_bytes` configuration value is exceeded.
Closes NEWRELIC-3938
I brought up during a review of spec that this metric was a may but other language implied it should be a must.  The [spec](https://source.datanerd.us/agents/angler/pull/370) has been changed so I added this metric.
> Add Supportability/Nodejs/Collector/MaxPayloadSizeLimit/<endpoint>

- .eslintrc.js
- esm-loader.mjs
- lib/esm-shim.mjs
- lib/shimmer.js
- test/.eslintrc.js
- test/lib/esm-helpers.mjs
- test/lib/test-mod-instrumentation.js
- test/lib/test-mod.mjs
- test/unit/esm-instrumentation.test.mjs
- test/unit/esm-loader.test.mjs
* Implemented load hook in ESM loader to provide ability to instrument ESM packages.
Closes NEWRELIC-3768
As you can see our approach to providing the plumbing for instrumenting ESM packages is to rewrite the source code in the load hook to wrap all exported functions in a proxy.  I was able to prove this out by adding a test ESM package and basic instrumentation.
> Added plumbing for ESM instrumentation

- esm-loader.mjs
- test/unit/esm-loader.test.mjs
I hit an issue when trying to use the new hook to instrument ESM which does not exist in the unit tests because it doesn't actually rely on the `--experimental-loader` hook.  If we had versioned tests at the time I change this it would've caught the bug.  
```sh
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "newrelic/esm-loader.mjs 'load'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
```
> restore shortCircuit on load hook to prevent crash in loader

- lib/config/default.js
* Increased the default limit of custom events from 1,000 to 30,000. 
* Closes https://issues.newrelic.com/browse/NR-54396
* Funny, the spec said we were at 10k, but that old limit is clearly just 1k.
> defaults: raise custom events limit to 30k

- bin/run-versioned-tests.sh
I merged #1371 and the CI on main failed with
```sh
<--- Last few GCs --->
[54885:0x150028000]   767040 ms: Mark-sweep 4043.2 (4138.5) -> 4036.7 (4138.4) MB, 1502.2 / 0.0 ms  (average mu = 0.109, current mu = 0.015) allocation failure; scavenge might not succeed
[54885:0x150028000]   768543 ms: Mark-sweep 4045.7 (4143.6) -> 4040.5 (4142.4) MB, 1488.7 / 0.0 ms  (average mu = 0.061, current mu = 0.009) allocation failure; scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0x100e1bedc node::Abort() [/Users/revans/.nvm/versions/node/v18.6.0/bin/node]
2: 0x100e1c064 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) …
```
> skip running versioned tests with c8 when not --major

- api.js
- lib/instrumentation/bunyan.js
- test/unit/api/api-record-log-events.test.js
- test/unit/api/stub.test.js
Some tests also added.
* Added an API for enqueuing application logs for forwarding 
```js
newrelic.recordLogEvent({ message: 'hello world', level: 'info' })`
```
**Note**: If you are including a serialized error make sure it is on the `error` key of message: 
```js
const error = new Error('testing errors'); 
newrelic.recordLogEvent({ message: 'error example', level: 'error', error })
```
closes NEWRELIC-4484
closes NEWRELIC-4485
* This should behave identically as normal application log forwarding with respect to configuration and metrics. A new metric has been added that counts the number of times this API function is called.
> NEWRELIC-4484 NEWRELIC-4485: implement API for enqueing logs and metrics

- .github/workflows/ci-workflow.yml
- .github/workflows/notify-release.yml
- .github/workflows/post-release.yml
- .github/workflows/prep-release.yml
- .github/workflows/publish-branch.yml
- .github/workflows/release-creation.yml
- .github/workflows/repolinter.yml
- .github/workflows/smoke-test-workflow.yml
- .github/workflows/test-specific.yml
I just happen to notice this while waiting for the [agent to be released](https://github.com/newrelic/node-newrelic/actions/runs/3315379709).
Github actions removed [Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) as a runner.  This PR fixes all instances that rely on Node.js 12.
> update actions that are using deprecated node 12

- .github/workflows/ci-workflow.yml
- .github/workflows/versioned-coverage.yml
Follow up from #1385 
There were a couple of late breaking requests for the original codecov implementation, so this PR addresses them
1. Move Async Local Context tests out into own GHA step, they're a bit flaky and having them lumped with the others means that re-runs take forever
2. Only run versioned tests on Async Local Context, as our integration/unit tests for Async Local Context are already dealt with by the original runs
3. Added a "cron" like job to run 4/5am eastern to gather coverage of versioned tests from the `main` branch, as we can only gather coverage for versioned tests with the `--major` flag due to c8 OOM'ing with the `--minor` flag
> NR-57994 Requested changes for code coverage collection

- lib/config/default.js
* Increased the default limit of custom events from 1,000 events per minute to 3,000 events per minute. In the scenario that custom events were being limited, this change will allow more custom events to be sent to New Relic. There is also a new configurable maximum limit of 100,000 events per minute. To change the limits, see the documentation for [custom_insights_events](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#custom_events_max_samples_stored). To learn more about the change and how to determine if custom events are being dropped, see our Explorers Hub post.
Closes NR-54396
> NR-54396 updated default limit of custom events from 1k to 3k

- .github/workflows/versioned-coverage.yml
Just in case we need to manually sync the versioned code coverage from main, adds the correct github hook to facilitate manually generating main versioned test coverage
> NR-57994 add manual way to invoke main coverage

- test/unit/environment.test.js
Replaced async lib with async functions
Replaced fs with fs/promises
Replaced rimraf with fs/promises
In environment unit test: 
* Replaced async lib with async functions
* Replaced fs with fs/promises
* Replaced rimraf with fs/promises
https://issues.newrelic.com/browse/NR-39257
> Drop async lib from environment unit test

- .github/workflows/post-release.yml
- .github/workflows/release-creation.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Updated a few workflows that relied on set-output, an action that is now deprecated in GHA.
> removed set-output as it is deprecated

- lib/shim/shim.js
This is a slight tweak but important when profiling the agent.  We are trying to determine why async local storage uses more CPU than legacy/promise context manager and this function is in the hot path and currently an anonymous arrow function. It makes it difficult to easily identify this when looking at flame graphs, heap dumps, etc.
> add name to callback function in shim runInContext

- lib/config/default.js
- lib/instrumentation/grpc-js/grpc.js
- test/versioned/grpc-esm/client-unary.tap.mjs
- test/versioned/grpc-esm/server-unary.tap.mjs
- test/versioned/grpc/client-bidi-streaming.tap.js
- test/versioned/grpc/client-server-streaming.tap.js
- test/versioned/grpc/client-streaming.tap.js
- test/versioned/grpc/client-unary.tap.js
- test/versioned/grpc/server-bidi-streaming.tap.js
- test/versioned/grpc/server-client-streaming.tap.js
- test/versioned/grpc/server-streaming.tap.js
- test/versioned/grpc/server-unary.tap.js
* Added new configuration option: `grpc.ignore_status_codes`
* NEWRELIC-5072
* By default, this ignores nothing. In the future, we might decide to add some status codes to be ignored by default. A likely candidate seems status code 5: NOT FOUND.
> NEWRELIC-5072: add `grpc.ignore_status_codes` config option

- lib/config/default.js
Closes NEWRELIC-5277
I extracted common logic in build config to a single assignConfigValue function. Since I was in here I addressed all the jsdoc linting warnings too.
> NEWRELIC-5277 refactored buildConfig to be less complex, addressed all jsdoc warnings within file

- test/versioned/restify/restify-post-7/restify.tap.js
- test/versioned/restify/restify-post-7/router.tap.js
* Update our versioned tests to support Restify 9.0.0
Closes NEWRELIC-5370
[Release Notes](https://github.com/restify/node-restify/releases/tag/v9.0.0)
[Migration Guide](https://github.com/restify/node-restify/blob/master/docs/guides/8to9guide.md)
[Re-Routing with next() removal](https://github.com/restify/node-restify/pull/1847)
Two major changes that effected our tests
1. If using a callback for definitions, the function signature MUST have req, res, and next (arity 3)
2. Using `next('my-route')` to perform re-routing is no longer supported and has been removed
> NEWRELIC-5370 Update versioned tests to support restify@9.0.0

- lib/instrumentation/@hapi/hapi.js
- test/versioned/hapi/capture-params.tap.js
- test/versioned/hapi/ignoring.tap.js
- test/versioned/hapi/render.tap.js
- test/versioned/hapi/router.tap.js
- test/versioned/hapi/vhost.tap.js
Closes NEWRELIC-5285
The versioned tests were still using deprecated methods like `deepEqual` so I fixed this.  The hapi instrumentation complexity was resolved by moving all functions to be at the root of file and pass in proper context.
> Address cognitive complexity in hapi instrumentation

- api.js
* added `noticeError` example for our API docs
* Closes NEWRELIC-4459
Just a quick example using a simple extra attribute. Need to also update docs-website to either point to or to replicate this example.
> NEWRELIC-4459: added noticeError example

- lib/errors/error-collector.js
* refactored Error Collector to reduce complexity and fixed/added JSDocs
Closes NEWRELIC-5279
* Updated error collector to reduce cognitive complexity
* Fixed existing jsdoc issues and added jsdocs for new methods
> NEWRELIC-5279 refactored Error Collector to reduce complexity

- lib/util/deep-equal.js
* Updated deep equality check to use native `util.isDeepStrictEqual()`
Closes NEWRELIC-5304
* Replaced the custom deep equality function with Nodejs' `util.isDeepStrictEqual`, which has been available since Node v9. Added a specific check for comparing `NaN`, as the original functionality (and JS in general) treats them as NOT equal, but `util.isDeepStrictEqual` does, this is to maintain the existing logic of the check.
> NEWRELIC-5304 Use native deep equal functionality

- THIRD_PARTY_NOTICES.md
- lib/instrumentation/director.js
- lib/shim/shim.js
- lib/shim/webframework-shim.js
- lib/symbols.js
- lib/util/code-level-metrics.js
- package-lock.json
- package.json
- test/unit/util/code-level-metrics.test.js
- test/versioned/express/segments.tap.js
- third_party_manifest.json
* Attached code level metrics attributes to middleware spans when `config.code_level_metrics.enabled` is true.
Closes NEWRELIC-5564
This code will solve all the web frameworks we want to attach CLM metrics for.  Basically any instrumentation that uses `shim.recordMiddleware` will flag the middleware function as CLM available. Then when the middleware function actually gets called it will get the function metadata and add it as attributes on the segment.
I only added versioned tests assertions for express but this will work for all other frameworks and we have tickets to add those corresponding tests.  To verify this doesn't break instrumentation you can run
```sh
NEW_RELIC_CODE_LEVEL_METRICS_ENABLED=true npm run versioned
```
Note: There will be 1 failure(express/segments) as there's a …
> CLM support for all middleware 

- test/versioned/restify/restify-post-7/package.json
* Added a new test stanza to run restify >=10 on Node 18.
Closes NR-33669
On versions 14 and 16, restify 10 was already getting run
```sh
Folder: restify-post-7
* restify(4): 7.7.0, 8.6.1, 9.0.0, 10.0.0
* express(1): 4.16
* restify-errors(1): 6.1.1
```
However, due to issues with restify 9 on Node 18 we had to skip it.  Now we can unleash it again for Node 18 🎉
> Node 18 restify tests

- lib/environment.js
- lib/util/async-each-limit.js
- test/unit/util/async-each-limit.test.js
* Reintroduced throttled reading of dependency tree at startup to prevent EMFILE issues
Closes NR-69739
In [9.0.1](https://github.com/newrelic/node-newrelic/pull/1325/files#diff-24984142d58a41889c987b60103bcd93653f3551f71f6cdf22b5762e885c9cd6L86), we removed the async library as a dependency because as a group we did not like how confusing it was to read. An unfortunate side effect is that we removed throttling the dependency lookups at start-up. This meant that customers could run into EMFILE issues, as shown in the GTSE attached to the JIRA ticket mentioned above.
I also did some JSDoc cleanup in the environment file while I was in there
> NR-69739  Reintroduced throttled reading of dependency tree

- lib/instrumentation/grpc-js/grpc.js
* Updated `@grpc/grpc-js` instrumentation to work with 1.8.0.
Closes NEWRELIC-5771
Looks like a [big refactor](https://github.com/grpc/grpc-node/pull/2243/files) occurred and moved the class we instrument to a new file and class name `src/resolving-call.ResolvingCall.prototype.start`.  It also changed the property for the grpc method to be `method` not `methodName`. All is well again.
> grpc 1.8.0 support

- lib/util/code-level-metrics.js
The *Once family of logging functions need a key to know what to only report once. This string key should be the first parameter.
https://github.com/newrelic/node-newrelic/blob/df3e611c578ab2227f0ace2a8996c5a2d7137762/lib/util/logger.js#L118
> code-level-metrics: fix invocation of infoOnce

- test/integration/distributed-tracing/trace-context-cross-agent.tap.js
- test/lib/cross_agent_tests/distributed_tracing/trace_context.json
This was brought up by other language devs, [see](https://newrelic.slack.com/archives/C119L74HL/p1670886634677689).  It's a confusion thing in that we attach tracing vendors on the root span as tracingVendors not vendors.  To avoid making some assumptions about assertion data, the proposal was to update the array name to be `tracingVendors`. It was more involved in our testing harness as it used that key in a case to assert it in the tracestate.  Since the keys are camel cases for consistency in asserting(no idea why we did this), but as you can see I had to update in a few places.  Take note, no agent code is changed.
> Update DT cross agent tests

- lib/util/code-level-metrics.js
- test/unit/util/code-level-metrics.test.js
* Added a check to the code level metrics utility to ensure filePath was set before adding the `code.*` attributes.
I discovered this crash thus getting into the catch when running with an express app and code level metrics.  It turns out when you bind a function it loses all the function metadata thus making our lookup useless. You can see where this occurs in the [express router.route](https://github.com/expressjs/express/blob/master/lib/router/index.js#L509).
> CLM: Handle binding functions

- api.js
- test/unit/rum.test.js
* Update `getBrowserTimingHeader` to allow Browser Agent to be generated even when not in a Transaction by adding `allowTransactionlessInjection` to function options. `allowTransactionlessInjection` is a boolean option, and when set to `true`, will allow injection of the Browser Agent when not in a transaction. Note that if you are using this option, you may need to wait until the Node agent has established a connection before calling `getBrowserTimingHeader`. To wait until the agent is connected, you can add the following check to your code: 
```js
if (!newrelic.agent.collector.isConnected()) {
await new Promise((resolve) => {
newrelic.agent.on('connected', resolve)
})
}
```
Closes https://github.com/newrelic/newrelic-node-nextjs/issues/99
This has been a source of pain for users in a …
> NEWRELIC-6167 Update `getBrowserTimingHeader` to inject Browser Agent regardless of transaction availability

- lib/instrumentation/winston.js
- test/versioned/winston/winston.tap.js
There is a different part of the Winston API that our current instrumentation simply misses. It's possible to create a logger by directly calling `createLogger`, but it's also possible to add new loggers to the list of loggers by doing `winston.loggers.add` with almost the same syntax.
This factors out a bit of the logic so that both methods of creating winston loggers are instrumented.
* Instrumented `winston.loggers.add` so it works like `winston.createLogger`.
* Closes NEWRELIC-6211
> NEWRELIC-6211: (winston) also instrument winston.loggers.add

- THIRD_PARTY_NOTICES.md
- lib/utilization/gcp-info.js
- package-lock.json
- package.json
- test/integration/pricing/system-info.tap.js
- test/integration/pricing/vendor-info-tests.js
- test/lib/cross_agent_tests/utilization/utilization_json.json
- test/lib/cross_agent_tests/utilization_vendor_specific/gcp.json
- third_party_manifest.json
Added safety check to enquote GCP IDs the platform reports as numbers. These numbers can be long enough that JS converts them to scientific notation, losing precision. Updated cross-agent test fixtures to expose this, with a new test case for this issue. Closes NR-80407
https://issues.newrelic.com/browse/NR-80407
> Preserving GCP IDs that come in as numbers

- lib/config/default.js
- lib/config/index.js
- test/unit/config/config-env.test.js
* NEWRELIC-6379
The agent seems like the right place to have this sort of logic, similar to the logic for hitting the ordinary NR collector endpoint.
> NEWRELIC-6379: (config) enable otlp_endpoint config item

- lib/collector/facts.js
- lib/instrumentations.js
- lib/metrics/names.js
- lib/shim/constants.js
- lib/shimmer.js
- test/integration/module-loading/module-loading.tap.js
- test/integration/module-loading/node_modules/@prisma/client/index.js
- test/integration/module-loading/node_modules/@prisma/client/package.json
- test/unit/facts.test.js
* Add a new tracking type of instrumentation.  This will be responsible for logging `Supportability/Features/Instrumentation/OnResolved/<pkg>` and `Supportability/Features/Instrumentation/OnResolved/<pkg>/Version/<version>` metrics when packages are required.
Closes NEWRELIC-6384
I plan on updating angler to start collecting these new metrics.  These new metrics will be used to track how many customers are requiring packages that have otel instrumentation but also logging libraries to properly track usage.  The previous metrics for logging were loaded when a dependency existed in the package.json.
> Add new tracking type instrumentation 

- lib/config/default.js
- lib/config/formatters.js
- lib/config/index.js
- lib/instrumentation/core/http-outbound.js
- lib/instrumentation/core/http.js
- lib/transaction/trace/index.js
- lib/util/urltils.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-env.test.js
- test/unit/config/config-formatters.test.js
- test/unit/instrumentation/http/http.test.js
- test/unit/instrumentation/http/outbound.test.js
- test/unit/trace.test.js
- test/unit/urltils.test.js
* Added support for `url` obfuscation using regex:
* for distributed tracing 
* incoming and outgoing requests `path` obfuscation
* transaction `request.url` attribute obfuscation
* span `http.uri` path obfuscation
* for transactions
*  transaction trace details `url` obfuscation
An example config looks like this:
```js
url_obfuscation: {
enabled: true,
regex: {
pattern: /(\/api\/v1\/users\/)([\d]+)(\/.*$)/,
flags: "i",
replacement: '$1**$3'
} 
}
```
This would turn `/api/v1/users/12345456/edit` to `/api/v1/users/**/edit`
Or using env vars:
```yml
NEW_RELIC_URL_OBFUSCATION_ENABLED: "true",
NEW_RELIC_URL_OBFUSCATION_REGEX_PATTERN: '/(\/api\/v1\/users\/)([\d]+)(\/.*$)/',
NEW_RELIC_URL_OBFUSCATION_REGEX_FLAGS: 'i',
NEW_RELIC_URL_OBFUSCATION_REGEX_REPLACEMENT: '$1**$3'
```
Adds the ability to …
> Obfuscate url paths for distributed tracing and transactions

- lib/serverless/api-gateway.js
- test/unit/serverless/aws-lambda.test.js
* Fixed error with Lambda/ALB serverless instrumentation when no response headers were included
Fixes #1503 / NEWRELIC-6805
When we updated to support multivalue headers/query params in #1489, we overlooked the scenario where there are no headers at all (which is possible with the response case), which caused the `Object.entries()` call to throw. Now, we'll first check to see if we have any headers at all to normalize, if not, then exit early.
> fix: update normalizeHeaders to gracefully handle no headers

- .github/workflows/publish-branch.yml
I'm not sure if we ever use this but it is using a repo only npm token. I updated to use our org level token.
> updated publish-branch to use org level npm token

- .github/workflows/ci-workflow.yml
- .github/workflows/versioned-coverage.yml
We discussed this in planning.  The async local versioned tests haven't caught anything.  It is safe to run these less frequently to boost the CI time on PRs and main runs.  I filed a [ticket](https://issues.newrelic.com/browse/NEWRELIC-7153) to move this to CI as the default in v10 when we drop the legacy context manager.
> moved the async local versioned test to nightly job to cut down on runtimes of PR/main CI

- lib/instrumentation/@prisma/client.js
- test/unit/instrumentation/prisma-client.test.js
Closes NEWRELIC-7171
* updated prisma instrumentation to work with version 4.11.0.  
* I also added more defensive code to avoid future crashes with instrumentation if prisma internals change.
* lock down min version of instrumentation to 4.0.0
Tested this with #1522 from 4.0.0 to 4.11.0
```sh
✓ prisma (100) 8m
===============================================================
Versions executed
Folder: prisma
* @prisma/client(10): 4.0.0, 4.1.1, 4.2.1, 4.4.0, 4.5.0, 4.6.1, 4.8.1, 4.9.0, 4.10.1, 4.11.0
* prisma(10): 4.0.0, 4.1.1, 4.2.1, 4.4.0, 4.5.0, 4.6.1, 4.8.1, 4.9.0, 4.10.1, 4.11.0
===============================================================
PASS
real	8m33.275s
user	4m52.602s
sys	1m20.720s
513.27 real       292.60 user        80.72 sys
```
> fix prisma instrumentation

- test/versioned/prisma/prisma/schema.prisma
Trying to fix the prisma test run on `main`.
> NEWRELIC-7174: (prisma) add a binary target to the schema

- lib/instrumentation/@prisma/client.js
- lib/shim/shim.js
- lib/symbols.js
- test/unit/instrumentation/prisma-client.test.js
- test/unit/shim/shim.test.js
- test/versioned/prisma/prisma.tap.js
- test/versioned/prisma/utils.js
* Updated prisma instrumentation to support the capturing of SQL Traces.
Closes NEWRELIC-7174
I removed some logic that parsed that table from the database.  All of our other instrumentation keeps that in tact, so `schema.table` was parsed to `table` but is now back to `schema.table`.  Also in capturing sql traces for prisma model calls the query will just be `<model>.<action>` (i.e. users.findMany).  The more important thing in traces is the backtrace that will locate the line it exists for customers to identify it.
> Add collecting sql traces for Prisma

- test/versioned/prisma/package.json
- test/versioned/prisma/prisma.tap.js
- test/versioned/prisma/prisma/schema.prisma
- test/versioned/prisma/prisma/seed.js
It seems like just adding the `debian-openssl-3.0.x` didn't fix issue. Instead you had to add the schema/seed as npm scripts.  You can see [here](https://github.com/bizob2828/node-newrelic/actions/runs/4348134972) that the versioned tests pass in all versions
> fixed prisma versioned tests to properly work across all supported versions

- api.js
- lib/errors/error-collector.js
- lib/errors/helper.js
- lib/errors/index.js
- lib/transaction/index.js
- test/unit/errors/error-collector.test.js
- test/unit/errors/expected.test.js
* Added ability to mark errors as expected when using `newrelic.noticeError`.
https://issues.newrelic.com/browse/NEWRELIC-7045
Closes NEWRELIC-7045
> Add expected boolean to noticeError

- api.js
- test/unit/api/api-set-user-id.test.js
- test/unit/api/stub.test.js
* Added an API method `setUserID` to provide an ability to associate a unique identifier with a transaction event, transaction trace and errors within transaction.  The attribute will be `enduser.id`.  
Closes NEWRELIC-7538
>  added setUserID api method

- lib/shimmer.js
* https://issues.newrelic.com/browse/NEWRELIC-7414
* https://github.com/newrelic/node-test-utilities/pull/162
This is an enhancment to support the [Test utils PR](https://github.com/newrelic/node-test-utilities/pull/162).  We need to provide an ability to register core and 3rd party instrumentation separately now that we will work towards supporting the ability to register multiple instrumentation hooks for a given module.
> NEWRELIC-7414 separated out the ability to register core and 3rd party instrumentation

- api.js
- lib/errors/error-collector.js
- lib/errors/index.js
- test/integration/api/set-error-group-callback.tap.js
- test/unit/api/api-set-error-group-callback.test.js
- test/unit/api/stub.test.js
- test/unit/errors/error-group.test.js
Added new API function called `setErrorGroupCallback`, which provides a way for you to customize the `error.group.name` attribute of errors that are captured by the agent. This attribute controls how the Errors Inbox functionality groups similar errors together.
To learn more about this function, please refer to our [example app](https://github.com/newrelic/newrelic-node-examples).
Closes NEWRELIC-7541
Example app PR: https://github.com/newrelic/newrelic-node-examples/pull/59
> feat: add ability to customize Error Groups

- documentation/function-wrapping.md
- test/smoke/index/index-bad-version.tap.js
In #1566 I restored the agent on require.cache as `__NR_cache` and removed the `symbols.cache`.  I forgot to update docs and a smoke test.
> updated docs and smoke tests that were still referencing symbols.cache

- .eslintrc.js
- lib/transaction/index.js
* Fixed issue causing `Accessing non-existent property 'Exception' of module exports inside circular dependency` Node.js warning
The `Exception` import introduced in #1569 was causing the following error on `main`, removed it since it was only used for jsdoc typings and updated our ESLint config to allow Exception in jsdocs without the import. Additionally, this issue only affects `main`, we never published a package with the offending code.
```(node:98030) Warning: Accessing non-existent property 'Exception' of module exports inside circular dependency```
> fix: remove Exception import to resolve Node warning

- lib/config/default.js
- lib/config/index.js
- test/unit/facts.test.js
* Added a new configuration option `heroku.use_dyno_names` to specify whether or not to use `process.env.DYNO` for naming the host name and display host.  This option defaults to true.  If you are on heroku and do not want this functionality set `heroku.use_dyno_names` to `false`.  You can also control this configuration options with the environment variable of `NEW_RELIC_HEROKU_USE_DYNO_NAMES`.
Thanks @benney-au-le  for your contribution 🚀 
Closes #1536 
The Ruby agent reports the Heroku dyno name as the hostname (for example, web.1). This allows you to view your data scoped to a particular dyno name. You can disable this behavior by setting the heroku.use_dyno_names setting to false. The agent will then use a single aggregated placeholder name called Dynamic Hostname.
Add the same …
>  Report hostname on heroku as dyno name

- .github/dependabot.yml
Closes NR-96231
Added `dependabot.yml` to configure the commit message prefixes for Dependabot updates. With this change, updates to production deps will be prefixed with `security`, and dev dependency updates will be prefixed with `chore`. Note that the dependabot code itself handles the adding of `:` (which can be seen [here](https://github.com/dependabot/dependabot-core/blob/main/common/spec/dependabot/pull_request_creator/pr_name_prefixer_spec.rb#L248)). Additionally, `include_scope` ensures that the dep name and versions are included in the commit message.
Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
There is currently no way to validate that the configuration is correct due to this …
> chore: Add dependabot configuration file to configure conventional commits

- .github/dependabot.yml
We've turned off this functionality in Snyk, and I accidentally enabled this functionality in Dependabot as part of #1580, so updating the Dependabot configuration to only do security updates a la https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
> ci: disable dependabot version updates

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
Our Apollo/graphql versioned tests started failing last night, because a recently merged PR https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/243 relies on a new function from our test utilities that wasn't currently available with the version we install in the agent. This PR bumps the version of test utilities to have the newer functionality.
> ci: bump the test utils version to get new makeFullyInstrumented function

- lib/config/default.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-server-side.test.js
…s with all other agents. In fact this PR was lost in the shuffle from GHE to GitHub.com https://source.datanerd.us/NodeJS-agent/nodejs_agent/pull/1982/files
* **BREAKING** - Updated the default of `config.transaction_tracer.record_sql` from `off` to `obfuscated`.  
I noticed this when I was working on prisma instrumentation, and did some spelunkeing.  I found this [PR](https://source.datanerd.us/NodeJS-agent/nodejs_agent/pull/1982), that got lost during the move from GHE to GitHub.com back in April of 2020.  The change gets up compliant with the agent spec.  However, this change is breaking.  I just wanted to open the PR and assign label so we can talk about it.  We may want to let this sit until we release our next semver major v10.
> DO NOT MERGE - set transaction_tracer.record_sql default to obfuscated

- lib/serverless/aws-lambda.js
- lib/shim/shim.js
- lib/shim/webframework-shim.js
- lib/transaction/index.js
- test/unit/shim/shim.test.js
- test/unit/shim/webframework-shim.test.js
- test/unit/transaction.test.js
- test/versioned-external/external-repos.js
- test/versioned/express/captures-params.tap.js
- test/versioned/express/router-params.tap.js
- test/versioned/hapi/capture-params.tap.js
- test/versioned/hapi/router.tap.js
- test/versioned/hapi/vhost.tap.js
- test/versioned/restify/restify-post-7/capture-params.tap.js
- test/versioned/restify/restify-post-7/router.tap.js
- test/versioned/restify/restify-pre-7/capture-params.tap.js
- test/versioned/restify/restify-pre-7/router.tap.js
* **BREAKING** - Route (URL) parameters are now stored as `request.parameters.route.*` attributes on Transactions and Spans
* **BREAKING** - Removed `captureUrlParams` from `WebFrameworkShim` class
* Closes #1574 
* [PR](https://github.com/newrelic/newrelic-node-nextjs/pull/117) to update Next.js instrumentation and tests
This breaking change fixes two issues with storing request parameter related attributes:
1. Reserved attribute name collisions on spans - Reported issue, `id` is a reserved attribute name for Distributed Tracing, and spans were getting the bare route parameters added as attributes which, in conjunction with the flattening of data that occurs when we send over the wire, caused the DT parent/child span association to break.
2. Collisions between query parameters and route …
> DO NOT MERGE - Route/URL parameters are now stored on request.parameters.route.* attributes

- esm-loader.mjs
- lib/instrumentation/@hapi/vision.js
- lib/instrumentation/mysql/mysql.js
- lib/instrumentation/mysql/nr-hooks.js
- lib/shim/conglomerate-shim.js
- lib/shim/datastore-shim.js
- lib/shim/index.js
- lib/shim/message-shim.js
- lib/shim/promise-shim.js
- lib/shim/shim.js
- lib/shim/transaction-shim.js
- lib/shim/webframework-shim.js
- lib/shimmer.js
- lib/symbols.js
- test/integration/api/TestMod.js
- test/integration/api/instrument.tap.js
- test/integration/module-loading/module-loading.tap.js
- test/lib/agent_helper.js
- test/unit/api/api-instrument-loaded-module.test.js
- test/unit/esm-loader.test.mjs
- test/unit/metric/datastore-instance.test.js
- test/unit/shim/datastore-shim.test.js
- test/unit/shim/message-shim.test.js
- test/unit/shim/shim.test.js
- test/unit/shim/webframework-shim.test.js
- test/unit/shimmer.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
- test/versioned-external/external-repos.js
* Added the ability to register instrumentation multiple hooks (onRequire, onResolved) for the same resolved moduleName.
* This has been a limitation of the agent from the beginning.  If a customer used the api to instrument `api.instrument`, `api.instrumentDatastore`, `api.instrumentWebframework`, `api.instrumentMessages`, or `api.instrumentConglomerate`, it would override existing instrumentation hooks.  The effect was that the Node.js agent would not function as designed.  
* **DEPRECATION NOTICE**: `shim.unwrap` and `shim.unwrapOnce` will no longer function if you attempt to unwrap an item that has been wrapped multiple times.
* This is because since we now allow instrumenting the same module more than once, you cannot safely unwrap without breaking all registered instrumentation.  We …
> DO NOT MERGE - Allow registering multiple instrumentation hooks for the same resolved module

- .github/workflows/ci-workflow.yml
- .github/workflows/release-please.yml
- .github/workflows/update-snyk-prs.yml
- bin/add-support-statement.js
- bin/test/add-support-statement.test.js
- bin/test/update-snyk-pr.test.js
- bin/update-snyk-pr.js
Closes NR-96232
Updates any PR that is generated by [Snyk Bot](https://github.com/snyk-bot) to add a `security:` prefix to the title. Snyk does not give us a way to configure the commit message or customize anything about the PR like Dependabot does, so since we're going to eventually update the PR process to use squash/merge with the PR title as the commit message, this (in a roundabout way) gets our Snyk PRs to be "conventional", and ensure that they end up in the appropriate release notes section.
> ci: update Snyk generated PR titles to have a Conventional Commit prefix

- .github/workflows/validate-pr.yml
Closes NR-96233
Added a check to ensure that a PR title matches our Conventional Commit requirements, and if not, adds a comment to the PR listing our allowed prefixes. Note that we'll have to disable this workflow until we're ready to migrate to the new release flow.
**Comment Example**
> ci: added PR title check automation

- bin/run-versioned-tests.sh
- lib/instrumentation/@nestjs/core.js
- lib/instrumentations.js
- lib/shim/webframework-shim.js
- test/unit/instrumentation/nest.test.js
- test/versioned/nestjs/nest.tap.js
- test/versioned/nestjs/package.json
- test/versioned/nestjs/setup.js
- test/versioned/nestjs/test-app-replacements/app.controller.ts
- test/versioned/nestjs/test-app-replacements/main.ts
* Added support to record Nest.js error stack traces.
* NEWRELIC-8072
We instrument `BaseExceptionFilter.handleUnknownError`, which gets called whenever Nest.js throws a 500. This is how Nest.js swallows exceptions, so it seems like a natural hook point.
> feat(nestjs): capture stack traces NEWRELIC-8072

- .github/workflows/post-release.yml
Restored v prefix for getting version tag in post-release job to create docs PR
https://issues.newrelic.com/browse/NR-96240
> fix: Restored v prefix to version in docs PR job

- .c8rc.json
- .github/workflows/versioned-coverage.yml
- bin/run-versioned-tests.sh
* refactor (run-versioned-tests.sh): added ability to run versioned tests and skip collecting coverage by passing in `C8` env var to the job.
* Updates `.c8rc.json` to remove redundant html reporter as lcov does both lcov and html.
I did this work in #1617 but that is not merging to main right away. I wanted to get these changes in.
> refactor(run-versioned-tests.sh): added ability to run versioned tests and skip collecting coverage by passing in `C8` env var to the job.

- test/versioned/prisma/package.json
Prisma Client 4.14.0 changed how the library configuration functions and removed some functions we instrument. This pins prisma down to 4.13.0 until we can fix the instrumentation in https://github.com/newrelic/node-newrelic/issues/1632
> test: pin prisma to < 4.14.0 until we fix instrumentation

- lib/config/index.js
- test/unit/config/config.test.js
This change broke the smoke tests.
Added a test to make sure we exercise this change.
> fix(config): revert changes to lib/config/index.js

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
We have to pin `testdouble` until we drop support for node 14. [3.18.0](https://github.com/testdouble/testdouble.js/blob/main/CHANGELOG.md#3180) release added support for Node 20 which even though it doesn't call it out dropped support for 14 and it's breaking our esm unit tests.
> chore: pin testdobule to 3.17.2 as 3.18.0 no longer works on node 14

- .github/workflows/post-release.yml
- bin/create-docs-pr.js
Changed post-release create-docs-pr job to use the machine user username/email, and removed the fork syntax from the docs PR.
[NR-96240](https://issues.newrelic.com/browse/NR-96240)
> fix: Set username/email to machine user by default

- THIRD_PARTY_NOTICES.md
- lib/instrumentation/@prisma/client.js
- package-lock.json
- package.json
- test/unit/instrumentation/prisma-client.test.js
- test/versioned/prisma/package.json
- test/versioned/prisma/prisma.tap.js
- third_party_manifest.json
* Updated prisma instrumentation to parse the schema to obtain database connection information.
* The function `getConfig` on the engine is no longer available in 4.11.0+ of `@prisma/client`.
Closes #1632
I weighed many options and this is our best option instead of building our own tokenizer with the library that `@mrleebo/prisma-ast` uses `chevrotain`.  The prisma package is called `@prisma/internals` but has a ton of dependencies and I didn't think it was appropriate to pull that in just to use the getConfig function.  In fact their code is written in rust fo this and exposed via a wasm module.  You can trace it all from [here](https://github.com/prisma/prisma/blob/main/packages/internals/src/engine-commands/getConfig.ts#L82).
> fix: updated prisma instrumentation to properly parse database connection strings that work across all versions of prisma

- .github/workflows/prep-release.yml
- .github/workflows/prepare-release.yml
- bin/.eslintrc.js
- bin/conventional-changelog.js
- bin/create-docs-pr.js
- bin/prepare-release.js
- bin/templates/header.hbs
- bin/test/conventional-changelog.test.js
- bin/test/create-docs-pr.test.js
- bin/test/prepare-release.test.js
Updated the prepare release workflow to accept a new, optional input from workflows. Setting USE_NEW_RELEASE to true in a given repo's actions variables configuration will cause the workflow to use the new Conventional Commit based release notes. This flag is set to false by default, which will allow our external repos to slowly be migrated over without interruption.
Closes NR-96236
When `USE_NEW_RELEASE` is set, prepare-release has been enhanced to use previous work around conventional commit parsing / changelog generation. Additionally, the docs-website script has also been enhanced to use conventional commits all the time now. I believe this is a safe enough change because create-docs-pr is only used in this repo, whereas prepare-release is used in all repos.
To test this, do the …
> ci: add --use-new-release functionality

- .github/workflows/prep-release.yml
Discovered during first release attempt, I missed including a required `type` field
https://github.com/newrelic/node-newrelic/actions/runs/4962480712/workflow
> ci: fix issue with missing type in the prep-release

- .github/workflows/prep-release.yml
Updated prep-release to use a string instead of a boolean. The variables come in from Github as strings, so a boolean check is incorrect. Instead, we now do a check to see if it's defined, and if so, set `--use-new-release` on the CLI
> ci: update to conditionally add CLI flag to prep-release

- .github/workflows/prep-release.yml
This is necessary in order to get the tag history, which we require to determine commits that have occurred between this new version and the previous version
[Tested against my fork](https://github.com/jmartin4563/node-newrelic/actions/runs/4981959889/jobs/8916950685), confirmed that it got to the point where it was committing files (at which point it failed because secrets)
> ci: update prep-release to fetch entire history of caller repo

- lib/instrumentation/mysql/mysql.js
- test/versioned/mysql/basic-pool.tap.js
- test/versioned/mysql/helpers.js
- test/versioned/mysql2/basic-pool.tap.js
**Note**: We need to add more information to the commit description on squash and merge to call out the fact we also instrument Poolnamespace.prototype.query now too.
This PR fixes the `setup` helper method in mysql by running before the agent instrumentation is loaded and busts the require cache.  This was found to hide the root cause of this PR which was a mistake on a symbol defaulting to true.  By fixing setup it also exposed an issue with PoolNamespace.prototype.query where it isn't getting instrumented thus some failing tests.  
Restore [this bit flip](https://github.com/newrelic/node-newrelic/pull/1647/files#diff-a19b1a5fade2ea9928d9a753cbf0fe66c12e4b9a912250f11b7c5cd7aa5e07d0L14), and the tests should fail
Closes #1645
> fix: Updated mysql instrumentation to properly wrap the connection pool.getConnection and poolCluster.of

- lib/instrumentation/mysql/mysql.js
- test/unit/instrumentation/mysql/describePoolQuery.test.js
- test/unit/instrumentation/mysql/describeQuery.test.js
- test/unit/instrumentation/mysql/extractQueryArgs.test.js
- test/unit/instrumentation/mysql/getInstanceParameters.test.js
- test/unit/instrumentation/mysql/index.test.js
- test/unit/instrumentation/mysql/storeDatabaseName.test.js
- test/unit/instrumentation/mysql/wrapCreateConnection.test.js
- test/unit/instrumentation/mysql/wrapCreatePool.test.js
- test/unit/instrumentation/mysql/wrapCreatePoolCluster.test.js
- test/unit/instrumentation/mysql/wrapGetConnection.test.js
- test/unit/instrumentation/mysql/wrapGetConnectionCallback.test.js
- test/unit/instrumentation/mysql/wrapQueryable.test.js
In the aftermath of #1645, we though it prudent to add additional automated tests to ensure that our use of shim symbols is correct and consistent, as the symbols are heavily used in our logic to determine if something is already instrumented or needs to be instrumented. In order to minimize the amount of code shuffling and room for error, I took the route of updating functions to be part of the export.
Tested via `npm run unit` and also with `npm run versioned:major mysql`
Closes https://issues.newrelic.com/browse/NEWRELIC-4868
> test: added unit tests for MySQL instrumentation

- index.js
- test/integration/logger-test-case/hello.js
- test/integration/logger-test-case/newrelic.js
- test/integration/logger.tap.js
> fix(logger): log execArgs at the debug level

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
* @newrelic/security-agent dependency is updated to its latest version.
* Fix in mysql instrumentation on getConnection to check if callback is wrapped
* Support for fire and forget vulnerability detection
* Snapshot file fixes.
* Handling for high_security config.
Run following command to test.
> feat: Updated @newrelic/security agent to 0.1.1 

- lib/instrumentation/@node-redis/client.js
- test/unit/instrumentation/redis.test.js
Added tests for the different branches of getRedisParams
Closes #1242 
Closes NEWRELIC-4440
> chore: Added test for getRedisParams

- test/unit/db/query-trace-aggregator.test.js
- test/versioned/grpc/package.json
- test/versioned/nestjs/package.json
- test/versioned/redis/package.json
> chore(testing): convert query-test-aggregator tests to tap style

- test/versioned/prisma/package.json
Until we fix #1679, we need to limit our tests to get the build passing.
> chore: temporarily limit prisma tests to non-breaking version

- test/unit/errors/error-event-aggregator.test.js
Updated mocha-style test to tap testing for error-event-aggregator.test.js
Closes #1681 
Closes NEWRELIC-9409
> chore(testing): Converted error-event-aggregator.test.js to tap

- .github/workflows/ci-workflow.yml
There are a few parts to this:
1) First, disable running on pushes. This is because pushes don't have context when they come from a pull request. In particular, pushes don't have the branch name the pull request came from.
2) At the same time, enable running on `synchronize` and `close` actions on `pull_request` events. This will ensure that when a PR gets updated or merged, we'll see a CI run. This changes the default actions of only running on `opened`, `synchronize`, or `reopened`. 
3) Then, disable running if the branch name starts with release.
4) In the same condition check, enable runs only for branches that are closed via a merge. We …
> ci: disable running CI for releases

- lib/instrumentation/@prisma/client.js
- test/versioned/prisma/package.json
Prisma 4.16.0 changed where the query comes from, so let's just make sure we get it from the right place.
Closes #1679
> fix(prisma): check for query args in string property

- test/unit/errors/error-trace-aggregator.test.js
Converted error-trace-aggregator.test.js to use tap instead of mocha.
Closes #1689 
Closes NR-129077
> chore(test): convert error-trace-aggregator.test.js to tap-style

- test/unit/trace.test.js
Added explicit t.end() in test/unit/trace.test.js.
> chore: Added t.end() to trace unit test

- test/unit/trace.test.js
Removed unneeded t.end() calls in trace unit test.
> chore(test): Fixed tap end/autoend use in trace unit test

- .github/workflows/ci-workflow.yml
Updates our `ci-workflow.yml` to use [fkirc/skip-duplicate-actions](https://github.com/fkirc/skip-duplicate-actions) to skip running our test suite when we merge a release PR. This will reduce the amount of human interaction (babysitting) it takes to perform our releases.
We will still run CI for all pull requests to fulfill our required status check requirement, and will not skip any manual invocations of the workflow.
We use `fkirc/skip-duplicate-actions`'s `ignore_path` to detect a release PR, as these PRs only update a specific subset of files, specifically `package.json`, `package-lock.json`, `changelog.json` and `NEWS.md`.
This PR has it disabled to minimize risk/impact, but in the future, this action has a robust duplicate run detection algorithm, which we could leverage in the …
> ci: skip running test suite when merging releases

- test/unit/environment.test.js
Converted tests/unit/environment.test.js to tap-style.
Closes #1703 
Closes NR-139427
> chore(test): converted environment.test.js to tap

- test/unit/errors/error-event-aggregator.test.js
- test/unit/errors/error-trace-aggregator.test.js
- test/unit/errors/expected.test.js
- test/versioned/hapi/errors.tap.js
- test/versioned/ioredis/ioredis-3.tap.js
- test/versioned/ioredis/ioredis.tap.js
- test/versioned/redis/redis.tap.js
Replaced deprecated t.equals assertions in tests with t.equal.
Closes NR-140242
Closes #1710
> chore(test): Replaced t.equals with t.equal

- test/unit/adaptive-sampler.test.js
Converted tests/unit/adaptive-sampler.test.js to tap assertions.
Closes #1706 
Closes NR-139963
> chore(test): Converted adaptive-sampler.test.js to tap

- test/versioned/prisma/package.json
Prisma dropped Node 14 in version 5.  Until we drop 14, we need to prevent our versioned tests from running >=5 on Node 14.  #1715 is also testing if the instrumentation crashes and if we have to do a semver check in instrumentation.  This is just to unblock CI.
> test: pin prisma to < 5 when running on node 14

- .github/ISSUE_TEMPLATE/story.md
> chore: Create story issue template

- lib/instrumentation/core/http.js
- test/unit/instrumentation/http/http.test.js
Changed http to use pathname instead of path, avoiding exposure of query params
Test for this case has been added to tests/unit/instrumentation/http/http.test.js 
Fixes #1718 
Closes NR-141506
> fix: Dropped query params when obfuscating

- lib/config/default.js
- test/unit/config/config-defaults.test.js
- test/unit/shim/webframework-shim.test.js
Enables code level metrics by default
> feat: enable code_level_metrics by default

- esm-loader.mjs
- test/unit/esm-loader.test.mjs
Version 10 of the Node agent added support for instrumenting a module more than once. This had a knock-on effect in our ESM loader in that we were naively calling `registerInstrumentation` every time a CJS module was imported, which in turn, would cause our instrumentation to be registered multiple times if an application `import`-ed a module more than once. This exhibited as route name duplication for transactions in the Express instrumentation / GH issue, but would have caused strangeness with all instrumentation.
To fix, I've added CJS modules to the `registeredSpecifiers` Map after performing instrumentation registration, and added a check to the beginning of the resolve hook logic to not register again if the loader has already performed on a module.
* Added unit test to ensure that …
> fix: prevent ESM loader from loading instrumentation multiple times

- package.json
- third_party_manifest.json
We have to wait until #1725 to update the engines stanza.  Otherwise customers cannot use agent on Node 14. We currently have failing smoke tests on 14 because of this.
> chore: restored engines to >=14 until we actually drop support for Node 14

- bin/create-docs-pr.js
- bin/create-github-release.js
This updates the support statement to standardize on other release not formats. 
See my conversation w/ @mrickard in `#node-agent` for more info
> ci: update support statement

- esm-loader.mjs
- test/lib/test-loader.mjs
- test/unit/esm-instrumentation.test.mjs
- test/unit/esm-loader.test.mjs
We had a report about a potential Remote Code Injection(RCE).  Although technically true the risk of this happening is lower 
than the initial report.  It requires customers to be importing paths with tainted strings and then provide this attack vector.
```js
import express from 'express'
const app = express()
app.get('/', async (request, response) => {
const { lang } = request.query
const { joke } = await import(`./strings/${lang}.mjs`)
response.send(joke)
})
app.listen(7777, () => {
console.log('Listening at http://localhost:7777')
})
```
Note: If `request.query.lang` was never imported as part of path this RCE does not exist.  
1. `npm i express newrelic`
1. Use this sample app above.
1. Create a newrelic config.
1. Run `node --loader newrelic/esm-loader.mjs index.mjs`
1. `curl …
> security: updated esm loader track instrumentation by url in a map instead of in url to avoid remote code executions

- lib/config/index.js
This is nothing but typo corrections. Only one in a log line, the rest in code comments. There are no functional changes.
I checked that the two typos that directly reference the code (`process_host.ipv_preference` and `this.serverless_mode`) are only misspelled in the comment, the code itself is using the correct spelling I changed them to.
I was temped to rename `_laspReponse` to `_laspResponse`, but I didn't want to step on any toes. Though it looks like it's only in the repo in this file and would be a safe change.
> chore: fixed typos in lib/config/index.js comments

- lib/aggregators/log-aggregator.js
- lib/instrumentation/pino/pino.js
- test/unit/aggregators/log-aggregator.test.js
- test/versioned/pino/pino.tap.js
Because pino does not always return valid JSON when serializing to json(see https://github.com/pinojs/pino/issues/1767), we have to add some defensive code to return a null record if we cannot parse the json to an object.  This also required some filtering logic in the log aggregator to not send empty logs to the collector.
Closes #1744
> fix: added defensive code around JSON.parse in formatting pino log lines because pino can return invalid json

- lib/shim/message-shim.js
- lib/shim/transaction-shim.js
- test/unit/shim/transaction-shim.test.js
Renamed handleCATHeaders to handleMqTracingHeaders. This function handles both distributed tracing and cross-application-tracing headers for message queues. CAT is going to be removed, leaving just the DT functionality. 
test/unit/ship/transaction-shim.test.js covers this file.
Closes #903 
Closes NR-133499
> feat!: Renamed shim.handleCATHeaders to shim.handleMqTracingHeaders

- .github/workflows/smoke-test-workflow.yml
We missed updating smoke test to test only on 16, 18 and 20. This PR fixes that
> test: update smoke tests versioned matrix in CI to 16, 18, and 20.

- THIRD_PARTY_NOTICES.md
- lib/instrumentation/@prisma/client.js
- package-lock.json
- package.json
- test/unit/instrumentation/prisma-client.test.js
- third_party_manifest.json
We had issues in the past with parsing the prisma connection string and provider.  In #1634 I moved it to parsing the schema with a 3rd party DSL parser.  I reached out to the prisma contributors and asked to re-expose getConfig. But they mentioned just trying out the [wasm package](https://github.com/prisma/prisma/pull/17455#issuecomment-1553402985).  I made this dep optional because not everyone uses prisma and it requires your build system to be configured to build node packages.
> fix: updated prisma instrumentation to parse prisma datamodel with internal package

- test/versioned-external/external-repos.js
CI will fail without this as the `ritm-update` branch in Next.js repo has been merged/closed.
> chore: updated next js repo to use main now that the branch has landed

- test/versioned/pino/pino.tap.js
A customer reported #1744 so we added defensive code and a test.  It turns out pino fixed this in https://github.com/pinojs/pino/pull/1779.  I had to update the test
as it now properly serializes the json.
> test: updated invalid json pino test as this was fixed in 8.15.1 of the pino library.

- package-lock.json
While testing something else I noticed a dep of chai has a CVE.  This is a dev dep so not a big deal but want this updated.
> chore: updated dev dep get-func-name to fix CVE

- index.js
- test/unit/index.test.js
Apparently Next.js does not like early returns in CommonJS files, even though it's valid syntax.  This PR updates it to return a stub API in that case, effectively doing nothing but without an early return
Closes #1783
> fix: updated agent to create a stub api when running in a worker thread

- .github/workflows/ci-workflow.yml
I would've been able to triage the elastic search issues faster if we had logs for the container.  This PR uploads all docker logs if a versioned test run fails.
You can see links [here](https://github.com/bizob2828/node-newrelic/actions/runs/6474022463).  I had a commit that replaced `failure()` with `always()`, but this will work on failures.
You can see there is a .gz for every version.
> ci: add steps to zip up container logs on versioned test failure

- index.js
- test/unit/index.test.js
In #1800 we updated the early return and abstracted common initialization code.  It properly assigns the API to module.exports but forgets to return the value used for security agent.  This fixes that and updates the unit test to assert that the security agent is called with the agent.
> fix: Updated intialization to properly return the api on start up to the security agent

- bin/conventional-changelog.js
- bin/test/conventional-changelog.test.js
ref: https://docs.newrelic.com/docs/style-guide/capitalization/capitalization/#heading_caps
> chore: Update release note headers to follow standard

- test/versioned/elastic/package.json
We skipped Node 20 elasticsearch tests while trying to triage issues with CI. This removes that flag.
> test: Removed skipping elasticsearch versioned tests on Node 20

- NEWS.md
This was missed when creating the changelog for 11.0.0.  The GitHub release has already been updated and PR to the release notes on docs-website will be coming shortly.
> chore: included changelog entry for removing ability to run in worker threads to 11.0.0

- .github/workflows/ci-workflow.yml
We were running up against a constrained CI environment when running versioned tests.  We split out internal and external versioned tests in #1792, this helped speed up runs significantly from 1hr 15 mins to 45 mins.  We were still towards the upper limit on disk space and when running coverage on versioned tests it took up over 40% of the disk.  When we added elasticsearch container it was causing failures because the disk was too high for the watermark, which we disabled in #1803.    We also had to limit the number of concurrent versioned tests job to 2 which also slowed it down.  We got approval for a larger 16 core runner and now can run 16 concurrent jobs on main.
This PR will only use larger runner when the branch is main and the `vars.NR_RUNNER` which is set to our larger runner of …
> ci: Updated CI workflow to use larger runners on versioned tests but only when running against the main branch

- bin/update-system-config-pages.js
There was some discussions around updating system configurations and it turns out the EU call previously has been a no-op for a bit.  It's getting this value via us prod.  I tested locally by reverting version and updating to newest and both us and eu prod are getting the values correctly.
> ci: Updated post release script to update the nodejs_agent_version only on staging and us prod, eu will get it via replication now

- test/versioned/grpc-esm/client-unary.tap.mjs
- test/versioned/grpc-esm/server-unary.tap.mjs
- test/versioned/grpc/client-bidi-streaming.tap.js
- test/versioned/grpc/client-server-streaming.tap.js
- test/versioned/grpc/client-streaming.tap.js
- test/versioned/grpc/client-unary.tap.js
- test/versioned/grpc/server-bidi-streaming.tap.js
- test/versioned/grpc/server-client-streaming.tap.js
- test/versioned/grpc/server-streaming.tap.js
- test/versioned/grpc/server-unary.tap.js
- test/versioned/grpc/util.cjs
We started seeing failing versioned tests when running in CI after larger runners.  It was always grpc tests with:
```sh
not ok 1 - No address added out of total 1 resolved
---
stack: >
bindResultPromise.then.errorString
(node_modules/@grpc/grpc-js/src/server.ts:569:32)
at:
line: 569
column: 32
file: node_modules/@grpc/grpc-js/src/server.ts
function: bindResultPromise.then.errorString
test: "should record errors in a transaction when ignoring "
source: |2
logging.log(LogVerbosity.ERROR, errorString);
deferredCallback(new Error(errorString), 0);
-------------------------------^
} else {
if (bindResult.count < addressList.length) {
``` 
After looking at the tests I realized we bind to a static port.  We never hit this before because the grpc and grpc-esm tests were never run at the same …
> test: updated the grpc versioned tests utils to dynamically bind ports to avoid conflicts between cjs and esm tests

- index.js
- lib/config/default.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-env.test.js
- test/unit/index.test.js
To restore behavior for some customers wanting to run in worker threads, they can set `config.worker_threads.enabled` to true in config of set `NEW_RELIC_WORKER_THREADS_ENABLED` to `true`.  I tried to be clear and proivde warnings that running in worker threads is not officially supported.  It seems as though some customers may find it valuable but we want to default to disable running in worker threads and allow customers to opt-in.
> feat: Updated agent initialization to allow running in worker threads when config.worker_threads.enabled is true

- package.json
- test/integration/newrelic-harvest-limits.tap.js
- test/integration/newrelic-response-handling.tap.js
- third_party_manifest.json
I think the issue we were facing is that the integration tests are timing out and the errors we see are very obscure.  But I was able to repro locally by doing `npx tap --timeout=45 --no-coverage test/integration/newrelic-response-handling.tap.js`.  You see errors like:
```sh
FAIL  test/integration/newrelic-response-handling.tap.js 656 OK 30s
command: /Users/revans/.nvm/versions/node/v20.8.0/bin/node
args:
- test/integration/newrelic-response-handling.tap.js
exitCode: null
signal: SIGTERM
```
We we see at times in tests. This is tap emitting the SIGTERM to end a test run.  I think we were always teetering around 5mins in CI and a few weeks ago I [added a few new tests](https://github.com/newrelic/node-newrelic/commit/30f0b16e13e9621c86481c5d5409a799dbbb8d57) and it pushed it over the …
> test: Increased timeout for integration tests to avoid random failures.

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
* Updated @newrelic/aws-sdk to v7.0.2
* Updated @newrelic/koa to v8.0.1
* Updated @newrelic/superagent to v7.0.1
* Removed this agent as a peer dependency, now that those packages are no longer standalone.
* Bumped @babel/traverse to v7.23.2 in dependencies.
> chore(deps): Updated aws-sdk, koa, superagent

- .github/workflows/versioned-coverage.yml
- .github/workflows/versioned-security-agent.yml
We sometimes get failures on nightly runs. Usually they are flappy tests and all other running versioned are stopped. This will prevent that from happening
> ci: Disable fail-fast on nightly versioned test runs

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
* Updated @newrelic/security-agent to v0.4.0
* Added event stats for RASP, IAST and exit events in healthcheck. 
* Deps: Updated uuid to v9.0.1 and @aws-sdk/client-lambda to v3.405.0
* Upgraded axios to 1.6.0 to resolve CVE-2023-45857 
* Removed Node.js 14.x from CI.
* Added should_skip flag to skip CI based on label.
> chore(dep): Updated @newrelic/security-agent to v0.4.0

- lib/adaptive-sampler.js
- lib/collector/remote-method.js
- lib/metrics/normalizer.js
- lib/metrics/normalizer/rule.js
- lib/shim/promise-shim.js
- lib/shim/shim.js
- lib/shim/transaction-shim.js
- lib/shim/webframework-shim.js
- lib/spans/streaming-span-event-aggregator.js
- lib/timer.js
- lib/util/flatten.js
- lib/util/process-version.js
- lib/util/properties.js
- lib/util/urltils.js
JSDoc doesn't recognize "bool" as a valid type. It should be written as "boolean". This PR adjusts all instances such that `npm run lint` does not report any "unknown type bool" errors.
> chore: fix bool -> boolean in jsdoc

- bin/prepare-release.js
- bin/test/prepare-release.test.js
This PR resolves issue #632 by always returning a date-string local to the `America/Los_Angeles` time zone.
> ci: Make release note date always in pacific time

- lib/logger.js
- test/unit/lib/logger.test.js
Set log file permissions to read/write for Node process only to prevent unauthorized access to the log.
`sudo -u nobody cat newrelic_agent.log` to simulate an unauthorized user should return `cat: newrelic_agent.log: Permission denied`.
`npm run unit` verifies that the agent can write the log as expected. 
Closes NR-175304
> security: Set log file permissions to read/write for Node process only

- documentation/feature-flags.md
- lib/config/default.js
- lib/feature_flags.js
- test/unit/feature_flag.test.js
The PR adds the configuration described in #1848 and resolved #1848.
I found some basic configuration testing, but it looks like there are not any tests that test for specific configuration items.
> feat: Added configuration for openai instrumentation

- test/versioned/pino/pino.tap.js
This PR removes a lint error complaining about a "logger" variable being redeclared in a subtest. Here, we refactor the tests to use variables from the subtest private context to avoid any potential side effects between tests and remove the lint error.
> test: Fixed shadowed variable lint error in pino versioned tests

- lib/llm-events/openai/chat-completion-message.js
- lib/llm-events/openai/chat-completion-summary.js
- lib/llm-events/openai/embedding.js
- lib/llm-events/openai/error-message.js
- lib/llm-events/openai/event.js
- lib/llm-events/openai/feedback-message.js
- lib/llm-events/openai/index.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/chat-completion-summary.test.js
- test/unit/llm-events/openai/common.js
- test/unit/llm-events/openai/embedding.test.js
- test/unit/llm-events/openai/error.test.js
- test/unit/llm-events/openai/feedback-message.test.js
I was able to confirm the data exists on the given request/responses when using a real openai library.   I also removed `api_type` as it is not available. also updated CDD for how to get organization
Closes #1843
> feat: Added openai LLM events.

- lib/instrumentation/@elastic/elasticsearch.js
- lib/util/objects.js
- test/unit/util/objects.test.js
The `isSimpleObject` utility was returning the incorrect boolean value when passing in an array.  The intention of this utility was to only assert if it was a plain object `{ key: 'value'}`.
Closes #1864
> fix: updated isSimpleObject util to only check plain objects not arrays

- api.js
- lib/agent.js
- test/unit/agent/agent.test.js
- test/unit/api/api-llm.test.js
- test/unit/api/stub.test.js
- test/unit/llm-events/openai/embedding.test.js
This API endpoint checks if the metadata is a plain object and if so assigns to agent.llm.metadata.
Closes #1850
> feat: Added setLlmMetadata API to allow users to specify metadata for LLM events

- lib/llm-events/openai/chat-completion-message.js
- lib/llm-events/openai/chat-completion-summary.js
- lib/llm-events/openai/error-message.js
- lib/llm-events/openai/event.js
- lib/llm-events/openai/feedback-message.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/chat-completion-summary.test.js
- test/unit/llm-events/openai/common.js
- test/unit/llm-events/openai/embedding.test.js
- test/unit/llm-events/openai/error.test.js
- test/unit/llm-events/openai/feedback-message.test.js
The initial attempt at creating LLM events was overengineered and created a perf hit around serialization with `JSON.parse(JSON.stringify(event))`. This PR updates that to just return the instance of the event and refactors it so we no longer have to store the agent as an instance property.
> refactor: Updated LLM events to no longer serialize and just return object

- api.js
This PR simplifies a check in the `api.recordCustomEvent` method by utilizing the `isSimpleObject` function.
> refactor: Improved custom event attributes checking when using api.recordCustomEvent

- README.md
- lib/instrumentation/openai.js
- lib/instrumentations.js
- lib/shim/shim.js
- lib/symbols.js
- test/unit/instrumentation/openai.test.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/embedding.test.js
- test/unit/shim/shim.test.js
- test/versioned/openai/openai.tap.js
- test/versioned/openai/package.json
This PR adds instrumentation for chat completion create.  It adds the relevant span and the associated LLM events: n chat completion messages, and 1 chat completion summary.
**Note**: Error handling has been deferred to #1845 as well as stream based chat completions(#1844).
Aside from instrumentation `openai.Chat.Completions.prototype.create`, I had to wrap `openai.prototype.makeRequest` to decorate the active segment with request headers and api key to be used when creating the LLM events. As you can see they are cleaned up before returning the result to the user.  I also had to enhance shim to pass in the active segment as the last arg, this is because once a promise resolves the active segment is its parent. We need the active segment that was being recorded to decorate the LLM events. …
> feat: Added instrumentation for openai chat completion creation

- lib/instrumentation/openai.js
- lib/metrics/names.js
- test/unit/instrumentation/openai.test.js
- test/versioned/openai/openai.tap.js
Adds instrumentation to create span for embedding creation and the LlmEmbedding event.  I omitted opaque: true. I will update the chat complietion in a different PR.  There is an ask to still capture the external http call to openai and this will do so. You can now see in the versioned tests that I'm asserting the child http external for embedding create.
Closes #1842
> feat: Added instrumentation for openai embedding creation

- lib/instrumentation/openai.js
- lib/llm-events/openai/chat-completion-message.js
- lib/llm-events/openai/event.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/common.js
- test/unit/llm-events/openai/embedding.test.js
- test/versioned/openai/openai.tap.js
This PR addresses a few items after reviewing approach with AI O11y team.
* removed `opaque: true` on recording of chat completions(embeddings was done in #1872) because we do in fact want to create spans for the external http call separately.
* `completion_id` should be the summary id for every message within a chat completion
* it was discovered that we were lacking creating a LlmChatCompletionMessage for the response choices
* it will only create a message for the first message(this is how python agent does as well as other vendors)
* metadata is spread across all LLM events instead of assigned to a key of `metadata`. 
* operations within chat completions were extracted to better convey what is occurring 
* added an `is_response` boolean to LlmChatCompletionMessages when it is the …
> refactor: updated how completion_id is assigned to LlmCompletionMessage

- package.json
- test/versioned/openai/openai.tap.js
- third_party_manifest.json
The nightly legacy context manager versioned tests were failing on [openai](https://github.com/newrelic/node-newrelic/actions/runs/6888474698).  This PR addresses those failures by ending every transaction.  It turns out the async local context manager does not require you to end the transaction because that implicitly happens with the ctx manager.  However, the legacy context manager requires you to end transactions if you want to properly sandbox every test.
`npm run versioned:legacy-context openai`
> test: Updated openai versioned tests to properly work with the legacy context manager

- api.js
- lib/instrumentation/openai.js
- test/unit/api/api-llm.test.js
- test/unit/instrumentation/openai.test.js
- test/versioned/openai/openai.tap.js
In #1868 we forgot to update the instrumentation's check for enablement. This PR fixes that oversight. It also improves the check to be an explicit check, which should cause future tests to fail if the configuration is removed or refactored again.
> fix: Add missing configuration check in OpenAI implementation

- test/unit/api/api-llm.test.js
This PR increases code coverage of the LLM API methods through unit testing. This PR stems from https://github.com/newrelic/node-newrelic/pull/1875#discussion_r1396339137.
> test: Add unit tests for LLM API methods

- CONTRIBUTING.md
- NEWS.md
- README.md
- examples/shim/Datastore-Simple.md
- test/lib/cross_agent_tests/sql_obfuscation/README.md
Update of links in documentation, to be consistent with use of `https` except for references to `localhost`.
Closes NR-175309
> chore(docs): Updated links in documentation to https

- .github/workflows/post-release.yml
- bin/update-system-config-pages.js
Access to staging is no longer available unless behind VPN.  It may be a bit before there is a solution in place.  I removed updating staging to avoid failures in post release.
> ci: remove updating staging with newly release agent version

- test/versioned/openai/chat-completions.tap.js
- test/versioned/openai/mock-server.js
The OpenAI folks [helped me realize](https://github.com/openai/openai-node/issues/537) that I didn't quite design the error stream case in our mock server. This PR refactors the mock server to induce an error at the client side that will be handled correctly by the OpenAI client, and in turn bubbled up to our code as a legitimate connection error.
> chore: Improve OpenAI mock server streams

- bin/macos-firewall.sh
- documentation/developer-setup.md
- lib/instrumentation/pg.js
- lib/instrumentation/winston.js
- lib/shimmer.js
- lib/symbols.js
- test/versioned/winston-esm/common.mjs
- test/versioned/winston-esm/fixtures/named-import.mjs
- test/versioned/winston-esm/fixtures/star-import.mjs
- test/versioned/winston-esm/newrelic.cjs
- test/versioned/winston-esm/package.json
- test/versioned/winston-esm/winston.tap.mjs
> fix: Updated shimmer to handle instrumenting named and default exports of CommonJS modules in ESM

- test/versioned/winston-esm/package.json
- test/versioned/winston-esm/winston.tap.mjs
The tests from #1894 exhibited a failure case when the versioned sampling was expanded in the `main` CI suite (https://github.com/newrelic/node-newrelic/actions/runs/7091603183/job/19301106334). The issue is that Winston changes the way they export their API between v3.3.4 and v3.4.0 in https://github.com/winstonjs/winston/pull/2006. This PR narrows the test case to test against Winston >= 3.4.0.
> test: Fix winston-esm versioned tests

- test/versioned/undici/package.json
Undici EOLd Node 16 in [6.0.0](https://github.com/nodejs/undici/releases/tag/v6.0.0). This PR skips running >=6.0.0 on Node 16.
> test: pin undici versioned to <6.0.0 on Node 16

- lib/instrumentation/openai.js
- lib/metrics/names.js
- test/versioned/openai/chat-completions.tap.js
- test/versioned/openai/embeddings.tap.js
The AI o11y team needs a more reliable way of location openai spans to provide more context in the AI Monitoring UX.  This convention was agreed upon for all current and future language agent teams: `Llm/<event-type>/<library>/<instrumented function>`.
`npm run versioned:internal openai`
Closes #1893
> refactor: Updated span names of openai actions to allow AI O11y team to locate relevant spans

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
Updated @newrelic/aws-sdk to 7.0.3, to call shim.setLibrary and shim.setDatastore only once instead of on every call to sqs/sns/dyanmodb. 
https://github.com/newrelic/node-newrelic-aws-sdk/issues/218
> fix(deps): Updated @newrelic/aws-sdk to 7.0.3

- index.js
Moving the './' path to the require statement allows bundlers to find the api.js and stub_api.js files
Move path for api dynamic import to require statement in `initApi`.
Closes #1904
> refactor: change dynamic import to work with bundlers

- lib/instrumentation/restify.js
- lib/util/logger.js
- test/versioned/restify/restify-post-7/async-handlers.tap.js
- test/versioned/restify/restify-post-7/capture-params.tap.js
- test/versioned/restify/restify-post-7/common.js
- test/versioned/restify/restify-post-7/package.json
- test/versioned/restify/restify-post-7/transaction-naming.tap.js
Restify checks handler type and the number of arguments. Our traditional wrapping would supply a synchronous wrapper around sync or async functions, and as a result was not passing the type checking. This change supplies an asynchronous wrapper for asynchronous Restify handlers and middleware.
`npm run versioned restify` will run the Restify versioned tests. This includes a new test for async and sync handlers: `async-handlers.tap.js`.
Closes #1824 
Closes NR-171678
> feat: Added instrumentation for Restify async handlers 

- api.js
- lib/llm-events/openai/event.js
- test/unit/api/api-llm.test.js
- test/unit/api/stub.test.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/chat-completion-summary.test.js
- test/versioned/openai/chat-completions.tap.js
- test/versioned/openai/embeddings.tap.js
It was discusssed with AI team that `setLlmMetadata` was too rigid.  They wanted a dynamic way to assign attributes.  We already have that in `api.addCustomAttribute(s)`. The AI will associate llm metadata downstream if custom attributes on transaction match `llm.` as the prefix to the attributes names.  With that we're also changing conversation id to be `llm.conversation_id`.
> feat: removed api.setLlmMetadata as llm metadata will be assigned via api.addCustomAttribute with a prefix of `llm.`

- test/integration/distributed-tracing/dt.tap.js
I was refactoring promise-shim and verifying I didn't break anything and noticed in this test we were using a deprecated `_headers` property on a request message.  The preferred way to access is via `.headers`.
> test: removed access to deprecated req._headers and instead use req.headers

- lib/instrumentation/core/http-outbound.js
- test/unit/instrumentation/http/outbound.test.js
This fixes a bug where if `opts.headers` is `null`, it is not handled by further down functions and causes a crash.
Unfortunately, the situations in which this is reproduced are very specific to a flow that I have difficulty artificially reproducing. I am applying this fix as a technical code fix purely based on the way that it is crashing.
Fixes #1925
> fix: Ensure opts.headers is defined in request instrumenting

- lib/shim/webframework-shim.js
- lib/shim/webframework-shim/common.js
- lib/shim/webframework-shim/index.js
- lib/shim/webframework-shim/middleware-mounter.js
- lib/shim/webframework-shim/middleware.js
This PR refactors webframework-shim to reduce cognitive complexity.  I broke out a lot into new files because it was very hard to navigate.
> refactor: Updated webframework-shim to reduce the cognitive complexity

- test/versioned/openai/chat-completions.tap.js
- test/versioned/openai/embeddings.tap.js
In #1919 mocha was removed as well as some common assertions were updated to properly use tap.  I missed a few places that were wrapping the tap assertion in a `t.doesNotThrow`.  This is no longer needed as the helper properly uses tap to do assertions. I also noticed some assertions were not using the proper instance of tap.
> test: updated chat-completions tests to properly assert segments

- lib/instrumentation/openai.js
In #1918 we removed the ability to assign metadata to LLM events. This was because the implementation wasn't fully thought out at the org level.  I missed a spot where it was actually reading if `agent.llm.metadata` was present and spreading it on the LLM message.
> chore: removed assigning unused metadata to LLM events

- test/versioned/undici/requests.tap.js
CI was failing after the [6.3.0](https://github.com/nodejs/undici/releases/tag/v6.3.0) release of undici.
```sh
ok 1 - segment "ROOT" should have child "External/localhost:33941/delay/1000"
ok 2 - should be equal
not ok 3 - should be equal
---
compare: ===
at:
line: 244
column: 11
file: requests.tap.js
stack: |
requests.tap.js:244:11
source: |2
t.equal(tx.exceptions.length, 1)
t.equal(tx.exceptions[0].error.message, 'Request aborted')
----------^
tx.end()
t.end()
diff: |
--- expected
+++ actual
@@ -1,1 +1,1 @@
-Request aborted
+This operation was aborted
...
1..3
```
Looks like generic error on aborted request changes. This PR updates that to handle it accordingly.
> test: updated abort controller test expected error message based on undici version

- lib/metrics/names.js
- test/versioned/openai/chat-completions.tap.js
The Nodejs/ML/OpenAI/<version> metric is needed to apply a tag to the apm entity. A dev rel engineer wasn't seeing it. It was because it had `//` in one of the path segments.  Also our test was using the same constant to assert the broken behavior. Fixed it all.
> fix: remove extra / in openai framework metric name

- test/unit/collector/remote-method.test.js
The current test relies on whatever DNS server the system uses to return a "not found" answer for `failed.domain.clxrg`. There are two problems with this:
1. A unit test, in my opinion, should not rely on any external resources (servers) in order to work.
2. AT&T seems to ship gateways that will resolve whatever random domain you give them to arbitrary IP addresses.
This PR solves both problems.
> test: Fix DNS lookup in remote-method test

- lib/shim/conglomerate-shim.js
- test/unit/shim/conglomerate-shim.test.js
In #1883 we added the ability to grab the version of the package via `shim.pkgVersion`.  There was an oversight when you create a child shim via `shim.makeSpecializedShim`. It was not using the pkgVersion and id from the parent shim.  This PR resolves that so if you are using a shim instance from `shim.makeSpecializedShim`, `shim.pkgVersion` will be present.
> feat: Assign pkgVersion and id of all child shim instances when using shim.makeSpecializedShim with a ConglomerateShim instance

- lib/instrumentation/@elastic/elasticsearch.js
- test/versioned/elastic/elasticsearch.tap.js
- test/versioned/elastic/package.json
Dropped instrumentation for ElasticSearch prior to 7.16.0, due to a bug in ElasticSearch's helper API, fixed in [7.16.0](https://github.com/elastic/elasticsearch-js/pull/1594).
We added versioned tests to check compatibility with the ElasticSearch helper API. Run `npm run versioned elastic`.
Closes NR-190287
Closes #1908
> fix: Dropped support for ElasticSearch < 7.16.0

- lib/collector/remote-method.js
- test/unit/collector/remote-method.test.js
- test/unit/mocks/logger.js
Updated private `_path` method to pass in boolean to generate path for remote method.  If arg is true it'll redact the ingest key. This is only called when logging certain trace level logs. This does not remove ingest key from collector path or payload in connect and pre-connect as the downstream services lack support for this.
After this PR you see this in logs
```
{"v":0,"level":10,"name":"newrelic","hostname":"TK46XHNX04","pid":84136,"time":"2024-01-12T21:26:05.878Z","msg":"Posting to https://staging-collector.newrelic.com:443/agent_listener/invoke_raw_method?marshal_format=json&protocol_version=17&license_key=REDACTED&method=agent_settings&run_id=","component":"remote_method","body":"Buffer 26910"}
```
Fixes NR-214994
> security(remote_method): redact ingest key in trace level logs

- .eslintrc.js
- lib/shim/shim.js
* Fixed _most_ jsdoc violations
* Refactored shim but reducing cognitive complexity.  This was done by removing nested functions
Closes NR-134577
> refactor: Updated `lib/shim/shim.js` to remove cognitive complexity violations

- THIRD_PARTY_NOTICES.md
- lib/feature_flags.js
- package-lock.json
- package.json
- third_party_manifest.json
We typically don't update deps that fall within semver ranges but this PR is mostly to remove the `aws_bedrock_instrumentation` feature flag now that the code is complete and released in 7.1.0 of `@newrelic/aws-sdk`.
> chore(deps): updated @newrelic/aws-sdk to latest and removed aws_bedrock_instrumentation feature flag

- .eslintrc.js
- lib/shim/message-shim/common.js
- lib/shim/message-shim/consume.js
- lib/shim/message-shim/index.js
- lib/shim/message-shim/subscribe-consume.js
- lib/shim/specs/index.js
Fixed jsdoc warnings as well.
I refactored message-shim by extracting inline functions into top level scope. I also moved some of the helper functions into their own files.  I fixed all the jsdoc violations and lastly added the MessageSpec and MessageSubscribeSpec into specs instead of inline within file.
`npm test`
Closes NR-134575
> refactor: Updated message-shim to remove cognitive complexity violations.

- .github/workflows/notify-release.yml
- .github/workflows/post-release.yml
Some non-sensitive repository values used for CI were set as secrets, but that's an unnecessary overloading of secrets: 
- NR_REPOS
- IGNORE_LABELS
- SLACK_CHANNEL
- NODE_AGENT_CI_USER_NAME
- NODE_AGENT_CI_USER_EMAIL
This PR migrates them to repo vars. 
Closes #1637 
Closes NR-137604
> chore: Migrated non-sensitive CI values to vars

- lib/errors/index.js
- test/unit/api/api-set-user-id.test.js
- test/unit/errors/error-collector.test.js
- test/unit/protocols.test.js
- test/versioned/connect/error-intercept.tap.js
We need to add the transaction id to ErrorTrace event to [link Transactions to Traces](https://newrelic.atlassian.net/wiki/spaces/CPE1/pages/2885255250/CDD+Put+Transaction+IDs+into+ErrorTrace+Events). 
Added transaction.id as the last field of the Error Trace JSON payload if the error occurs within a transaction. 
Example error trace payload:
```
[
"BSr1H3OtQKJhADnLvCAdVaVlqrHUAAgBAAAnIQEAAMwQAgQgHVy5AwAGMTEuOYWZ0ZXItMw",
[
0,
"WebTransaction/Expressjs/GET//error-stack",
"Expected ',' or '}' after property value in JSON at position 47",
"SyntaxError",
{
"userAttributes": {},
"agentAttributes": {
"spanId": "4c6c496ad0492950",
"request.headers.host": "localhost:3000",
"request.headers.userAgent": "curl/8.4.0",
"request.headers.accept": "*/*",
"request.method": "GET",
"request.uri": …
```
> feat: Added transaction ID to ErrorTrace event

- api.js
- lib/shim/datastore-shim.js
- lib/shim/message-shim/subscribe-consume.js
- lib/shim/promise-shim.js
- lib/shim/shim.js
- lib/shim/webframework-shim/middleware-mounter.js
- lib/shim/webframework-shim/middleware.js
- lib/transaction/handle.js
- package.json
- third_party_manifest.json
I noticed after refactoring message-shim and webframework-shim the [API docs](https://newrelic.github.io/node-newrelic/) were not being properly generated.
One issue was the WebFrameworkShim and MessageShim docs are gone, this was because they are now subdirectories.  But there was also a lot of global functions. This PR marks all private methods as such in jsdoc with `@private`, but also fixes the `public-docs` script to include the new subdirectories of the shim files.
```
npm run public-docs
open out/index.html
```
It should have MessageShim and WebFrameworkShim in the Classes section.  Also the global section should remove a lot of private functions.
> docs: Fixed jsdoc generation by marking private methods as @private

- lib/instrumentation/winston.js
- test/versioned/winston/winston.tap.js
A customer reported they didn't see the agent forwarding agent logs. That is because the configure method will clear existing transports and assign new ones. This PR wraps the configure method and adds our transport to the arguments of the function before calling the original. I also noticed we don't properly create our formatter if you pass a null param to `winston.createLogger`, this also fixes that issue by re-assigning arguments[0] to an empty object when undefined.
`npm run versioned:internal winston`
Fixes #1986
> fix: Updated winston instrumentation to wrap configure to properly retain our transporter to do log forwarding

- test/versioned/prisma/package.json
Prisma fixed their exports issues in 5.9.1 this PR updates the versioned test range to skip 5.9.0 but continue testing on newer versions
Closes #1984
> test: updated prisma versioned test range to skip 5.9.0 as it was broken

- lib/instrumentation/grpc-js/grpc.js
In 1.10.0 of `@grpc/grpc-js` they refactored how they end calls/streams by introducing a server interceptor.  Weirdly the methods to end a call and stream are not exposed to the public API.  Either way this PR wraps the calls to work in 1.10.0.
`npm run versioned:internal grpc`
Closes #2000
> fix: Updated grpc-js instrumentation to properly track errors and end transactions

- test/smoke/api/error-data.tap.js
- test/smoke/api/metric-data.tap.js
- test/smoke/api/transaction-sample-data.tap.js
#1981 refactored the collector to have a common send function and the first argument is now the method on collector API. Smoke tests apparently used this directly and needed to be updated to use the send function instead of the specific collector method as function name. I also pushed my branch to the origin so the smoke tests should run and pass now
> test: Updated smoke tests to send data to the appropriate collector method

- lib/shim/shim.js
- lib/shimmer.js
- test/integration/module-loading/module-loading.tap.js
- test/unit/shim/shim.test.js
This PR simplifies the calculation of `this._moduleRoot` on shim.  Since require-in-the-middle has been introduced it passes us the module root as basedir which gets passed in as `resolvedName`.  The previous logic traversed up directories to find the appropriate root.  This logic did not account for windows paths in the regular expression.  Instead of fixing that I found this code confusing and unnecessary. For built in packages, the `this._moduleRoot` will be set as `.`.  `this._moduleRoot` is only used when calling `shim.require` which is only done in 3rd party instrumentation so setting builtins to `.` is really just defensive code.
The only issue I have with this PR is I cannot figure out how to create a failing test for the issue as it only exists on windows and I can't seem to …
> fix: Updated Shim to properly calculate the _moduleRoot on windows environments

- test/unit/collector/api.test.js
I was running unit tests and noticed:
```sh
ok 1 - should be equal
Cleaning pending mocks: ["POST https://collector.newrelic.com:443/agent_listener/invoke_raw_method"]
1..1
```
I thought it was an issue with a recent fix #2013 but it turned about to be an issue with cleaning up pending mocks as the log test doesn't hit `agent_settings`. This PR fixes the warning to avoid confusion in the future.
`node test/unit/collector/api.test.js`
You should no longer see the 
```sh
Cleaning pending mocks: ["POST https://collector.newrelic.com:443/agent_listener/invoke_raw_method"]
```
when running the tests
> test: Cleaned up pending mocks in the log dropping test to avoid a console warning around pending mocks in after each

- lib/instrumentation/openai.js
- lib/llm-events/event.js
- lib/llm-events/langchain/event.js
- lib/llm-events/openai/event.js
- lib/metrics/names.js
- test/unit/llm-events/langchain/event.test.js
- test/unit/llm-events/openai/chat-completion-summary.test.js
- test/unit/llm-events/openai/common.js
- test/versioned/openai/chat-completions.tap.js
- test/versioned/openai/common.js
- test/versioned/openai/embeddings.tap.js
This PR addresses a few items that were codified into the specification that we were missing:
* remove capturing api key
* update tracking metric to start with `Supportability/Nodejs/ML`
* include any custom attributes that start with `llm.` except `llm.conversation_id` as attributes on all Llm Events.
Closes #2007
> refactor: Updated AIM instrumentation 

- lib/instrumentation/openai.js
- lib/llm-events/event.js
- lib/llm-events/langchain/event.js
- lib/llm-events/openai/chat-completion-message.js
- lib/llm-events/openai/chat-completion-summary.js
- test/unit/llm-events/langchain/chat-completion-message.test.js
- test/unit/llm-events/langchain/chat-completion-summary.test.js
- test/unit/llm-events/langchain/event.test.js
- test/unit/llm-events/langchain/vector-search-result.test.js
- test/unit/llm-events/langchain/vector-search.test.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/chat-completion-summary.test.js
- test/unit/llm-events/openai/common.js
- test/versioned/openai/feedback-messages.tap.js
Moves `conversation_id` to `llm.conversation_id` and have it apply to all Llm Events.
Closes #2019
> refactor: Updated capturing conversation_id on Llm Events as `llm.conversation_id`

- lib/shim/specs/class.js
- lib/shim/specs/message-subscribe.js
- lib/shim/specs/message.js
- lib/shim/specs/middleware-mounter.js
- lib/shim/specs/middleware.js
- lib/shim/specs/operation.js
- lib/shim/specs/query.js
- lib/shim/specs/recorder.js
- lib/shim/specs/render.js
- lib/shim/specs/transaction.js
- lib/shim/specs/wrap.js
This PR fixes some issues with the docs on the recently added spec objects. When I got to some specs that only add one or two parameters to the subclass I forgot why I was using a `typedef` for the constructor parameters and wrote them inline. This was a mistake. Each subclass's parameters should augment the parent class's parameters. We can only do that with `typedef` blocks for the parameters.
As I was fixing this issue, I discovered that the `@augments` tag does not inline the parent definition's properties, nor provide a link back to the definition. The `@mixes` tag at least provides a link.
> docs: Fix spec objects parameter definitions

- bin/macos-firewall.sh
- documentation/developer-setup.md
This PR updates the documentation around the `macos-firewall.sh` script to note that it should be run using elevated privileges.
> docs: Add note about using sudo for firewall script

- THIRD_PARTY_NOTICES.md
- lib/instrumentation/langchain/callback-manager.js
- lib/instrumentation/langchain/common.js
- lib/instrumentation/langchain/nr-hooks.js
- lib/instrumentation/langchain/tools.js
- lib/instrumentations.js
- lib/llm-events/langchain/chat-completion-message.js
- lib/llm-events/langchain/chat-completion-summary.js
- lib/llm-events/langchain/event.js
- lib/llm-events/langchain/index.js
- lib/llm-events/langchain/tool.js
- lib/metrics/names.js
- lib/symbols.js
- package-lock.json
- test/lib/agent_helper.js
- test/unit/instrumentation/langchain/tools.test.js
- test/unit/llm-events/langchain/event.test.js
- test/unit/llm-events/langchain/tool.test.js
- test/versioned/fastify/common.js
- test/versioned/langchain/helpers/custom-tool.js
- test/versioned/langchain/package.json
- test/versioned/langchain/tools.tap.js
- third_party_manifest.json
**Note**: I'm using a community tool in wikipedia which is making real http requests. I could mock just not sure it matters yet.  We also cannot merge this because it depends on the https://github.com/elastic/require-in-the-middle/pull/82 PR which hasn't landed nor is released.  
This PR instruments langchain StructuredTool class to create LlmTool events and records spans when their call methods are invoked.  I also had to tweak some of the llm events to put attributes on the base class.  This also partially addresses #2007 but I can PR that separately as the openai tests will be failing
Closes #1964
> feat: Added instrumentation for langchain tools.

- lib/instrumentation/langchain/runnable.js
- lib/llm-events/langchain/chat-completion-message.js
- test/versioned/langchain/common.js
This PR fixes an oversight from previous work.
> chore: Add missing is_response to LangChain completion messages

- lib/instrumentations.js
Added `@azure/openai` and `@langchain/community/llms/bedrock` as tracking type modules in `lib/instrumentations.`.  This will produce supportability metrics that angler can load so we can track customers using these packages before deciding to add instrumentation.
In an app
```
npm i @azure/openai @langchain/community
require('@azure/openai')
require('@langchain/community/llms/bedrock')
```
Run npm linked version of agent and check logs.
You will see supportability metrics get logged as such
```sh
[{\"name\":\"Supportability/Features/Instrumentation/OnRequire/@azure/openai\"},[1,0,0,0,0,0]]
[{\"name\":\"Supportability/Features/Instrumentation/OnRequire/@azure/openai/Version/1\"},[1,0,0,0,0,0]]
{\"name\":\"Supportability/Features/Instrumentation/OnRequire/@langchain/community/llms/bedrock\" …
```
> chore: Added @azure/openai and @langchain/community/llms/bedrock as tracking packages so we can measure usage with angler

- lib/instrumentation/langchain/runnable.js
- lib/llm-events/langchain/event.js
- test/unit/llm-events/langchain/event.test.js
- test/versioned/langchain/common.js
- test/versioned/langchain/package.json
- test/versioned/langchain/runnables-streaming.tap.js
This adds instrumentation for `chain.stream`.  I also handled when `ai_monitoring.streaming.enabled` is set to false by creating the supportability metric and also the framework metric but no events.  
`npm run versioned:internal langchain`
Closes #1967
> feat: Added instrumentation for `chain.stream` for langchain js.

- bin/publish-docs.sh
This should help diagnose why https://github.com/newrelic/node-newrelic/actions/runs/8144608511/job/22260190806 is failing and provide ongoing insight in the future.
> chore: Added flag for verbosity during docs publishing

- bin/publish-docs.sh
After adding verbosity to docs gen (https://github.com/newrelic/node-newrelic/actions/runs/8145456792/job/22261755414) it looks like some operations are happening out-of-order (it could just be the way GitHub Actions records the logs, though). This PR adds some delays to try and solve that problem.
> chore: Added some delays to docs publishing

- lib/llm-events/openai/chat-completion-message.js
- lib/llm-events/openai/embedding.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/common.js
- test/versioned/openai/chat-completions.tap.js
- test/versioned/openai/common.js
- test/versioned/openai/embeddings.tap.js
To support calculating token counts downstream for Llm events that lack counts(i.e. streaming or disabling capturing content), we have added `token_count` to LlmEmbedding, and LlmChatCompletionMessage.  This only adds and does not remove the old attributes for capturing token counts on prompts and completions. That will be handled in #2057
Closes #2056
> feat: Added token_count to LlmEmbedding and LlmChatCompletionMessage for openai

- api.js
- lib/instrumentation/restify.js
- lib/llm-events/openai/chat-completion-message.js
- lib/llm-events/openai/embedding.js
- lib/shim/shim.js
- test/unit/api/api-llm.test.js
- test/unit/api/api-set-error-group-callback.test.js
- test/unit/api/stub.test.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/embedding.test.js
- test/versioned/openai/chat-completions.tap.js
Adds `setLlmTokenCountCallback` to register callback to be called to get token counts when they are not present on events.  This function must be synchronous and return token count.  
Closes #2055
> feat: Added setLlmTokenCountCallback API endpoint to register a callback for calculating token count when none is provided

- lib/llm-events/openai/chat-completion-message.js
- lib/llm-events/openai/embedding.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/common.js
- test/versioned/openai/chat-completions.tap.js
- test/versioned/openai/common.js
- test/versioned/openai/embeddings.tap.js
> chore: Changed token_count to only use tokenCountCallback

- documentation/feature-flags.md
- lib/feature_flags.js
- lib/instrumentation/langchain/common.js
- test/unit/instrumentation/langchain/runnables.test.js
- test/unit/instrumentation/langchain/tools.test.js
- test/unit/instrumentation/langchain/vectorstore.test.js
- test/versioned/langchain/runnables-streaming.tap.js
- test/versioned/langchain/runnables.tap.js
- test/versioned/langchain/tools.tap.js
- test/versioned/langchain/vectorstore.tap.js
langchain is feature complete. feature flag is no longer needed.
Closes #2072
> chore: Removed langchain_instrumentation feature flag as the instrumentation is feature complete

- lib/errors/index.js
- test/unit/errors/error-collector.test.js
Our agents needs to add `guid` to `TransactionError` events. This is the final step needed in order for Errors Inbox team to link `TransactionError` events and `ErrorTrace` events when errors happen within a transaction. 
Added unit tests. Also ran a sample errors app and verified in the query builder that there is a `guid` on `TransactionError` events when distributed tracing is enabled or disabled. 
Relates to this pr #1954 
Closes #2076
> feat: Added `guid` attribute to `TransactionError` events

- lib/instrumentation-descriptor.js
- lib/instrumentation-tracker.js
- lib/util/idgen.js
- test/unit/instrumentation-descriptor.test.js
- test/unit/instrumentation-tracker.test.js
This PR adds source code needed by issue #2033. We can't add it directly in the work for that issue because our external `@newrelic/test-utilities` package depends on it as well. So we need to:
1. get this code into the tree
2. update the test utils branch to point to this merged code
3. in the 2033 branch point to the git tree for the update test utils
4. merge both things
5. issue releases some how?
> chore: Added instrumentation tracking class

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
We had a nightly failure with security agent.  It turns out the grpc instrumentation in security agent is stomping on our instrumentation.  I've logged https://github.com/newrelic/csec-node-agent/issues/192. Until the IAST team can implement integration tests with our agent before release we will continue to pin the security agent.
> chore(deps): pin @newrelic/security-agent to 1.0.1

- lib/instrumentation/mongodb/v4-mongo.js
- test/versioned/mongodb/bulk.tap.js
- test/versioned/mongodb/package.json
- **feat: Added support for Mongo v5+**
- **feat: Added instrumentation for `initializeUnorderedBulkOp`**
**Note**: This is based off of my mongo-5 branch so this will need to rebased after #2085 is merged. The relevant commit is this [one](https://github.com/newrelic/node-newrelic/pull/2086/commits/9b13aaed2842cb629bc30db0f243ae6fbbc9b1fd)
I'm not sure what 2022 me was doing but this was rather straightforward.  This Pr adds instrumentation for `initializeUnorderedBulkOp` and `initializeOrderedBulkOp`.
`npm run versioned:internal mongodb`
Closes #1122
> feat: Added instrumentation for `initializeUnorderedBulkOp`, and `initializeOrderedBulkOp` in mongodb 4+

- bin/prepare-release.js
In the course of adding release automation to the serverless plugin repo, I noticed this typo in our constant name. There's no functional change, but it's housekeeping.
> chore: Fixed typo in constant name

- .github/workflows/versioned-security-agent.yml
This PR resolves #2088. It adds a new job to the `versioned-security-agent` workflow that detects if the `package.json` has been updated, and if so, whether or not the `@newrelic/security-agent` version number has been changed. The results of this job are utilized by the already existing job to determine if it should run. After this PR there are three cases where the versioned tests will run with the security agent enabled:
1. When the workflow is directly run through the GitHub interface.
2. When nightly scheduled job is executed.
3. When a pull request includes a change in the version for the `@newrelic/security-agent` dependency.
-----
Note: the CI run https://github.com/newrelic/node-newrelic/actions/runs/8455455203/job/23162959574?pr=2100 as a result of opening this PR shows that the …
> chore: Updated versioned security agent workflow

- jsdoc-conf.json
- package-lock.json
- package.json
See:
+ https://github.com/ankitskvmdam/clean-jsdoc-theme/issues/281
+ https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/9c6d7538c39bd74a1f223dd4c52d45cab6d8d37a
```sh
npm run public-docs
open out/index.html
```
> chore: Removed scrollbar styling in generated API docs

- .github/workflows/prep-release.yml
- .github/workflows/prepare-release.yml
- bin/prepare-release.js
- bin/test/prepare-release.test.js
The `bin/prepare-release.js` script has logic to generate a changelog in both markdown and json.  The json gets written to changelog.json which is subsequently parsed and used to open a docs PR with front matter for the given release.  This logic is only needed for `node-newrelic`.  When we migrated all of our others repos we had to add a changelog.json which writes features, bugs and security fixes but it's never used.  This PR provides the ability to optionally pass in a flag `--changelog-json` to write out the changes to changelog.json which will only be used in node-newrelic, which you can see is being done in `.github/workflows/prepare-release.yml`. Once this is merged we can update all external repos to remove the `changelog.json`
```
npm run unit:scripts
```
Closes #2105
> ci: Updated `prepare-release.js` to not require changelog.json

- test/versioned/elastic/package.json
See issue https://github.com/elastic/elastic-transport-js/issues/90
> chore: Updated elastic tests to skip broken version

- test/versioned/elastic/package.json
My previous PR didn't quite do it.
> chore: Fixed incorrect pinning of @elastic/transport

- .github/workflows/prep-release.yml
- .github/workflows/prepare-release.yml
- bin/prepare-release.js
We no longer need to use `use_new_release` since all repos workflows are (or will be) updated to use the new release workflow. 
Fixes issue https://github.com/newrelic/node-newrelic/issues/2112
> ci: Removed usage of `use_new_release` from prepare release workflow

- .github/workflows/ci-workflow.yml
- .github/workflows/versioned-coverage.yml
- .github/workflows/versioned-security-agent.yml
- THIRD_PARTY_NOTICES.md
- bin/run-versioned-tests.sh
- package-lock.json
- package.json
- third_party_manifest.json
> chore: Updated versioned tests to use quiet output mode

- examples/shim/Context-Preservation.md
- examples/shim/Datastore-Simple.md
- examples/shim/Instrumentation-Basics.md
- examples/shim/Messaging-Simple.md
- examples/shim/Webframework-Simple.md
Some images were invalid markdown in html divs. I just unified this with the same injection.
```sh
npm run public-docs
open out/index.html
```
Check all Tutorials in the dropdown.
Closes #2152
> docs: Fixed images in markdown tutorials

- lib/collector/serverless.js
- test/integration/agent/serverless-harvest.tap.js
Usage metrics are displayed by agent and faceted by `name`, which is derived from the `agent_language` metadata header. While that header's part of the v2 serverless spec, it's still recognized and delivered to NRDB in a v1 payload. This adds the header. 
This value is included in the serverless harvest integration test, but the TDP usage value has been tested using a function instrumented with a custom build of the agent that includes this change.
Closes #2130 
Closes NR-256299
> chore: Added language header to serverless metadata

- api.js
- lib/transaction/index.js
- test/unit/api/api-ignore-apdex.test.js
- test/unit/api/stub.test.js
- test/unit/transaction.test.js
- test/versioned/express/render.tap.js
This PR adds `ignoreApdex` which just sets a property on transaction and when apdex is calculate will skip and log a warning. I plan on following up with a spec update but this logic aligns with Ruby, Java, and .NET agents. 
Closes #2142
> feat: Added API `ignoreApdex` to ignore calculating apdex for the active transaction

- test/versioned/aws-sdk-v3/package.json
It's been a while since we've had to work around aws sdk quirks. This PR updates the minimum of the dynamo peer deps to work around resolution issues
> ci: Updated minimum version of lib-dynamo to work around peer dependency resolution

- lib/instrumentation/core/http-outbound.js
- lib/instrumentation/undici.js
- lib/spans/span-event.js
- lib/spans/streaming-span-event.js
- test/integration/instrumentation/http-outbound.tap.js
- test/unit/instrumentation/http/outbound.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
- test/versioned/undici/requests.tap.js
Added OTEL-compliant `http.request.method` and `server.address` properties to external HTTP spans.
This PR includes additions to `test/unit/spans/span-event.test.js` and `test/unit/spans/streaming-span-event.test.js`, so running unit tests will include these.
Closes #2150 
Closes NR-260118
> chore: Added otel compliant spans to external http spans

- lib/spans/span-event.js
- lib/spans/streaming-span-event.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
Added OTEL-compliant `db.system`, `server.address`, and `server.port` properties to db spans.
This PR includes additions to `test/unit/spans/span-event.test.js` and `test/unit/spans/streaming-span-event.test.js`, so running unit tests will include these.
Closes #2149 
Closes NR-260092
> chore: Added otel compliant attributes for database spans

- lib/instrumentation/openai.js
- test/versioned/openai/common.js
This updates instrumentation to handle the update to `openai` in [4.40.1](https://github.com/openai/openai-node/issues/816).  I'm not sure we should release this fix as I think openai needs to issue a fix for this.  But this will unblock our CI for now. 
Also, FWIW `import-in-the-middle` causes OpenAI to crash
```
node ---loader=import-in-the-middle/hook.mjs --input-type=module -e "import OpenAI from 'openai'; const a = new OpenAI();"
```
`npm run versioned:internal openai`
> fix: Updated instrumentation to handle the different exports in 4.40.1 of `openai`

- .github/workflows/ci-workflow.yml
This PR changes `ci.yml` to only run expensive linting and testing jobs if any JavaScript files have changed. In other words, docs changes or other repo maintenance will not trigger the long running CI jobs.
Note: we need to update the `main` branch protection rule to require the `all-clear` job to pass and remove the direct requirements on specific linting/testing jobs.
> chore: Updated CI to skip expensive actions when not needed

- .github/workflows/ci-workflow.yml
- .github/workflows/compatibility-report.yml
This PR resolves #2178. The result will be: after any PR is merged to `main` that contains changes to any json files under `test/versioned/` a new PR will be automatically opened that updates the `compatibility.md` document in the root of the repository.
The workflow can also be triggered manually.
The automatic PR will continually update the same branch+PR until such time as that PR has been merged. Subsequent changes will result in new PRs.
> chore: Added workflow for generating compatibility doc

- test/versioned/superagent/async-await.tap.js
- test/versioned/superagent/superagent.tap.js
- test/versioned/superagent/test-server.js
The superagent tests were making requests to the live `https://newrelic.com` server. Sometime between 2024-05-09 and 2024-05-10, that server started returning a 301 for requests in order to append a device parameter, e.g. `?device=desktop`.
This PR resolves that issue by making these tests query a local server.
> chore: Fixed superagent versioned tests

- lib/feature_flags.js
- test/smoke/index/index.tap.js
- test/smoke/newrelic.js
- test/unit/feature_flag.test.js
> chore: Removed unused express5 feature flag

- test/versioned/langchain/vectorstore.tap.js
In the case where `@langchain/core` is different than `@langchain/community`, the version of `@langchain/core` getting instrumented varies.  We have a test that asserts the `Supportability/Nodejs/ML/Langchain/<version` metric and it needed to be updated to get the right version.  This adds a try catch and tries to assert the `@langchain/core` version from `@langchain/community` first and if it does not exist falls back to the shared `@langchain/core` version.
```npm run versioned:internal langchain```
Closes #2201
> ci: Updated the langchain vectorstore test to reference the correct version of `@langchain/core` getting tested

- lib/instrumentation/@node-redis/client.js
- test/versioned/redis/package.json
- test/versioned/redis/redis-v4-legacy-mode.tap.js
We had a customer using some legacyMode of redis v4.  When you do that you access commands via `client.v4.<cmd>`.  We weren't instrumenting that object.  This PR fixes that.
`npm run versioned:internal redis`
Closes #2199
> feat: Added support for redis v4 legacyMode `client.v4.<command>`

- test/versioned/aws-sdk-v3/bedrock-chat-completions.tap.js
It seems that prior to #2208 we somehow lucked into always having `@smithy/smithy-client` available in the BedRock chat completions test suite import paths. But post that PR, the resolution will sometimes make it not directly available to that suite. This PR solves the issue by requiring it from the known good paths for it.
> chore: Fixed aws-sdk-v3 bedrock tests

- test/versioned/aws-sdk-v3/bedrock-chat-completions.tap.js
It seems like the passing versioned tests when I ran locally were a fluke. I managed to get a run locally that exhibits the CI failure (https://github.com/newrelic/node-newrelic/actions/runs/9211125804/job/25339758931), and that allowed me to inspect what is happening. It turns out that we have the following dependency tree for the actual agent:
```sh
❯ npm ls @smithy/smithy-client
newrelic@11.17.0 /Users/jsumners/Projects/team-repos/node-newrelic
├─┬ @aws-sdk/client-s3@3.582.0
│ ├─┬ @aws-sdk/client-sso-oidc@3.582.0
│ │ └── @smithy/smithy-client@3.0.1 deduped
│ ├─┬ @aws-sdk/client-sts@3.582.0
│ │ └── @smithy/smithy-client@3.0.1 deduped
│ ├─┬ @aws-sdk/core@3.582.0
│ │ └── @smithy/smithy-client@3.0.1 deduped
│ ├─┬ @aws-sdk/credential-provider-node@3.582.0
│ │ ├─┬ …
```
> chore: Fixed aws-sdk-v3 bedrock tests (again)

- .github/workflows/ci-workflow.yml
- .github/workflows/compatibility-report.yml
- package.json
> chore: Added updating of docs site with compat table

- .github/workflows/ci-workflow.yml
- .github/workflows/compatibility-report.yml
This PR is a follow-up to #2157. It:
1. Fixes generation of the pull request to the docs site.
2. Adds a workflow dispatch case to enable direct CI job runs.
We can see:
1. A successful run of the docs website PR generation at https://github.com/newrelic/node-newrelic/actions/runs/9273360076 (resulting in https://github.com/newrelic/docs-website/pull/17465)
2. Manual CI invocations ignoring the result of `should_run` and running all jobs at https://github.com/newrelic/node-newrelic/actions/runs/9273527204
> chore: Fixed CI jobs

- test/versioned/ioredis/ioredis-3.tap.js
- test/versioned/ioredis/ioredis.tap.js
This metric will be used to link APM entities to AWS Elasticache redis services.  We had an assertion in `redis` but not `ioredis`
```
npm run versioned:internal ioredis
```
Closes #2228
> test: Updated ioredis tests to assert the host metric getting created on ioredis calls

- .github/workflows/ci-workflow.yml
- package.json
- test/lib/agent_helper.js
- test/versioned/memcached/memcached.tap.js
- test/versioned/memcached/newrelic.js
- test/versioned/memcached/package.json
Migrated `memcached` tests to versioned tests. I put the minimum range at 2.2.0 as anything earlier than that fails to install on node 18/20
```
npm run versioned:internal memcached
```
Closes #2227
> test: Migrated `memcached` tests to versioned tests

- THIRD_PARTY_NOTICES.md
- compatibility.md
- package.json
- test/versioned/express/ignoring.tap.js
- test/versioned/hapi/ignoring.tap.js
- test/versioned/restify/pre-7/ignoring.tap.js
- third_party_manifest.json
* Updated @newrelic/security-agent to V1.3.0.
* Updated versioned tests for express, restify and hapi due to update in @newrelic/security-agent v1.3.0
* Due to update in invocation of instrumentation module for security agent, metric count has been changed.
```
npm run versioned:security
```
> chore: Updated versioned tests due to update in @newrelic/security-agent V1.3.0

- README.md
A little bit of clean-up I noticed is needed.
> chore: Updated readme to remove no longer relevant information

- lib/instrumentation/kafkajs.js
- lib/instrumentation/kafkajs/index.js
- lib/instrumentation/kafkajs/producer.js
- test/lib/agent_helper.js
- test/versioned/kafkajs/kafka.tap.js
> feat: Added kafkajs producer instrumentation

- test/versioned/when/when.tap.js
This PR updates a flaky test in the `when` suite. An instance of the failure can be seen at https://github.com/newrelic/node-newrelic/actions/runs/9364306171/job/25777040589#step:7:1319. The issue is that the GitHub Actions environment is inconsistent. It routinely runs things slower than they would otherwise execute. Given the variability of JavaScript timers, we really only need to verify that the provided delay is met.
> chore: Updated flaky when test

- lib/instrumentation/kafkajs.js
- lib/instrumentation/kafkajs/consumer.js
- lib/instrumentation/kafkajs/index.js
- lib/instrumentation/kafkajs/producer.js
- lib/shim/message-shim/subscribe-consume.js
- lib/shim/specs/message-subscribe.js
- lib/symbols.js
- lib/transaction/tracecontext.js
- package.json
- test/unit/distributed_tracing/tracecontext.test.js
- test/unit/shim/message-shim.test.js
- test/unit/shim/shim.test.js
- test/versioned/kafkajs/kafka.tap.js
- test/versioned/kafkajs/utils.js
This PR adds instrumentation for `kafkajs.Kafka.consumer.run`.  I did not instrument [eachBatch](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch). I'm not sure how we should handle this.  Our message shim handles transaction naming on a 1 message basis as it needs the topic name to name the consumption transaction.  For now we will defer until someone asks for it. I plan on adding a story to track if customers are using this method.  I had to tweak both the message-shim to allow to wrap a consumer when it is an object.  The consumer arg of MessageSpec is a number so i added `functions` to allow to wrap n functions at the position of the consumer.  Lastly, the traceparent and tracecontext are buffers so I had to handle parsing those as buffers.
```
npm run …
```
> feat: Added instrumentation for `kafkajs.Kafka.consumer`

- lib/instrumentation/amqplib/amqplib.js
- test/unit/metric/datastore-instance.test.js
- test/unit/shim/datastore-shim.test.js
- test/unit/shim/message-shim.test.js
- test/unit/shim/shim.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
I noticed a few unit tests were not constructing specs while doing kafkajs work.  This PR updates all places where tests are using shim and to properly construct specs/params for info it passes to the shim helper method.
> test: Updated unit tests that were missing constructing specs at instrumentation source

- lib/instrumentation/kafkajs/producer.js
- lib/shim/message-shim/index.js
- lib/shim/specs/message.js
- test/unit/shim/message-shim.test.js
- test/versioned/kafkajs/kafka.tap.js
- test/versioned/kafkajs/utils.js
> chore: Implemented DT header injection for message specs

- .github/workflows/compatibility-report.yml
- ai-support.json
- ai-support.spec.md
This PR is in support of #2253.
The purpose of this PR is to add a JSON file we can utilize in our docs automation to add documentation around which "AI" things we support, and how deep that support goes for each thing.
With the `ai-support.json` file in place, when our compatibility document automation is run it will generate a document that looks like the following:
<details>
<summary>Example report</summary>
```markdown
After installation, the agent automatically instruments with our catalog of
supported Node.js libraries and frameworks. This gives you immediate access to
granular information specific to your web apps and servers.  For unsupported
frameworks or libraries, you'll need to instrument the agent yourself using the
[Node.js agent …
```
> chore: Added AI support docs for automation

- .github/workflows/versioned-security-agent.yml
This PR updates the versioned security agent workflow to utilize the action I wrote for our baseline CI workflow. It should be a bit easier to understand and maintain.
> chore: Updated versioned security agent workflow with simpler setup

- docker-compose.yml
- package.json
It seems there was a release of Docker around 2024-06-11 that started showing what looks like a warning but is really an error that terminates `docker-compose up`:
https://github.com/newrelic/node-newrelic/actions/runs/9479735600/job/26126953241
> [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/zmarcantel/cassandra:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
This PR fixes it by updating the configuration.
> chore: Updated docker compose configuration

- dashboards/constants.js
- dashboards/generate-library-usage.js
- dashboards/library-usage.json
- dashboards/utils.js
This PR creates the script and framework to add other scripts to generate dashboard in NR 1.
```sh
node dashboards/generate-library-usage.js
cat dashboards/library-usage.json | jq .
```
This `.json` can be imported as a dashboard. You can see it in action [here](https://onenr.io/01wZdlBXEj6)
Closes #2265
> chore: Added a script that generates Dashboard json for reporting on libraries by version

- .github/workflows/versioned-security-agent.yml
> ci: Updated security agent workflow to use large runners when available

- .github/workflows/release-creation.yml
The serverless plugin uses this workflow.  It needs to run a build step before publishing. We never had this ability. This PR addes a new workflow input that allows you to pass in a boolean of `build: true` which will run build before publishing.
> ci: Added ability to run a build step in create release

- .github/workflows/ci-workflow.yml
- .github/workflows/notify-release.yml
- .github/workflows/post-release.yml
- .github/workflows/prep-release.yml
- .github/workflows/publish-branch.yml
- .github/workflows/release-creation.yml
- .github/workflows/repolinter.yml
- .github/workflows/smoke-test-workflow.yml
- .github/workflows/update-snyk-prs.yml
- .github/workflows/validate-pr.yml
- .github/workflows/versioned-coverage.yml
- .github/workflows/versioned-security-agent.yml
This PR updates all of the versions of the various actions we utilize.
1. It solves warnings like: 
2. It limits our usage of third party actions to specific commits. This is a guard against a potential attack where the action's floating `vX` tag could be re-pointed to a malicious commit. The only third party actions we "trust" are the actions under the `actions/` namespace (i.e. the ones maintained by GitHub directly).
3. There should not be any noticeable change in the outcome of the actions. The deprecation of version of Node used by actions does not affect the version of Node used by jobs.
4. GitHub is already forcing the change behind the scenes https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
A successful run of the …
> chore: Updated GitHub Actions versions

- api.js
- bin/create-docs-pr.js
- lib/config/attribute-filter.js
- lib/instrumentation/aws-sdk/util.js
- lib/shim/datastore-shim.js
- lib/transaction/name-state.js
- lib/util/hashes.js
- lib/utilization/docker-info.js
- lib/utilization/gcp-info.js
- test/integration/instrumentation/http-rum.tap.js
- test/unit/rum.test.js
- test/versioned/express/render.tap.js
- test/versioned/hapi/render.tap.js
- test/versioned/restify/pre-7/rum.tap.js
- test/versioned/restify/rum.tap.js
Most of the updates were clean. Only one that was referencing a negative index needed adjusted to work with substring.
Closes NR-82088
> refactor: Replaced instances of `substr()` with `substring()`

- ai-support.json
- lib/llm-events/aws-bedrock/bedrock-command.js
- lib/llm-events/aws-bedrock/bedrock-response.js
- lib/llm-events/aws-bedrock/stream-handler.js
- test/lib/aws-server-stubs/ai-server/index.js
- test/lib/aws-server-stubs/ai-server/responses/claude3.js
- test/lib/aws-server-stubs/ai-server/responses/index.js
- test/unit/llm-events/aws-bedrock/bedrock-command.test.js
- test/unit/llm-events/aws-bedrock/bedrock-response.test.js
- test/unit/llm-events/aws-bedrock/chat-completion-message.test.js
- test/unit/llm-events/aws-bedrock/chat-completion-summary.test.js
- test/unit/llm-events/aws-bedrock/stream-handler.test.js
- test/versioned/aws-sdk-v3/bedrock-chat-completions.tap.js
> feat: Added support for Anthropic Claude 3 messages API

- docker-compose.yml
- docker/Readme.md
- docker/mysql/my.cnf
- test/versioned/mysql/helpers.js
This PR resolves #2269.
We limit the Docker image to `mysql:8.3` because in 8.4 they removed the configuration we need in order to make our tests work with the `mysql` npm package. See 
+ https://dev.mysql.com/doc/refman/8.4/en/native-pluggable-authentication.html
+ https://web.archive.org/web/20240522184559/https://dnsmichi.at/2024/05/11/docker-compose-ghost-msql-8-4-msql-native-password-startup-errors-mitigation-solution/
+ https://github.com/mysqljs/mysql/pull/2233
> chore: Updated mysql tests to use MySQL 8.3

- test/versioned/mysql2/package.json
This PR fixes an issue in our CI introduced by #2280. The problem is tied to https://github.com/sidorares/node-mysql2/issues/1398. In short, `mysql2@1` relies on `iconv-lite@0.4.8` which does not have an encoding mapping that MySQL server 8+ requires. The fix for the `mysql2` driver is to update to at least version 2.0.0. Given the details outlined in #2269 , I have updated updated our versioned tests to minimally test against `mysql@2.0.0`. The consequence is that we do not have coverage for v1 of `mysql2` (which was last released 2019-08-28 according to npm).
Internally, I can see some usage of the v1 line with v11 of our agent, but the total number at the time of this writing is 16 instances. All other usages of `mysql2@1` are on older versions of the agent and still only totals some …
> chore: Updated mysql2 tests to fix CI issue

- test/versioned/elastic/package.json
`@elastic/elasticsearch` 8.14.0 no longer works on Node 16 https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.14/changelog-client.html
The cause is https://github.com/elastic/elasticsearch-js/pull/2277.
> chore: Made elastic versioned tests work on Node 16

- api.js
Just some typo corrections and clarifying custom attributes are added to the active Span as well as the Transaction
> fix: typos

- lib/utilization/docker-info.js
- test/unit/facts.test.js
- test/unit/utilization/aws-ecs-api-response.json
- test/unit/utilization/docker-info.test.js
> feat: Added support for getting container ids from ECS metadata API

- lib/serverless/api-gateway.js
- test/unit/serverless/api-gateway-v2.test.js
Added defensive code to handle when no headers are present.
```sh
node test/unit/serverless/api-gateway-v2.test.js
```
Fixes #2291
> fix: Handled assigning headers in LambdaProxyWebRequest when there are no headers present

- test/unit/api/api-record-log-events.test.js
For unit tests, logMessage["error.stack"] is truncated at 1024 characters and last three chars are replaced with ellipses. If error.stack exceeds 1021 chars, the equality test fails. Solution was to compare only the first 1021 chars.
> test: fixed log error stack message truncating and failing equality test

- bin/publish-docs.sh
This PR resolves #2301. Instead of trying to merge in changes to the `gh-pages` branch, we simply recreate it every time.
> chore: Forced re-creation of API docs on gh-pages

- lib/errors/error-collector.js
- test/unit/errors/error-collector.test.js
- Refactored _processUserErrors, _processTransactionExceptions, and _processTransactionErrors into a single function: _processErrors
Original Ticket:
- There's a lot of duplication here--for example, in the error-collector, _processUserErrors and _processTransactionExceptions are nearly identical, apart from the property they inspect. _processTransactionErrors behaves only slightly differently. Those three could be collapsed into one processor.
- First half of this Jira ticket (https://new-relic.atlassian.net/browse/NR-96722)
> refactor: reduce duplication in the error-collector

- documentation/developer-setup.md
- As part of rewriting the Node.js Onboarding Agenda on Confluence, this document needs to be updated to better accommodate early-career devs / freshers. 
- Included links and commands for a quicker machine setup
> docs: included commands and links for mac setup

- lib/errors/index.js
- Got rid of the `isExpected` function in the Exception class to avoid duplication with the `isExpected` function in the error helper.
> refactor: got rid of redundant isExpected in the Exception class

- .github/workflows/post-release.yml
In #2307 we implemented a fix for the local `gh-pages` publishing occasionally failing due to branch mismatches. However, the next time it ran there was a failure due to a branch protection. Upon fixing the branch protection, and attempting to re-run the workflow, another error was encountered: the step for publishing to the docs website does not account for the PR already existing. This revision separates the two jobs such that they can be run independently when needed.
> chore: Implemented split jobs for post release docs publishing

- .github/workflows/post-release.yml
> chore: Fixed copy paste error in post release workflow

- THIRD_PARTY_NOTICES.md
- package.json
- third_party_manifest.json
thanks isaacs,
So apparently we're dropping support for EOL versions in patches now.  I get the frustration but this author's deps are intertwined in some core packages.  This should probably go in `@newrelic/native-metrics` but it doesn't fail when installing as a standalone just in the agent for some reason.
```
npm run unit
```
> fix: Pinned dependenices of node-gyp that dropped support for Node 16 in patch releases

- test/benchmark/datastore-shim/test-datastore.js
- test/benchmark/promises/shared.js
- test/lib/benchmark.js
Benchmark tests for datastore-shim and promises were throwing an error: when run, and benchmark stats were generated, the stat constructor failed, as there were no values in samples. The tests used both callbacks and async/await, so the stats were invoked before the async promises were resolved. This PR removes the async-handling callback code path, so async tests aren't expected to fire a callback on completion. 
`npm run bench datastore-shim`
`npm run bench promises`
Closes NR-67805
Closes NR-281838
> fix: Refactored benchmark tests to complete async functions

- THIRD_PARTY_NOTICES.md
- package.json
- third_party_manifest.json
This reverts commit 7dab36d35582ff23e3ba0764ef06fcf3f0f030f1.
Looks like author reverted this issue. You can follow along [here](https://x.com/matteocollina/status/1810371377867927585). I'm backing this out because I'd rather not provide overrides.
> chore: Revert "fix: Pinned dependenices of node-gyp that dropped support for Node 16 in patch releases (#2333)"

- lib/config/index.js
- lib/instrumentation/aws-sdk/v3/bedrock.js
- lib/instrumentation/langchain/common.js
- lib/instrumentation/langchain/runnable.js
- lib/instrumentation/langchain/tools.js
- lib/instrumentation/langchain/vectorstore.js
- lib/instrumentation/openai.js
- test/unit/config/config-server-side.test.js
- test/unit/instrumentation/langchain/runnables.test.js
> feat: Added support for account level governance of AI Monitoring

- lib/instrumentation/@node-redis/client.js
- lib/symbols.js
- test/unit/instrumentation/redis.test.js
- test/versioned/redis/redis-v4.tap.js
- test/versioned/redis/redis.tap.js
In redis pre 4 we were able to instrument the underlying command executor which traced all running commands. In v4 we tried to instrument all commands attached to client.  This did not work with transactions(multi + exec).  This PR refators the instrumentation to wrap the redis commands queue `addCommand` which is the equivalent of the pre v4 instrumentation.  
```
npm run versioned:internal redis
```
Closes #2339
> fix: Updated redis v4 instrumentation to work with transactions(multi/exec)

- .github/workflows/compatibility-report.yml
If `nrversions` crashes for whatever reason, we want to still be able to read the log file.
> chore: Always upload status logs in compat report CI

- bin/run-versioned-tests.sh
While I was helping Amy refactor `@newrelic/test-utilitites`. I noticed we manage [2 separate queues for running tests and installing packages within the test](https://github.com/newrelic/node-test-utilities/blob/main/lib/versioned/suite.js#L140).  The install limit is 1 but we set it to 2 and the test limit defaults to number of CPUs or in CI we default to 4 if not using the larger runner.  However since the test is kicked off first then queues up the install, you'll have a discrepancy in waiting for concurrent test runs and it'll show a `waiting`.  This PR increases the install limit to a larger number 100 which can't really go above the jobs limit but it should speed up the tests slighty as it's not queueing up installs of tests.  I plan on removing this 2nd queue in test utils but …
> ci: increase the limit of installs from 2 to a bigger number

- .gitignore
- bin/compare-bench-results.js
- bin/run-bench.js
- package.json
- test/benchmark/async-hooks.bench.js
- test/benchmark/datastore-shim/recordBatch.bench.js
- test/benchmark/datastore-shim/recordOperation.bench.js
- test/benchmark/datastore-shim/recordQuery.bench.js
- test/benchmark/datastore-shim/test-datastore.js
- test/benchmark/http/server.bench.js
- test/benchmark/promises/native.bench.js
- test/benchmark/promises/shared.js
- test/lib/benchmark.js
Updated `run-bench.js` and `benchmark.js` to complete asynchronous tests before generating statistics
Updated `run-bench.js` to allow JSON output to a file, and consolidate printing logic
Reduced cognitive complexity in `run-bench.js`
`npm run bench` to run benchmark tests and output json result files to `benchmark_results`
Given two benchJson outputs, `node bin/compare-bench-results.js {file1.json} {file2.json}`  will compare two benchmark runs, and write a markdown file to `benchmark_results`.
Closes NR-281645
> test: Updated benchmark test results to output result files 

- .github/workflows/benchmark-tests.yml
- bin/run-bench.js
Added benchmark test GitHub Action, which automatically writes the output to a file in `benchmark_results`. The file is named with the git branch and Node version, which are supplied by the action. 
When this action is run, it verifies that it's written a file to the output by running `ls` on the output directory. File contents aren't inspected, but it's a baseline check that the benchmark test did not fail.
Closes #2118 
Closes NR-255566
> ci: Added benchmark test GitHub Action

- test/integration/grpc/reconnect.tap.js
- test/integration/infinite-tracing-connection.tap.js
I noticed when adding support for Node 22 we had some deprecation warnings.  
```sh
(node:98461) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
When adding `--trace-deprecation` to the entire integration run I discovered
```sh
(node:99014) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.
at /Users/revans/code/pull-requests/node-newrelic/test/integration/grpc/reconnect.tap.js:221:16
at /Users/revans/code/pull-requests/node-newrelic/node_modules/@grpc/grpc-js/src/server.ts:869:11
at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
It also existed in another grpc test.  
`node test/integration/grpc/reconnect.tap.js` …
> test: Removed server.start in grpc tests as it is deprecated and no longer needed

- lib/instrumentation/cassandra-driver.js
- test/versioned/cassandra-driver/query.tap.js
- Added promise based query test
- Added slow query test
- Refactored some code for cleaner tests
- Added `promise: true` to shim to enable promise based querying
Run versioned test for cassandra-driver
> fix: Updated cassandra-driver instrumentation to properly trace promise based executions

- .github/workflows/board.yml
I added a new custom field called `Date created` to the project board and backfilled all issues, didn't worry about PRs. but now you can set the sort order by date created to see most recent at top of every column
> ci: Include date created when adding new issue/pr to board

- .github/workflows/benchmark-tests.yml
- .github/workflows/ci-workflow.yml
- .github/workflows/smoke-test-workflow.yml
- .github/workflows/versioned-coverage.yml
- .github/workflows/versioned-security-agent.yml
Looks like [Node 22.5.0](https://github.com/nodejs/node/issues/53902) broke npm install.  This PR pins to 22.4.1 so our CI can continue to run properly.
> ci: Pin Node 22 to 22.4.1

- lib/instrumentation/aws-sdk/v3/common.js
I think the bug describes it all.  I was worried about this fix after digging deep into the middleware that get called.  However, it was just explicitly stating the priority to ensure the response from our middleware is the IncomingMessage and we can get the active external http span
```sh
npm run versioned:internal aws-sdk-v3
```
Closes #2378
> fix: Updated aws-sdk v3 instrumentation to custom middleware last to properly get the external http span to add aws.* attributes

- .github/workflows/benchmark-tests.yml
- .github/workflows/ci-workflow.yml
- .github/workflows/smoke-test-workflow.yml
- .github/workflows/versioned-coverage.yml
- .github/workflows/versioned-security-agent.yml
Reverts newrelic/node-newrelic#2375
GitHub fixed the Actions infra this morning. We should be able to revert this now.
> chore: Reverted "ci: Pin Node 22 to 22.4.1"

- documentation/developer-setup.md
Fixed the project dashboard links in developer-setup.md
> chore: Updated dashboard links in developer-setup.md

- test/versioned/mysql/basic.tap.js
- test/versioned/mysql2/basic.tap.js
> chore: Verified MySQL host:port metric is recorded

- test/versioned/aws-sdk-v3/package.json
This should fix an issue exposed in #2401. The versions used as minimums were derived by examining what was available when support was first added to the agent.
> chore: Add test configs for defined targets in the aws test suite

- lib/instrumentation/redis.js
The jira ticket stated removing support for <2.6.1 however after testing it's <2.6.0.  I was able to cleanup other parsing of the client to get the host/port/db.
```
npm run versioned:internal redis
```
No Github issue but Jira:
Closes NR-95813
> feat!: Removed support for `redis` < 2.6.0

- lib/instrumentation/amqplib/amqplib.js
- lib/instrumentation/amqplib/channel-model.js
- lib/instrumentation/amqplib/channel.js
- lib/instrumentation/amqplib/utils.js
- lib/shim/message-shim/consume.js
- lib/shim/message-shim/index.js
- lib/shim/message-shim/subscribe-consume.js
- lib/shim/specs/params/queue-message.js
- lib/spans/span-event.js
- lib/spans/streaming-span-event.js
- lib/symbols.js
- test/unit/shim/message-shim.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
- test/versioned/amqplib/amqp-utils.js
- test/versioned/amqplib/callback.tap.js
This PR reorganized the `amqplib` instrumentation by relevant files being instrumented.  It also adds getting the connection information from the channel and storing on a symbol for reuse.  I also had to refactor `message-shim` methods to allow specs to functions and passing the proper `this` context to the spec which allowed me to get the connection information from the socket.  I then added `host`, `port` as segment attributes and added tests to assert that. Lastly, moved assigning `server.address` and `server.port` from the specific span classes to the generic class. 
**Note**: There are cases that `server.address` and `server.port` are being assigned from different attributes so I kept that.
Closes #2388
> feat: Added `server.address` to amqplib spans

- examples/shim/Datastore-Simple.md
- examples/shim/Messaging-Simple.md
- examples/shim/Webframework-Simple.md
I know we're trying to phase these examples out but they are still relied upon by customers.  This PR updates the examples to properly construct specs.
> docs: Updated examples to properly use specs

- lib/instrumentation/pino/pino.js
- test/versioned/pino/pino.tap.js
> fix: Pick log message from merging object in Pino instrumentation

- documentation/nextjs/faqs/error-handling.md
_Injecting Browser Agent_ -> _Error Handling_
> fix: typo in doc header

- THIRD_PARTY_NOTICES.md
- package.json
- test/lib/fake-cert.js
- test/lib/promise-resolvers.js
- test/lib/test-collector.js
- test/unit/agent/agent.test.js
- test/unit/agent/intrinsics.test.js
- test/unit/agent/synthetics.test.js
- test/unit/instrumentation/mysql/wrapCreatePoolCluster.test.js
- third_party_manifest.json
This PR resolved #2380.
There are couple of main differences between `tap` and `node:test` patterns:
1. In `node:test` every `test()` is actually a promise.
2. In `node:test` every test function is wrapped in a promise.
3. In `node:test` there is not a subtest `.end` or `.autoEnd` concept.
So if we have a `tap` test like:
```js
tap.test('some stuff', t => {
t.test('one', t => {
t.equal(1, 1)
})
t.test('two', t => {
foo('bar', (error, val) => {
t.error(error, 'no error should occur')
t.equal(val, 'bar')
t.end()
})
function foo(param, cb) {
cb(param)
}
})
})
```
The equivalent in `node:test` would be:
```js
test('some stuff', async t => {
await t.test('one', t => {
assert.equal(1, 1)
})
await t.test('two', async t => {
const { promise, resolve } = Promise.withResolvers()
foo('bar', (error, …
```
> chore: Converted agent unit tests to node:test

- test/versioned/mongodb-esm/bulk.tap.mjs
- test/versioned/mongodb-esm/collection-common.mjs
- test/versioned/mongodb-esm/collection-find.tap.mjs
- test/versioned/mongodb-esm/collection-index.tap.mjs
- test/versioned/mongodb-esm/collection-misc.tap.mjs
- test/versioned/mongodb-esm/collection-update.tap.mjs
- test/versioned/mongodb-esm/common.cjs
- test/versioned/mongodb-esm/cursor.tap.mjs
- test/versioned/mongodb-esm/db.tap.mjs
- test/versioned/mongodb-esm/newrelic.cjs
- test/versioned/mongodb-esm/package.json
- test/versioned/mongodb/collection-common.js
- test/versioned/mongodb/common.js
- test/versioned/mongodb/db-common.js
abstracted the common code and share between cjs and esm mongodb tests,
I was able to fix the issues when running the two suites together. I updated esm tests to rely on the cjs common and added new db, collections and prefix for ESM based tests.
```sh
NR_LOADER=./esm-loader.mjs npx c8 -o ./coverage/versioned --merge-async -r lcov ./node_modules/.bin/versioned-tests --major --print pretty -i 100 --all --strict --samples 10 test/versioned/mongodb-esm test/versioned/mongodb
```
Closes #2417
> test: Restored mongodb-esm tests

- lib/instrumentation/aws-sdk/v3/sqs.js
- test/lib/aws-server-stubs/response-server/index.js
- test/lib/aws-server-stubs/response-server/sqs/index.js
- test/versioned/aws-sdk-v3/sqs.tap.js
> chore: Added entity relationship attributes to SQS segments

- test/versioned/mongodb/collection-common.js
- test/versioned/mongodb/collection-misc.tap.js
- test/versioned/mongodb/collection-update.tap.js
- test/versioned/mongodb/common.js
This _should_ fix the CI failures where the ESM tests couldn't find `mongodb/package.json` as it was looking in the CJS tests.
> test: Moved pkgVersion to collection-common to avoid a conflict with ESM tests

- test/versioned/superagent/package.json
This PR omits the latest `superagent` release (https://github.com/ladjs/superagent/releases/tag/v10.0.0) from the versioned test matrix as it causes test failures. This will allow our CI to continue working while we investigate.
> chore: Limited superagent tests to avoid new breaking release

- test/unit/agent/agent.test.js
- test/unit/agent/synthetics.test.js
This PR removes the promise resolvers workaround from the agent unit tests. I discovered that the test function supports a second `done`/`end` parameter that is a function to be invoked when the test is complete.
Note:
```js
// This test will not work as the promise from the `async` takes precedence:
test('something', async (t, end) => {
someCallback('does something', (error) => {
end(error)
})
})
// This test will work as expected because no promises are involved:
test('something', (t, end) => {
someCallback('does something', (error) => {
end(error)
})
})
// If we need async operations, we should still use promise resolvers:
test('something', async (t) => {
const { promise, resolve, reject } = Promise.withResolvers()
const aThing = await getThing()
someCallback('does something', { with: …
```
> chore: Remove promise resolvers from callback based agent unit tests

- lib/instrumentation/pino/pino.js
Removes the ignoring of checking for cognitive complexity. resolved it by separating out the instrumentation for `asJson`
Closes #2424
> refactor: Updated pino instrumentation to separate the wrapping of asJson into its own function

- lib/instrumentation/@node-redis/client.js
- test/unit/instrumentation/redis.test.js
- test/versioned/redis/redis-v4-legacy-mode.tap.js
…ot provided
This PR addresses handling parsing host/port when provided to connect when assigning host and port on the spans for redis
```sh
npm run versioned:internal redis
```
Closes #2462
> fix: Updated redis instrumentation to parse host/port when a url is not provided

- lib/instrumentation/express.js
- test/lib/metrics_helper.js
- test/versioned/express-esm/package.json
- test/versioned/express-esm/segments.tap.mjs
- test/versioned/express-esm/transaction-naming.tap.mjs
- test/versioned/express/app-use.tap.js
- test/versioned/express/async-handlers.tap.js
- test/versioned/express/bare-router.tap.js
- test/versioned/express/client-disconnect.tap.js
- test/versioned/express/errors.tap.js
- test/versioned/express/middleware-name.tap.js
- test/versioned/express/newrelic.js
- test/versioned/express/package.json
- test/versioned/express/render.tap.js
- test/versioned/express/route-iteration.tap.js
- test/versioned/express/segments.tap.js
- test/versioned/express/transaction-naming.tap.js
- test/versioned/express/utils.js
- test/versioned/koa/package.json
This originally started as a research spike to see what broke. It turns out not much so I just PRd support for express 5 beta.  We will not officially support it because it hasn't been released as generally available.  We will keep tabs on any upcoming beta releases and remove the test stanzas when 5.0.0 is out.  I will make sure when this lands to include a secondary changelog item to state this is not officially supported just yet.
Most of the changes are around how child applications are mounted.  In v4 they used to be mounted as applications, now they are just mixed in.  You can see a difference here:
* [express 4](https://github.com/expressjs/express/blob/2177f67f5439494f7a29a8d04f744cc20fb9f201/lib/application.js#L221) - it would create a lazyrouter which registered query, and …
> feat: Added instrumentation support for Express 5 beta

- README.md
Updated the README file to remove the reference to the @newrelic/next package as it has been merged into this one, and no longer needs to be installed separately.
Docs only change.
None.
> docs: Remove reference to @newrelic/next in README

- lib/instrumentation/koa/instrumentation.js
- test/versioned/koa/package.json
- test/versioned/koa/router-common.js
…
This PR removes skipping `@koa/router@13.0.0`+.  There were too big changes:
* allowedMethods middleware is no longer a named function so I updated the tests to handle this
* Fixed instrumentation to properly name segments/transactions for nested routers.  Turns out we had a test that defined both `:/wildcard`, and `/specific`, in this case it should match the wildcard which it does but our segment/transaction naming was using the `/specific` which was incorrect.
```sh
npm run versioned:internal koa
```
Closes #2477
> fix: Updated koa instrumentation to properly get the matched route name and to handle changes in `@koa/router@13.0.0`

- .github/workflows/ci-workflow.yml
We were pinning the codecov-action to a sha that no longer works for posting coverage on PRs. I also enabled `fail_ci_if_error: true` to fail CI so we can catch issues in the future. This PR won't exercise the upload but I did have a past run that tested it [here](https://github.com/newrelic/node-newrelic/actions/runs/10456783167)
Closes #2485
> ci: Updated codecov action sha to post coverage from forks.  Added flag to fail ci if it fails to upload report

- lib/serverless/api-gateway.js
- test/unit/serverless/api-gateway-v2.test.js
- test/unit/serverless/fixtures.js
- test/unit/serverless/lambda-sample-events.js
- test/unit/serverless/utils.test.js
> fix: Improved AWS Lambda event detection

- api.js
I noticed our jsdoc formatting was off for examples. This PR fixes that formatting
```sh
npm run public-docs
open out/index.html
```
> docs: cleaned up formatting of api.js to properly inject example snippets when rendering on API docs site

- test/unit/custom-events/custom-event-aggregator.test.js
- test/unit/distributed_tracing/dt-cats.test.js
- test/unit/distributed_tracing/dt-payload.test.js
- test/unit/distributed_tracing/tracecontext.test.js
This PR resolves https://github.com/newrelic/node-newrelic/issues/2526.
> test: Replace distributed tracing tests with `node:test`

- documentation/nextjs/faqs/cloud-providers.md
Updated the FAQ for using Next.js in cloud providers(Vercel, AWS Amplify, etc) with OpenTelemetry.
Closes #2534
> docs: Updated Next.js Otel cloud provider FAQ

- test/lib/custom-assertions.js
This PR adds a `match` function that is equivalent to Tap's `t.same`.
> chore: Added a match function for tests

- lib/serverless/api-gateway.js
- test/unit/serverless/api-gateway-v2.test.js
- test/unit/serverless/fixtures.js
- test/unit/serverless/utils.test.js
> fix: Fixed detection of REST API type payloads in AWS Lambda

- lib/collector/api.js
- test/lib/assert-metrics.js
- test/lib/test-collector.js
- test/unit/collector/api-connect.test.js
- test/unit/collector/api-login.test.js
- test/unit/collector/api-run-lifecycle.test.js
- test/unit/collector/api.test.js
- test/unit/collector/http-agents.test.js
- test/unit/collector/key-parser.test.js
- test/unit/collector/parse-response.test.js
- test/unit/collector/remote-method.test.js
- test/unit/collector/serverless.test.js
> chore: Converted collector unit tests to node:test

- package.json
- test/unit/llm-events/aws-bedrock/bedrock-command.test.js
- test/unit/llm-events/aws-bedrock/bedrock-response.test.js
- test/unit/llm-events/aws-bedrock/chat-completion-message.test.js
- test/unit/llm-events/aws-bedrock/chat-completion-summary.test.js
- test/unit/llm-events/aws-bedrock/embedding.test.js
- test/unit/llm-events/aws-bedrock/error.test.js
- test/unit/llm-events/aws-bedrock/event.test.js
- test/unit/llm-events/aws-bedrock/stream-handler.test.js
- test/unit/llm-events/error.test.js
- test/unit/llm-events/feedback-message.test.js
- test/unit/llm-events/langchain/chat-completion-message.test.js
- test/unit/llm-events/langchain/chat-completion-summary.test.js
- test/unit/llm-events/langchain/event.test.js
- test/unit/llm-events/langchain/tool.test.js
- test/unit/llm-events/langchain/vector-search-result.test.js
- test/unit/llm-events/langchain/vector-search.test.js
- test/unit/llm-events/openai/chat-completion-message.test.js
- test/unit/llm-events/openai/chat-completion-summary.test.js
- test/unit/llm-events/openai/embedding.test.js
This PR resolves https://github.com/newrelic/node-newrelic/issues/2533.
> test: Converted `llm-events` tests to use `node:test`

- lib/config/index.js
- test/unit/errors/error-collector.test.js
- test/unit/errors/error-event-aggregator.test.js
- test/unit/errors/error-group.test.js
- test/unit/errors/error-trace-aggregator.test.js
- test/unit/errors/expected.test.js
- test/unit/errors/ignore.test.js
- test/unit/errors/server-config.test.js
> chore: Converted errors unit tests to node:test

- test/unit/util/application-logging.test.js
- test/unit/util/async-each-limit.test.js
- test/unit/util/byte-limit.test.js
- test/unit/util/camel-case.test.js
- test/unit/util/code-level-metrics.test.js
- test/unit/util/codec.test.js
- test/unit/util/hashes.test.js
- test/unit/util/label-parser.test.js
- test/unit/util/llm-utils.test.js
- test/unit/util/logger.test.js
- test/unit/util/obfuscate-sql.test.js
- test/unit/util/objects.test.js
- test/unit/util/snake-case.test.js
> test: Migrated `test/unit/util` to use `node:test`

- test/versioned/express-esm/package.json
- test/versioned/express/package.json
`express@5` was released on 2024-09-09. It has some incompatibility with the security agent tests. This PR disables it for the time being.
https://github.com/newrelic/node-newrelic/actions/runs/10789319338/job/29922071924
+ [x] https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/321 is required first.
> chore: Disable express@5 in versioned tests

- test/unit/spans/base-span-streamer.test.js
- test/unit/spans/batch-span-streamer.test.js
- test/unit/spans/create-span-event-aggregator.test.js
- test/unit/spans/map-to-streaming-type.test.js
- test/unit/spans/span-event-aggregator.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/span-streamer.test.js
- test/unit/spans/streaming-span-attributes.test.js
- test/unit/spans/streaming-span-event-aggregator.test.js
- test/unit/spans/streaming-span-event.test.js
Migrated `test/unit/spans` tests to `node:test`.
Closes #2550
> test: Migrated `test/unit/spans` to use `node:test`

- lib/config/build-instrumentation-config.js
- lib/config/default.js
- lib/shimmer.js
- test/lib/custom-assertions.js
- test/lib/metrics_helper.js
- test/unit/config/build-instrumentation-config.test.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-env.test.js
- test/versioned/disabled-instrumentation/disabled-express.test.js
- test/versioned/disabled-instrumentation/disabled-ioredis.test.js
- test/versioned/disabled-instrumentation/newrelic.js
- test/versioned/disabled-instrumentation/package.json
Provides a new configuration stanza of `config.instrumentation.<library>.enabled` to disable every 3rd party library.  
* Use at your own risk. 
* Disabling instrumentation for a 3rd party library may affect instrumentation of libraries used after the disabled library. 
```sh
npm run versioned:internal major disabled-instrumentation
```
Closes #2536
> feat: Provided ability to disable instrumentation for a 3rd party package

- .github/workflows/azure-site-extension.yml
Site extension publishing was tested on a fork; the filename structure there successfully used a `.` before the semver value in the expected filename. The previous workflow specified a hyphen before the semver value, which does not match the file generated by `nuget pack`.
GHA workflows can only be run after merge to main, though arguably this could be tested in a fork.
This fix is a subtask of NR-300597
> fix: Nuget pack generates packagName.semver and not packageName-semver

- lib/agent.js
- lib/aggregators/base-aggregator.js
- lib/collector/api.js
- lib/config/index.js
- lib/errors/error-collector.js
- lib/harvester.js
- lib/metrics/normalizer.js
- lib/spans/streaming-span-event-aggregator.js
- lib/transaction/index.js
- lib/transaction/transaction-event-aggregator.js
- lib/util/stream-sink.js
- test/integration/newrelic-harvest-limits.tap.js
- test/integration/newrelic-response-handling.tap.js
- test/unit/aggregators/base-aggregator.test.js
- test/unit/collector/api.test.js
- test/unit/harvester.test.js
- test/unit/trace-aggregator.test.js
- test/unit/transaction-event-aggregator.test.js
While working on #2548 I needed to understand when some events are firing and learned that we do not have any documentation around events. Ideally, we'd have a document that outlines the common event sequences, but I don't have that picture right now. What this PR includes is jsdoc for almost every event the codebase generates. There is a whole class events in the `Config` namespace that I could not document. These events are emitting events named after configuration keys. There are two problems here:
1. It's not clear what the event names will actually be. As an example, what would be fired if `enabled` from `{ feature_name: { enabled: true } }` is changed to `false`? Would the event name be `enabled`, `feature_name`, or something like `feature_name.enabled`?
2. There's no way to …
> chore: Document emitted events

- cloud-tooling/README.md
- cloud-tooling/azure-site-extension/NewRelic.Azure.WebSites.Extension.NodeAgent.nuspec
The new Azure site extension contains an informative README.md which was not displaying on the nuget.org site. This PR adds a tag to the .nuspec file, allowing display. 
I've tested this with a renamed site extension from my fork, and can provide the link. 
Closes #2558
Closes NR-311749
> fix: Ensure Readme displays for Azure site extension

- test/versioned/koa/package.json
This is to get CI working for the weekend.
> chore: Reduce koa-router version to enable CI

- test/unit/adaptive-sampler.test.js
- test/unit/analytics_events.test.js
- test/unit/apdex.test.js
- test/unit/attributes.test.js
> chore: Migrate block of unit tests to `node:test`

- test/unit/db_util.test.js
- test/unit/environment.test.js
- test/unit/error_events.test.js
> chore: Migrate second block of unit tests to `node:test`

- .github/workflows/azure-site-extension.yml
This PR adds a trigger to the GitHub Actions workflow that publishes the agent as an Azure Site Extension. If a version of the agent is successfully released to NPM, this workflow will then publish to nuget.
I've tested in this fork with a different workflow as the trigger: https://github.com/mrickard/node-newrelic/actions/runs/10856411190 was triggered by a workflow that optionally succeeded or failed, based on user input: https://github.com/mrickard/node-newrelic/actions/runs/10856407943
Closes #2559 
Closes NR-311751
> ci: Added workflow run trigger to Azure site extension publish job

- test/versioned/aws-sdk-v2/package.json
- test/versioned/aws-sdk-v3/package.json
- test/versioned/grpc/package.json
- test/versioned/langchain/package.json
- test/versioned/nextjs/package.json
- test/versioned/prisma/package.json
We ran into a problem with langchain, and have hit this over the years with other libraries where the versioned tests matrix has conflicts between the transitive dep and package under test. This PR removes all transitive deps, could not remove `pg-native` as it wasn't a peer dep until later.  In versioned tests where it relies on implicitly testing instrumentation I have added `minSupported` to the targets stanza so our nr-versions go util can still mark the package as supported
Closes #2579
> test: Removed transitive deps from versioned tests as they will auto-install if required as peer deps

- test/versioned/koa/package.json
- test/versioned/koa/router-common.js
koa router had two fixes: https://github.com/koajs/router/pull/189 and https://github.com/koajs/router/pull/183 which broke our versioned tests.  This PR handles the nuance from 13.0.1+
```sh
npm run versioned:internal koa
```
I know a fix was made in #2576 but there was still one failing test, this fixes both.
> test: Updated koa-router to tests to handle bug fixes from 13.0.1

- test/versioned/aws-sdk-v3/package.json
Missed `minSupported` and messed up `@smithy/smithy-client`
> test: Updated a missing `minSupported` in aws-sdk-v3 versioned tests

- test/unit/util/obfuscate-sql.test.js
Refactors the `test/unit/util/obfuscate-sql.test.js` script to generate less noise.
> chore: Removed noisy test log

- test/versioned/fastify/add-hook.tap.js
- test/versioned/fastify/code-level-metrics-hooks.tap.js
- test/versioned/fastify/code-level-metrics-middleware.tap.js
- test/versioned/fastify/errors.tap.js
- test/versioned/fastify/naming-common.js
- test/versioned/fastify/new-state-tracking.tap.js
Doing `fastify.listen(0)` no longer works in `fastify@5`. This PR updates all references of `.listen` to pass in an object of `{ port: 0 }`
```sh
npm run versioned:internal:major fastify
```
> test: Updated fastify versioned tests to work with `fastify@5.0.0`

- test/versioned/koa/router-common.js
I described the issue [here](https://github.com/koajs/router/issues/192). This PR fixes this nuance for now until I can get confirmation.
> test: Fixed @koa/router tests. path-to-regex differs between @koa/router and koa-router now

- test/versioned/koa/package.json
- test/versioned/koa/router-common.js
Both `koa-rotuer` and `@koa/router` 13.0.1 use `path-to-regexp@8` but `@koa/router` released 13.1.0 and downgraded `path-to-regexp@6`. This PR updates how we determined how to defined wildcard routes by keying off the version of `path-to-regexp` when present. If it is not present assume the legacy behavior.
```sh
npm run versioned:internal koa
```
```sh
===============================================================
✓ koa (100) 3m
===============================================================
Versions executed
Folder: koa
* koa(5): 2.0.1, 2.4.1, 2.8.2, 2.12.1, 2.15.3
* koa-router(3): 11.0.2, 12.0.1, 13.0.1
* @koa/router(4): 11.0.2, 12.0.2, 13.0.1, 13.1.0
* koa-route(4): 3.0.0, 3.1.0, 3.2.0, 4.0.1
===============================================================
PASS
```
I suspect they …
> test: Updated how we handle the koa-router nuance of wildcard routes

- THIRD_PARTY_NOTICES.md
- package.json
- third_party_manifest.json
* Dropped support for Node.js v16
* Dropped functionality to generate snapshot file
* Support to honour proxy settings via config
* Support for secure cookie security event generation
* Report error to Error Inbox upon connection failure to Security Engine
* Support to detect application and server path
* Functionality to truncate Incoming HTTP request upto default limit
* Dropped support for Node.js v16
* Dropped functionality to generate snapshot file
* Handling for empty data in IAST fuzzing header
* Added identifiers in events
* Fix for file integrity security event generation
* Fix for missing identifiers in iast-data-request JSON
> chore(deps): Udpated @newrelic/security-agent to v2.0.0

- lib/instrumentation/pino/pino.js
- test/versioned/pino/issue-2595.test.js
- test/versioned/pino/package.json
> fix: Fixed handling of Pino merging object

- test/lib/custom-assertions.js
- test/unit/shim/conglomerate-shim.test.js
- test/unit/shim/datastore-shim.test.js
- test/unit/shim/message-shim.test.js
- test/unit/shim/promise-shim.test.js
- test/unit/shim/shim.test.js
- test/unit/shim/transaction-shim.test.js
- test/unit/shim/webframework-shim.test.js
Migrated the shim unit tests.  
```sh
npx c8 -o ./coverage/unit node_modules/.bin/borp --timeout 180000 --reporter ./test/lib/test-reporter.mjs 'test/unit/shim/*.test.js'
```
Closes #2566
> test: Migrated `test/unit/shim` to `node:test`

- test/unit/index.test.js
- test/unit/instrumentation-descriptor.test.js
- test/unit/instrumentation-tracker.test.js
- test/unit/is-absolute-path.test.js
- test/unit/util/is-absolute-path.test.js
> chore: Migrate block of unit tests to node:test

- test/unit/serverless/api-gateway-v2.test.js
- test/unit/serverless/aws-lambda.test.js
- test/unit/shim/message-shim.test.js
- test/unit/shim/shim.test.js
- test/versioned/express/app-use.test.js
- test/versioned/express/bare-router.test.js
- test/versioned/express/errors.test.js
- test/versioned/express/express-enrouten.test.js
- test/versioned/express/ignoring.test.js
- test/versioned/express/issue171.test.js
- test/versioned/express/render.test.js
- test/versioned/express/route-iteration.test.js
- test/versioned/express/route-param.test.js
- test/versioned/express/router-params.test.js
- test/versioned/express/transaction-naming.test.js
We had a flaky express versioned test when migrating to `tspl`. It had concurrent http requests and it was assuming the last request would end last.
This PR updates all instances of `tspl` and adds `await plan.completed` to ensure the plan has been fulfilled before ending.
> test: Updated tests that relied on `tspl` by awating the `plan.completed` instead of calling `end` to avoid flaky tests

- THIRD_PARTY_NOTICES.md
- package.json
- test/versioned/pg-esm/package.json
- third_party_manifest.json
We had some failures in CI with the IAST agent.  I noticed we have a discrepancy between the versions of `pg-native` we test in `pg` vs `pg-esm`.
> test: Updated the mininum version of pg-native in pg-esm tests to align with the pg tests

- THIRD_PARTY_NOTICES.md
- package.json
- third_party_manifest.json
Pinned iitm in #2616. A patch has since been released so removing the pinning to a good version of iitm.
> chore: Upgraded `import-in-the-middle` to work around a bug introduced in 1.11.1

- test/unit/rum.test.js
- test/unit/sampler.test.js
- test/unit/shimmer.test.js
- test/unit/stats.test.js
- test/unit/synthetics.test.js
- test/unit/system-info.test.js
Migrated penultimate grouping of unit tests to `node:test`.
Closes #2621
> test: Migrated unit tests to `node:test`

- test/lib/custom-assertions.js
> docs: Updated match custom-assertion jsdoc

- lib/transaction/tracer/index.js
- test/benchmark/shim/record.bench.js
- test/benchmark/tracer/bindFunction.bench.js
- test/benchmark/tracer/segments.bench.js
- test/benchmark/tracer/transaction.bench.js
- test/benchmark/tracer/utilities.bench.js
- test/benchmark/webframework-shim/recordMiddleware.bench.js
- test/integration/core/native-promises/native-promises.tap.js
- test/integration/core/net.tap.js
- test/integration/core/timers.tap.js
- test/integration/transaction/tracer.tap.js
- test/lib/agent_helper.js
- test/unit/api/api-start-background-transaction.test.js
- test/unit/api/api-start-web-transaction.test.js
- test/unit/instrumentation/core/promises.test.js
- test/unit/instrumentation/http/outbound-utils.js
- test/unit/instrumentation/http/outbound.test.js
- test/unit/shim/shim.test.js
- test/unit/transaction.test.js
- test/versioned/bluebird/methods.test.js
This PR updates all tests to interact with the tracer to get the segment context. This along with #2642 will centralize how we access the context and make it easier for future refactors.
> test: Updated tests that used the context manager directly and instead use the tracer to access the segment context

- .github/workflows/azure-site-extension.yml
Our GitHub workflow to publish the Azure site extension was executing before NPM made the new agent available. This change adds a test for local-vs-remote versions, and checks periodically before either resolving or exiting. 
Much of this happens in Powershell, so I've tested extensively on a fork. 
Closes #2615 
Closes NR-317297
> ci: Added delay to site extension publishing to wait for NPM

- lib/config/default.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-env.test.js
This PR contains config for IAST scan scheduling and restrictions.
You can configure your IAST to handle scan scheduling. These configurations allow you to exclude certain APIs, parameters, and vulnerability categories from IAST analysis. You can also delay IAST scans or schedule them for specific times of the day.
Example config is given below:
`security:
{
iast_test_identifier: '1008',
scan_controllers: {
iast_scan_request_rate_limit: 3600,
scan_instance_count: 1
},
scan_schedule:
{
delay: 0,
duration: 300,
schedule: '',
always_sample_traces: false
},
exclude_from_iast_scan: {
api:[]
http_request_parameters:
{
header: [],
query: [],
body: []
},
iast_detection_category: {
insecure_settings: false,
invalid_file_access: false,
sql_injection: false,
nosql_injection: false,
ldap_injection: …
> feat: IAST configurations for scan scheduling and restrictions

- lib/serverless/aws-lambda.js
- test/unit/serverless/aws-lambda.test.js
Entity linking for Lambda functions requires standardized attributes being added to transaction trace segments: `cloud.resource_id` and `cloud.provider`. This PR adds them.
@svetlanabrennan added assertions to the `aws-lambda` unit test; running serverless unit tests shows that these are present. 
Closes #2586 
Closes NR-314346
> feat: Added ARN and provider to Lambda segments

- lib/llm-events/aws-bedrock/bedrock-command.js
- test/unit/llm-events/aws-bedrock/bedrock-command.test.js
This Pr will improve the support for using the invoke model with bedrock LLM. the Invoke API expects the body to be of type `{[content: "user or assistant message"]}`.
We will now check for the type of the input if the type is a string we will return the value as is. If the param is an object we will attempt to reduce the object to just the message value.
run test suite. 
https://new-relic.atlassian.net/browse/NR-326020
> feat: Added support for Bedrock invoke model user request

- test/versioned/openai/chat-completions.test.js
- test/versioned/openai/embeddings.test.js
When #2723 was merged the build was failing for older versions of `openai`. This PR fixes those two issues.
```sh
npm run versioned:internal openai
```
> test: Fixed two assertions to work against older versions of `openai`

- lib/config/default.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-env.test.js
Updated default configs to accept `application_logging.forwarding.labels.enabled` and `application_logging.forwarding.labels.exclude` to support adding labels to log records. 
Docs website will be updated with these configs in #2716 
Added and updated unit tests
Closes #2713 
Relates to #2716
> feat: Added `labels.enabled` and `labels.exclude` to config defaults

- test/lib/fake-cert.js
This PR resolves #2709. Unit tests, on my system, run in about 1 minute and 28 seconds after this change. I also have a caching implementation, but it only shaves off another 5 seconds. I can push it up if we want those precious seconds.
> chore: Improved unit test speed

- lib/agent.js
- lib/aggregators/log-aggregator.js
- lib/instrumentation/nr-winston-transport.js
- lib/instrumentation/pino/pino.js
- test/lib/logging-helper.js
- test/unit/agent/agent.test.js
- test/unit/aggregators/log-aggregator.test.js
- test/versioned/bunyan/helpers.js
- test/versioned/pino/helpers.js
- test/versioned/pino/pino.test.js
- test/versioned/winston/helpers.js
- test/versioned/winston/winston.test.js
While helping @svetlanabrennan understand the work to add labels to logs it was discovered the spec suggests we put them in a common.attributes section of the logs array. It also suggested we add the `entity.guid`, `entity.name`, `entity.type` and `hostnmae` as these are static to a given application and reduces the redundancy in the logs payload.  This PR addresses that.
I'd still like to test this with our example applications but the code in here is closer to our specification now.
Closes #2735
> feat: Moved `entity.guid`, `entity.name`, `entity.type`, and `hostname` to `common.attributes` on logs payload instead of in every log message

- THIRD_PARTY_NOTICES.md
- lib/otel/rules.js
- lib/otel/rules.json
- lib/otel/segment-synthesis.js
- package.json
- test/unit/lib/otel/segment-synthesizer.test.js
- third_party_manifest.json
This PR adds new keys to the rules.json(for now) to identity which type of segment should be created.  I didn't enumerate all the types just yet.  The intention is this will be called on the `onEnterSpan` section of the otel tracer.  Maybe we bind the relevant timeslice metric recorder but for now that's for a different story(#2654)
Closes #2648
> feat: Added segment synthesizer and provided ability to convert http client otel spans to external http trace segments

- test/lib/test-reporter.mjs
#2700 tried to improve our test reporter by keeping track of individual subtest failures. But it was not a success. A test suite like the one below would report as passing even though it should have been reported as failing:
```js
'use strict'
const test = require('node:test')
const assert = require('node:assert')
test('passing', () => assert.ok(true))
test('failing', () => { throw Error('boom') })
test('passing2', () => assert.ok(true))
```
This refactor solves the problem (🤞).
> chore: Fixed test reporter

- lib/llm-events/aws-bedrock/bedrock-command.js
- test/unit/llm-events/aws-bedrock/bedrock-command.test.js
The shape of the users prompt message was incorrect for claude 3.5 
```
// Prepare the payload for the model.
const payload = {
anthropic_version: "bedrock-2023-05-31",
max_tokens: 1000,
messages: [
{
role: "user",
content: [{ type: "text", text: prompt }],
},
],
};
```
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_bedrock-runtime_code_examples.html#anthropic_claude
run unit test suite.
> fix: Corrected expected shape of user input in get Prompt()

- test/integration/core/fs.test.js
This PR fixes a set of flaky tests on macOS. I _think_ the problem is due to the way macOS file system does things. This [answer](https://apple.stackexchange.com/a/441772) indicates that access times are wonky on APFS to begin with. I tried several variations to try and fudge the time of file creation and then verification, but I always ended up with a failure. Sometimes it would take a couple of seconds to hit the error, other times it would take a minute or so. Regardless, it always fails on macOS when trying to test the modified access time.
I do not have a Linux or Windows system available for work to verify any of these guesses, though. So it _could_ be a flake that we are just lucky doesn't hit in CI.
For what it's worth, I verified my attempts with:
```sh
time while \
node …
```
> chore: Fixed flaky test on macOS

- test/integration/grpc/reconnect.test.js
> chore: Updated grpc integration tests to node:test

- test/integration/environment.test.js
- test/integration/flatten.test.js
- test/integration/logger.test.js
- test/integration/shimmer/reinstrument.test.js
- test/integration/uninstrumented/uninstrumented.test.js
- test/unit/util/flatten.test.js
> chore: Updated shimmer, uninstrumented, environment, flatten, and logger integration tests to node:test

- test/versioned/mysql2/package.json
A temporary patch to get our CI working while we investigate why `mysql2@3.11.5` is causing our `mysql2` promise instrumentation to fail.
> chore: Restricted mysql2 version to get CI working

- test/versioned/pino/pino.test.js
This PR removes a reference to `pino` internals in our versioned tests. Those internals rely on `tap`, which we are working to remove.
> chore: Removed reference to pino internals

- lib/serverless/api-gateway.js
- test/unit/serverless/alb-event.test.js
- test/unit/serverless/fixtures.js
- test/unit/serverless/utils.test.js
Filtering of API Gateway v1 vs v2 did not allow for Lambda functions triggered by ALB/ELB. Prior to our most recent change to that filtering, ALB events were traced without explicit filtering. This adds explicit checking for an ALB event type, and allows ALB-triggered web requests to be treated as web transactions. 
This adds a unit test at `test/unit/serverless/alb-event.test.js` checking for the expected request properties. Existing tests at `test/unit/serverless/api-gateway-v2.test.js`, `test/unit/serverless/aws-lambda.test.js`, and `test/unit/serverless/utils.test.js` also test the new comparison method.
Closes NR-341636
Closes #2779 
Closes NR-342521
Closes #2753 
Closes NR-341279
> fix: Fixed matching for ALB and API Gateway (v1 & v2) events for Lambda

- lib/instrumentation/mysql/mysql.js
- test/unit/instrumentation/mysql/index.test.js
- test/versioned/mysql/basic.js
- test/versioned/mysql/newrelic.js
- test/versioned/mysql2/newrelic.js
- test/versioned/mysql2/package.json
- test/versioned/mysql2/promises.test.js
Turns out we were relying on the fact that the `msyql2/index.js` was a circular reference for the `mysql2/promises` interface.  This was updated in https://github.com/sidorares/node-mysql2/pull/3081/files.  I also noticed that the versioned tests were configuring the sql tracing in the config file and at times wasn't sticking. So I moved those to be explicit in the tests that need that configuration.
```sh
npm run versioned:internal mysql2
npm run versioned:internal mysql
```
Closes #2810
> fix: Updated `mysql2` instrumentation to work with 3.11.5+

- README.md
- documentation/nextjs/faqs/browser-agent.md
- documentation/nextjs/faqs/error-handling.md
In #2807 it was brought to our attention that the Next.js apps linked in docs were permalinks to old versions that still referred to `@newrelic/next`. This PR updates those permalinks to point to the latest examples.
> docs: Fixed links to next.js apps

- test/versioned-external/external-repos.js
The external versioned tests were failing since merging: https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/333. I added a file that was not included in the config for the apollo server tests.
```sh
npm run versioned:external:major apollo-server
```
> test: Added `test/custom-assertions.js` to the apollo-server external versioned tests config

- lib/db/query-parsers/elasticsearch.js
- lib/db/query-parsers/mongodb.js
- lib/instrumentation/@elastic/elasticsearch.js
- lib/instrumentation/mongodb/v4-mongo.js
- lib/otel/rules.json
- lib/otel/segment-synthesis.js
- test/unit/db/query-parsers/elasticsearch.test.js
- test/unit/lib/otel/fixtures/db-sql.js
- test/unit/lib/otel/fixtures/http-client.js
- test/unit/lib/otel/fixtures/index.js
- test/unit/lib/otel/fixtures/span.js
- test/unit/lib/otel/segment-synthesizer.test.js
The transformation rules key off of client as span kind and db.system to do its matching.  However some of the required attributes for naming do not exist in Node.js opentelemetry instrumetation. Most `db.sql.table`. For traditional sql database libs we must parse the SQL to extract the operation and table. I also cross referenced our instrumentation to determine how we name segments for databases:
Segment naming for all dbs:
* mysql/mysql2 - `Datastore/statement/MySQL/<table>/<operation>`
* pg - `Datastore/statement/Postgres/<table>/<operation>`
* redis - `Datastore/operation/Redis/<operation>`
* mongodb - `Datastore/statement/MongoDB/<collection` or `Datastore/operation/MongoDB/<operation>`
* elasticsearch - `Datastore/statement/ElasticSearch/<index>/<operation>` or …
> feat: Added segment synthesis for db client otel spans to db trace

- lib/instrumentation/mysql/mysql.js
- test/versioned/mysql2/promises.test.js
Update `createPool` and `createPoolCluster` to not return a `Promise`
Updated `mysql2` promise version of `createPool` and `createPoolCluster` to not return a `Promise`, following the `mysql2` source code.
`npm run versioned:internal mysql2`
Additionally, I have patched the `newrelic` package locally to test in my project and confirmed that the changes fixed `mysql2` instrumentation.
Closes #2822.
> fix: update `mysql2` promise version instrumentation

- test/versioned/when/when.test.js
This test is failing because it was asserting i took longer than the timeout but less than the delay. I have found in CI sometimes it's taking longer than the delay however, if it'd resolve the delay the test would fail so I'm removing the assertion to assert it takes less than the delay
Closes #2826
> test: Fixed flakey `when` versioned test

- lib/serverless/api-gateway.js
- test/unit/serverless/aws-lambda.test.js
- test/unit/serverless/fixtures.js
- test/unit/serverless/utils.test.js
> fix: Fixed matching for Lambda events containing resource but which aren't API Gateway

- lib/otel/segment-synthesis.js
- lib/otel/segments/database.js
- lib/otel/segments/http-external.js
- lib/otel/segments/index.js
- lib/otel/segments/server.js
- test/unit/lib/otel/fixtures/index.js
- test/unit/lib/otel/fixtures/server.js
- test/unit/lib/otel/fixtures/span.js
- test/unit/lib/otel/segment-synthesizer.test.js
This creates both the transaction and segment when the otel span is a server match. I expect more work to be done once we wire up the context manager. We're forcing the transaction name whereas our instrumentation decorates the namestate and finalizes the same on transaction end.  I've found that most otel instrumentation sets the http.route attribute in the web frameworks which is like us and I think that's being used to finalize the http span name on the end of the request.
I also changed what the synthesizer returns. In the case of servers and will be for #2651 we need to create the transaction. So when the instrumentation for otel is wired up we'll need to bind both the transaction and segment to the context manager and not just the segment.
Closes #2649
> feat: Added segment and transaction synthesis for http server spans

- lib/otel/rules.js
- lib/otel/rules.json
- lib/otel/segment-synthesis.js
- lib/otel/segments/index.js
- lib/otel/segments/producer.js
- test/unit/lib/otel/fixtures/index.js
- test/unit/lib/otel/fixtures/producer.js
- test/unit/lib/otel/rules.test.js
- test/unit/lib/otel/segment-synthesizer.test.js
I updated the rules engine to handle producer spans separate from client spans as they are different.  Currently there's only one producer rule which is a fallback rule. I _think_ this is because the messaging spec is most complete and takes a few span attributes to build the name.
Closes #2650
> feat: Added segment synthesis for otel producer spans

- lib/otel/rules.js
- lib/otel/rules.json
- lib/otel/segment-synthesis.js
- lib/otel/segments/index.js
- lib/otel/segments/internal.js
- test/unit/lib/otel/rules.test.js
- test/unit/lib/otel/segment-synthesizer.test.js
This one is straightforward, pull the name of span to name segment but prefix with `Custom/`
Closes #2652
> feat: Added segment synthesis for internal spans

- test/lib/custom-assertions/match.js
@mrickard found that he was passing in an object that lacked the keys he was asserting. It wasn't failing, this PR fixes that.
> test: Updated `match` to fail if you pass in an object that lacks the expected keys

- lib/shim/message-shim/subscribe-consume.js
- lib/shim/shim.js
- lib/shim/transaction-shim.js
- test/unit/shim/shim.test.js
- test/unit/shim/transaction-shim.test.js
…o be backwards compatible with the changes to context manager
I did some analysis on the big changes to context manager: #2646, #2689, #2717 and found 2 places where we altered behavior to "public" methods.  I put public in quotes because aside from our api we do document and expose our shim.  These two changes were in the shim where the signatures varied and I updated the code to restore behavior:
`shim.createSegment` - before this PR required you to pass in `parent` to represent the parent segment, I updated this to pull from context manager and get the active segment like before.
`shim.handleMqTracingHeaders` - before this PR it required you to now pass in the transaction. I updated this to get the current transaction if not set and move this to the last arg to not break people's …
> fix: Updated `shim.createSegment` and `shim.handleMqTracingHeaders` to be backwards compatible with the changes to context manager

- lib/instrumentation/aws-sdk/v3/lambda.js
- lib/instrumentation/aws-sdk/v3/smithy-client.js
- lib/serverless/aws-lambda.js
- test/unit/serverless/aws-lambda.test.js
- test/versioned/aws-sdk-v3/lambda.test.js
External Lambda functions invoked by a Node application result in external segments. In order for the entity to be linked, external segments need two additional attributes: `cloud.resource_id` and `cloud.platform`. This PR adds middleware at `instrumentation/aws-sdk/v3/lambda.js` (via `instrumentation/aws-sdk/v3/smithy-client.js`) to add these attributes. This middleware adds the attributes only if the agent's config includes an AWS account ID defined as `cloud.aws.account_id`. The account ID referenced here should be the same as the AWS account ID hosting Lambda functions that will be invoked by the instrumented Node application. 
There are two new tests in `test/versioned/aws-sdk-v3/lambda.test.js`: one to test for these new attributes when `cloud.aws.account_id` is set on the agent …
> feat: Added entity linking attributes to aws-sdk v3 Lambda segments

- test/versioned/mysql2/promises.test.js
This PR fixes an issue in our tests that showed up with the release of `mysql2@3.12.0` on 2024-12-23. Basically, that version still exhibits the bug reported in https://github.com/sidorares/node-mysql2/issues/3091. So all we can really do is bump this conditional with each release of `mysql2` until that bug is resolved.
> chore: Fixed mysql2 tests for new mysql2 version

- docker-compose.yml
- lib/instrumentation/@opensearch-project/opensearch.js
- lib/instrumentations.js
- lib/shim/datastore-shim.js
- test/lib/params.js
- test/unit/instrumentation/opensearch.test.js
- test/versioned/opensearch/newrelic.js
- test/versioned/opensearch/opensearch.test.js
- test/versioned/opensearch/package.json
Adds instrumentation for `@opensearch-projects/opensearch` 2.1.0+.  It turns out at this time the interface is exactly the same as elasticsearch.  I copied the instrumentation but _could_ abstract if need be.  
```sh
npm run versioned:internal opensearch
```
Closes #2849
> feat: Added instrumentation for `@opensearch-projects/opensearch` v2.1.0+

- test/integration/distributed-tracing/trace-context-cross-agent.test.js
- test/integration/uninstrumented/package.json
- test/integration/uninstrumented/uninstrumented.test.js
- test/lib/temp-override-uncaught.js
- test/lib/temp-remove-listeners.js
- test/unit/collector/facts.test.js
`t.diagnostic` output gets added to every PR, this is unncessary noise and is not helpful to our test runs.
> test: Removed `t.diagnostic` from tests

- lib/serverless/api-gateway.js
- lib/serverless/aws-lambda.js
- test/unit/serverless/api-gateway-v2-websocket.test.js
- test/unit/serverless/fixtures.js
- test/unit/serverless/utils.test.js
Customer reported an error when triggering an instrumented Lambda function via `APIGatewayRequestAuthorizerEvent`. 
This PR makes the event matching more restrictive to avoid false positives. 
Added event fixture to `test/unit/serverless/fixtures.js` and assertions to `test/unit/serverless/utils.test.js`. Added unit test for API Gateway V2 websocket events in `test/unit/serverless/api-gateway-v2-websocket.test.js`
Closes #2857 
Closes NR-354739
> fix:  Fixed event matcher to focus on properties specific to web requests (v1/ALB and v2)

- test/versioned/Readme.md
Back in September we added support for defining a `minSupported` field on versioned test targets (https://github.com/newrelic/newrelic-node-versions/pull/35). I meant to update our local docs, but it slipped my mind until today.
> chore: Updated versioned tests docs

- test/versioned-external/external-repos.js
To get versioned tests to pass against apollo server plugin, there were changes needed like the agent from the segment/context manager refactor. This PR restores to the main branch as the work has been merged in https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/337
```sh
npm run versioned:external:major
```
> test: Restored the branch to test apollo-server-plugin to main

- test/integration/core/dns.test.js
While trying to investigate other issues this morning, our integration suite started failing. It seems that `resolve('example.com')` has started returning a set of IPs instead of a single IP as our suite expected. In my opinion, we should not be relying on external infrastructure for our test suites. So I updated these tests to resolve in our expected manners. The other solution would be to update the test to something like `assert.equal(ips.length > 0, true)`.
> chore: Fixed dns integration tests

- lib/header-attributes.js
- test/unit/header-attributes.test.js
This PR resolves #2860. If we were to insist of using a simple regular expression to match the characters we want to strip, that regular expression would _always_ include backtracking. This is because we want to replace _all_ occurrences of the offending characters. The only solution I can determine that will satisfy Sonar is to split and rejoin.
> chore: Replaced backtracking regex with new algorithm

- lib/instrumentation/aws-sdk/v3/bedrock.js
- lib/llm-events/aws-bedrock/bedrock-command.js
- lib/llm-events/aws-bedrock/bedrock-response.js
- lib/llm-events/aws-bedrock/chat-completion-message.js
- lib/llm-events/aws-bedrock/chat-completion-summary.js
- lib/llm-events/aws-bedrock/embedding.js
- lib/llm-events/aws-bedrock/utils.js
- test/lib/aws-server-stubs/ai-server/index.js
- test/lib/aws-server-stubs/ai-server/responses/claude3.js
- test/unit/llm-events/aws-bedrock/bedrock-command.test.js
- test/unit/llm-events/aws-bedrock/bedrock-response.test.js
- test/unit/llm-events/aws-bedrock/chat-completion-message.test.js
- test/unit/llm-events/aws-bedrock/chat-completion-summary.test.js
- test/unit/llm-events/aws-bedrock/embedding.test.js
- test/unit/llm-events/aws-bedrock/utils.test.js
- test/versioned/aws-sdk-v3/bedrock-chat-completions.test.js
- test/versioned/aws-sdk-v3/common.js
The current version of the Bedrock instrumentation is mostly geared toward supporting the Claude [Text Completions](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-text-completion.html) API but may not split messages as expected in multi-turn conversations with the Messages API. 
The Text Completions API supports a single prompt message but the Messages API, lets you provide multiple distinct messages (context and prompt) to the model. Currently the agent combines those separate context messages into a single prompt but it probably should follow the pattern we use in OpenAI instrumentation of splitting them into multiple `LlmChatCompletionMessage` events (still one `LlmChatCompletionSummary` per API call)
To make things more complicated, the Messages …
> feat: Added support for Claude 3+ Chat API in Bedrock

- test/unit/llm-events/aws-bedrock/bedrock-command.test.js
In #2870 there were a few missing unit tests around edge cases when calculating the prompt for claude 3 messaging api calls.  This PR adds the missing tests.
> test: Improved test coverage of normalizing claude 3 messages

- lib/shim/shim.js
- test/unit/shim/shim.test.js
This PR adds some defensive code in shim `recordWrapper`. Before the segment refactor, this check was:
```js
// See if we're in an active transaction.
let parent
if (segDesc.parent) {
// We only want to continue recording in a transaction if the
// transaction is active.
parent = segDesc.parent.transaction.isActive() ? segDesc.parent : null
} else {
parent = shim.getActiveSegment()
}
if (!parent) {
shim.logger.debug('Not recording function %s, not in a transaction.', name)
return fnApply.call(fn, this, arguments)
}
```
Afterwards, it only checked if the transaction was active, assuming there was always a segment.  
```js
// middleware recorders pass in parent segment
// we need to destructure this as it is not needed past this function
// and will overwhelm trace level loggers with …
```
> fix: Added defensive code in shim to prevent crashing when checking parent segment

- lib/db/utils.js
This PR resolves #2859.
I worked on a couple of different algorithms in an attempt to get around the rule violation, but the regular expression is our best option. The simplest algorithm I was able to devise still used regular expressions, but ended up being slower (despite being easier to follow). I have attached my benchmark below.
<details>
<summary>Benchmark</summary>
```js
'use strict'
const assert = require('node:assert')
const tests = [
['use test_db;', 'test_db'],
['USE INIT', 'INIT'],
['use test_db', 'test_db'],
['use test_db;;;;;;', 'test_db'],
['            use test_db;', 'test_db'],
['use            test_db;', 'test_db'],
['use test_db            ;', 'test_db'],
['use test_db;            ', 'test_db'],
['use `test_db`;', '`test_db`'],
['use `☃☃☃☃☃☃`;', '`☃☃☃☃☃☃`'],
['use …
```
> chore: Updated lint rule suppression comment

- .github/workflows/post-release.yml
- .github/workflows/release-lambda-init-containers.yml
We are getting rid of the internal [auto-layer-releases repo](https://source.datanerd.us/aws-lambda/auto-layer-releases/blob/master/app.py) and moving creating of the release tags into each agent's GHA deploy flow.
> ci: Move init container release from lambda to GHA

- lib/instrumentation/when/contextualizer.js
- lib/shim/promise-shim.js
- test/lib/promises/transaction-state.js
- test/unit/shim/promise-shim.test.js
A customer reported a regression(#2908) when upgrading to 12.11.0+. This surfaced when we removed the transaction from segment and there was some naive checking in both promise-shim and when instrumentation.
This PR adds some defensive code to handle when a transaction prematurely ends and instrumentation for `when` and `bluebird` attempt to check if it has to propagate the segment/transaction through the promise methods.
I also added some tests to assert that this behavior has been fixed. If you run the tests without the code, change it crashes with same reported error.
Closes #2908
> fix: Fixed issue with `bluebird` and `when` instrumentation where checking active context crashed when transaction prematurely ends

- lib/shim/transaction-shim.js
- test/unit/shim/transaction-shim.test.js
It seems like warm starts of lambdas leak async context in Node.js A regression was introduced [here](https://github.com/newrelic/node-newrelic/pull/2646/files#diff-094eb25e618908bce01ee4101c497f24988ddfc48bd7200371c2b6bc67a31b21L406). Previously before wrapping a call in a transaction it checked for an active transaction, this changed and only checked for a transaction, not that it was active. For some reason during warm invocations of lambda, the Node.js async context(which we just leverage AsyncLocalStorage) is leaking across runs.  
I added some unit tests around transaction-shim. Also we manually tested with a patched layer in lambda and there were 8 requests made and all 8 had telemetry.
Closes #2910
> fix: Fixed transaction-shim to properly create new transactions when the existing transaction is not active

- lib/util/sql/obfuscate.js
> chore: Added regex note to sql obfuscator

- .github/workflows/release-lambda-init-containers.yml
In #2848 we moved the publishing of github releases of `newrelic-lambda-layers` and `newrelic-agent-init-container` to a post release workflow, instead of a lambda cron that checked if any new releases of agent existed. I overlooked when I first reviewed that it doesn't check if Create Release was a success so I added that logic. I also removed some unnecessary jobs to setup node, install deps and configure git.  The reason is Node.js isn't being used here, we just cat the package.json to get the version and then rely on `gh` to create releases. Also since it auths to `gh` cli with a token we don't have to set up the username/email.
> ci: Optimized the lambda layers and k8s init containers post release workflow

- lib/config/index.js
- test/unit/config/config-defaults.test.js
Our current configuration doesn't allow an `undefined` value for a 3 layers deep/nested config item. This PR allows that now. 
Run unit tests
Fixes #2871
> fix: Updated default config to accept `undefined` as default value

- index.js
- lib/agent.js
- lib/collector/api.js
- lib/config/default.js
- lib/health-reporter.js
- package.json
- test/lib/custom-assertions/match.js
- test/unit/agent/agent.test.js
- test/unit/collector/api-connect.test.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-env.test.js
- test/unit/index.test.js
- test/unit/lib/health-reporter.test.js
- test/unit/mocks/agent.js
> feat: Added New Relic Control health check

- lib/otel/segments/database.js
- lib/otel/span-processor.js
- test/versioned/otel-bridge/span.test.js
The PR assigns the appropriate time slice metrics recorder depending on the otel span. It uses the database recorder when it is a query and database operation when it is redis or memcached. I also added some versioned tests to verify the timeslice metrics are occurring. Lastly, I added a method to reconcile the segment attributes when a span ends.  This basically maps the span attributes to segment attributes so when the agent re-creates spans from segments it assigns the appropriate attributes on span but retains the expected attributes on segment.  If this mapping doesn't occur the attributes are the segment would be incorrect.
Closes #2653
> feat: Added timeslice metrics recorders for synthesized db segments

- lib/config/build-instrumentation-config.js
- lib/config/default.js
- lib/core-instrumentation.js
- lib/shimmer.js
- test/unit/config/build-instrumentation-config.test.js
- test/unit/config/config-defaults.test.js
- test/unit/config/config-env.test.js
Followed the pattern I did in #2551.  I manually added `undici` and `domain` as they don't follow the same pattern as the other core instrumentation.
Closed #2926
> feat: Provided ability to disable instrumentation for core Node.js libraries

- lib/otel/constants.js
- lib/otel/segments/server.js
- lib/otel/span-processor.js
- test/versioned/otel-bridge/span.test.js
> feat: Added http timeslice metrics from otel

- api.js
- test/unit/api/api-get-trace-metadata.test.js
A regression existed from the refactor of [12.11.0](https://github.com/newrelic/node-newrelic/commit/7078554a546971d876f41da0823af3d0def33eb2#diff-1cbda34460db92d4ad755248356e01a93fa8afb3e78f3ae866547fddf34c163bR1542-R1552). A PR(#2943) was opened around a gap in test coveraege around this `getTraceMetadata` method. A customer had an active transaction but not segment.  We assumed this could never happen, however this does happen at times due to context propagation breaking.  This PR addresses this issue by handling of adding `traceId` and `spanId` separately.  The customer experiencing this will still have invalid trace metadata(lacking a spanId) but that's a different issue.
> fix: Fixed `api.getTraceMetadata` to handle when there is an active transaction but not active segment

- lib/llm-events/aws-bedrock/bedrock-command.js
- test/lib/aws-server-stubs/ai-server/index.js
- test/unit/llm-events/aws-bedrock/bedrock-command.test.js
- test/unit/llm-events/aws-bedrock/stream-handler.test.js
- test/versioned/aws-sdk-v3/bedrock-chat-completions.test.js
#2937 wasn't targetting main. This PR does that.
> feat: Added support for region-prefixed Bedrock models

- lib/metrics/recorders/message-transaction.js
- lib/otel/constants.js
- lib/otel/segments/consumer.js
- test/unit/lib/otel/consumer.test.js
- test/versioned/otel-bridge/span.test.js
> feat: Added consumer timeslice metrics from otel

- lib/util/logger.js
- test/unit/logger.test.js
It was discovered that components of the agent that rely on child loggers and adding logging from those child loggers before a root logger is configured crashes the agent.  This is because the child logger did not get assigned a log queue.  Once I assigned that, I realized it was missing the extras associated with a logger, most notably the component.  This PR fixes both of those issues and adds tests to ensure that you can queue logs from a child logger and it gets the appropriate component in a given log like when the queue is flushed and logged accordingly.
Closes #2941
> fix: Fixed queueing of logs from child loggers

- lib/context-manager/context.js
- lib/otel/fake-span.js
- lib/otel/segments/utils.js
- lib/otel/setup.js
- lib/otel/span-key-interceptor.js
- lib/otel/trace-propagator.js
- test/unit/lib/otel/fake-span.test.js
- test/unit/lib/otel/segment-utils.test.js
- test/unit/lib/otel/setup.test.js
- test/versioned/otel-bridge/span.test.js
During testing of otel example apps I was finding DT was incorrect at times.  The situation was if a transaction was started with agent and the next span was an otel span, when it retrieved the span context is thought there wasn't a parent.  That's because there wasn't a parent in otel but the agent had created a transaction with a root segment.  This PR addresses that issue by doing 2 things.  At setup of otel bridge, there's a function that is run to intercept the key that is used by otel to bind spans to the context.  Then when we bind a segment or transaction to context we also check if this span key is present and add a fake span to the otelCtx.  The span only needs a `spanContext` method which returns the appropriate spanid, traceId, and traceFlags(we hardcode to sampled).  Once I …
> feat: Updated Context class to ensure bi-directional context propagation with opentelemetry bridge

- lib/otel/attr-reconciler.js
- lib/otel/span-processor.js
> chore: Refactored otel attribute reconciling

- lib/context-manager/async-local-context-manager.js
- lib/context-manager/context.js
- lib/otel/context.js
- lib/transaction/tracer/index.js
- test/unit/context-manager/async-local-context-manager.test.js
- test/unit/lib/otel/context.test.js
I realized we conflated what's needed in our Context for agent and agent in otel bridge.  This PR splits out the otel context and adds a few missing tests around adding fake spans to the otel ctx.
> refactor: Separated context classes for agent in standard and opentelemetry bridge mode

- test/versioned/nestjs/package.json
This PR resolves #2974. Upstream packages have fixed their dependency version ranges, thus resolving this problem.
> chore: Reverted restriction in NestJS versioned tests

- test/lib/custom-assertions/assert-span-kind.js
- test/versioned/fastify/naming-common.js
When I added asserting span kind(#2976) there was some naive code for flattening the segments.  This PR fixes that and makes CI happy whilst running versioned tests with security agent.
```sh
npm run versioned:internal:major fastify
```
```sh
npm run versioned:security:major fastify 
```
> test: Fixed fastify assertions around span kind while running security agent

- lib/transaction/index.js
While researching how we might implement honoring the w3c sampling flag I noticed that the `getScrubbedUrl` method is not used anywhere. So this PR removes it.
> chore: Removed unused transaction method

- lib/agent.js
- lib/system-metrics-sampler.js
- test/unit/agent/agent.test.js
- test/unit/system-metrics-sampler.test.js
While researching what it might take to support honoring the w3c sampling flag, I discovered that we have multiple "samplers." In order to reduce confusion when working with one sampler or the other, this PR renames the system metrics sampler from just "sampler" to a very clear "systemMetricsSampler."
> chore: Clarified system metrics sampler naming

- test/integration/config/config-esm.test.js
As of [20.19.0](https://nodejs.org/en/blog/release/v20.19.0) you can require an esm module.  This test assumed you could not for versions < 22.12.0, now it works with the appropriate ranges.
> test: Fixed handling require esm for >20.19.0+

- lib/otel/segments/internal.js
- lib/otel/span-processor.js
- test/versioned/otel-bridge/span.test.js
This PR updates span processor to reconcile attributes on internal spans.  I also realized we're assigning the wrong time slice metrics recorder for internal spans. It should be the generic recorder.
Closes #2998
> feat: Assign all attributes on internal spans to segment

- test/versioned/langchain/package.json
Our langchain versioned tests started failing and I was able to track it down to the fix in [openai@4.91.0](https://github.com/openai/openai-node/pull/1312/files). The default to was `float32` but now it is `base64`. The langchain openai package does not allow us to pass in an [encoding format](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/embeddings.ts#L156), it only allows to set the model, input, and optional dimensions.  This apparently becomes a problem when loading the documents into a vectorstore, like elasticsearch.  So for now I'm pinning this version of openai to get our tests passing.
> test: pin openai to 4.90.0 to work with @langchain/openai

- lib/instrumentation/@azure/functions.js
- test/unit/instrumentation/@azure/functions.test.js
- test/versioned/azure-functions/background.test.js
- test/versioned/azure-functions/http.test.js
- test/versioned/azure-functions/package.json
This PR resolves #2997.
-----
I believe that our other instrumentations will fill in any other required attributes. For example, if the trigger is a Redis based trigger, the work in the PR should start the transaction and then the Redis instrumentation should add spans that include required datastore attributes.
I wanted to write a test that proves this. But as of right now, the only such trigger I think we could test with is Redis, and the current version of `@azure/functions` doesn't actually support it:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cache-trigger-redispubsub?tabs=isolated-process%2Cnode-v3%2Cpython-v1&pivots=programming-language-javascript
I looked at their RabbitMQ docs as well, https://learn.microsoft.com/en-us/azure/azure-functions/functio …
> feat: Support Azure functions background trigger types

- THIRD_PARTY_NOTICES.md
- lib/config/default.js
- lib/grpc/connection.js
- lib/spans/base-span-streamer.js
- lib/spans/batch-span-streamer.js
- lib/spans/create-span-event-aggregator.js
- lib/spans/span-streamer.js
- lib/spans/streaming-span-event.js
- package.json
- test/integration/infinite-tracing-connection.test.js
- test/unit/grpc/connection.test.js
- test/unit/spans/batch-span-streamer.test.js
- test/unit/spans/create-span-event-aggregator.test.js
- test/unit/spans/span-streamer.test.js
- test/unit/spans/streaming-span-event.test.js
- third_party_manifest.json
A customer reported missing spans for certain traces.  I was able to reproduce this with a [local mock server](https://github.com/newrelic/newrelic-node-examples/pull/320). There were several issues:
* the batch streamer was sending batches when the stream wasn't connected so they were floating into the ether
* the logic to flush the queue every 5 seconds was also sending batches into the ether
* lastly on failures we weren't retrying. grpc-js has built-in retries but it must be configured via a retry policy
I also tweaked the batch streamer to flush queue when timer(5 seconds elapses) or there's a batch(250). I also added some more unit tests and an integration test that asserts that retries occur after failures. Lastly our integration tests weren't asserting the seen/sent/dropped, it …
> fix: Updated span streamer to properly retry failed batches and handle flushing batch queue every 5 seconds

- docker-compose.yml
Now that ElasticSearch v9.0.0 is released, our versioned tests will test it automatically. Our test image for ElasticSearch, however, needed to be updated for compatibility with v9
> test: Updated elasticsearch image for versioned tests

- test/versioned/pg-esm/package.json
- test/versioned/pg/package.json
3.4.0 is failing versioned tests; this unblocks us until we resolve the test failures.
The actual failures will be resolved by work on #3048
> ci: Pinned pg-native to below 3.4.0

- lib/otel/trace-propagator.js
- lib/transaction/index.js
- lib/transaction/tracecontext.js
- test/unit/lib/otel/trace-propagator.test.js
- test/unit/transaction.test.js
While digging into how we could propagate gcp pub/sub `googclient_traceparent` I realized our trace propagator wasn't 100% correct.  We were injecting traceparent/tracestate by just assigning the values to the headers object.  The [propagation spec](https://opentelemetry.io/docs/specs/otel/context/api-propagators/) states you should call the `setter.set` to assign the header value.  In most cases this just does `headers[key] = value`. However, in the case of gcp pub sub, the library has its own [setter](https://github.com/googleapis/nodejs-pubsub/blob/8b514934fe55a66a27bbc00b4c76f648d6aa7c50/src/telemetry-tracing.ts#L186) that prefixes all headers with `googclient_`.  By updating our `insertDistributedTracingHeaders` to call `setter.set` this mapping logic will properly work and DT …
> refactor: Updated how otel bridge trace propagator assigns traceparent/tracestate headers

- lib/transaction/trace/exclusive-time-calculator.js
- test/unit/transaction/trace/segment.test.js
I do not know how this occurs but I suspect it's an issue around async context propagation where a segment was either not added to the transaction trace tree or it was added to the wrong transaction trace.  This PR adds some defensive code that essentially defaults the exclusive time to the segment time in these situations.  We have had [report](https://github.com/newrelic/node-newrelic/issues/2881#issuecomment-2789787287) on a similar, closed issue,  but have not provided a reproduction case.
> refactor: Added defensive code when calculating exclusive time on a segment where it cannot locate the segment in the transaction trace tree

- lib/transaction/index.js
- test/unit/instrumentation/undici.test.js
- test/unit/shim/message-shim.test.js
- test/unit/transaction.test.js
- test/versioned/grpc-esm/client-unary.test.mjs
- test/versioned/grpc/client-bidi-streaming.test.js
- test/versioned/grpc/client-server-streaming.test.js
- test/versioned/grpc/client-streaming.test.js
- test/versioned/grpc/client-unary.test.js
- test/versioned/grpc/server-unary.test.js
- test/versioned/grpc/util.cjs
- test/versioned/kafkajs/kafka.test.js
This PR updates the `insertDistributedTraceHeaders` logic to only include the `newrelic` header if it contains a value.
Closes #3047
> fix: Only add `newrelic` header to outgoing headers if has a value

- test/versioned/pg-esm/package.json
- test/versioned/pg/package.json
Updated pg-native versions in `pg` and `pg-esm` versioned tests. ESM support was introduced in 3.4.0, but not all required files were exported. `pg-native@3.4.5` corrects the export. Thanks to @brianc for fixing this!
Closes #3048 
Closes NR-406454
> test: Skipped regressions in pg-native versioned tests 

- test/versioned/aws-sdk-v3/package.json
The AWS SDK client-bedrock-runtime v3.798.0 replaces NodeHttpHandler with NodeHttp2Handler. This fails version testing, so this pins the version to a compatible range while we work on support.
> test: Pinned @aws-sdk/client-bedrock-runtime to <3.798.0

- lib/transaction/tracer/index.js
- test/unit/transaction/tracer.test.js
- test/versioned/kafkajs/kafka.test.js
- test/versioned/kafkajs/utils.js
In [12.11.0](https://github.com/newrelic/node-newrelic/releases/tag/v12.11.0) we broke out segment tree from the actual segment.  Previously, it continued adding segments as children with a `_collect` property of false.  These got filtered out when we serialized the transaction trace.  When the segment tree was added it could crash with `RangeError: Maximum call stack size exceeded` when attempting to add a segment to a deeply nested tree.  In order to prevent this unnecessarily adding segments to the transaction trace tree after the `max_trace_segments` is exceeded, I updated the logic to only add segments to transaction trace when collect it true. 
Closes #3036
> fix: Updated `createSegment` to stop adding segments to trace when `max_trace_segments` is exceeded

- test/versioned/redis/package.json
https://github.com/redis/node-redis/releases/tag/redis%405.0.0 was released yesterday and is not compatible in some way with our tests. Omitting it for now to unblock CI while we work on a proper fix.
> chore: Reduced redis range to unblock CI

- lib/context-manager/context.js
- lib/otel/context.js
- test/unit/lib/otel/context.test.js
This is defensive code to prevent obscuring errors.  We have found that if you have an uncaught exception, it tries to enter the segment with a null value.  If the otel bridge is enabled this crashes becaue of some assumptions in the context that transaction always exists when entering a segment.
> refactor: Added check to only set a FakeSpan if `transaction.agent.otelSpanKey` exists

- test/versioned/redis/package.json
Allows `redis@5` to be tested against the suites that should work until we get an answer on https://github.com/redis/node-redis/issues/2934.
> chore: Tweaked redis pin

- THIRD_PARTY_NOTICES.md
- package.json
- third_party_manifest.json
This PR pins the security agent to 2.4.0 due to a bug exposed in 2.4.1. See the discussion at https://github.com/newrelic/csec-node-agent/pull/297#issuecomment-2876351634 for details.
> chore: Pins security agent due to bug

- package.json
- third_party_manifest.json
This unpins the security agent and bumps it to the version that is not broken.
> chore: Updated security agent

- .github/workflows/ci-workflow.yml
- .github/workflows/smoke-test-workflow.yml
- .github/workflows/versioned-security-agent.yml
This PR resolves #3083 by adding configuration to our GHA workflows to force running of desired jobs by adding a label to a PR.
Supported labels are:
- `force-integration` -- runs integration tests
- `force-lint` -- runs linter
- `force-unit` -- runs unit tests
- `force-smoke` -- runs smoke test
- `force-security` -- runs security agent tests
- `force-versioned` -- runs versioned tests
> chore: Added support for running jobs on label

- .github/workflows/ci-workflow.yml
- lib/agent.js
While doing some research, I stumbled upon this block of code that is using unnecessary function invocations to get a value or default. This PR simplifies it to modern JavaScript.
> chore: Simplified linking metadata collection

- lib/config/default.js
- lib/serverless/aws-lambda.js
- test/unit/serverless/aws-lambda-stream-response.test.js
- test/unit/serverless/aws-lambda.test.js
Lambda APM Mode will support Lambda telemetry in the same UI as the one used by APM. To support this unified view, agent teams will need to inject an all-uppercase event source type in the function name segment of the transaction name. 
If `NEW_RELIC_APM_LAMBDA_MODE` is not enabled, or if there is no event source, the transaction name is unchanged. 
One test has been added to each of `aws-lambda.test.js` and `aws-lambda-stream-response.test.js`. In the latter case, the test uses a `cloudwatchScheduled` test event, as response streaming Lambda functions don't support API Gateway. Presumably any response streaming Lambda function using `NEW_RELIC_APM_LAMBDA_MODE` will be triggered by some background event, if any.
Closes #3104 
Closes NR-416510
> chore: Added event source type to  txn name for Lambda APM Mode

- lib/instrumentation/openai.js
- test/versioned/openai/package.json
This PR pins the `openai` module to the v4 range. The newly released v5 will require more work.
> chore: Pinned openai due to new major

- lib/otel/transformation-rules.json
- test/unit/lib/otel/fixtures/producer.js
- test/unit/lib/otel/rules.test.js
- test/versioned/otel-bridge/span.test.js
I tested all of our example apps. I misconfiugred the producers in the rules json.  I also had to add a specific `gcp_pubsub` producer rule for now.  Until [5.1.0](https://github.com/googleapis/nodejs-pubsub/pull/2039) is released naming will be off. Once they ship this I can remove `Producer_1_24_GCP` rule as it'll match on `Producer_1_24`.
> fix: Updated rules to work with 1.17.0 and 1.24.0 for consumer and producer span kind

- lib/collector/facts.js
- lib/config/index.js
- lib/otel/attr-reconciler.js
- lib/shim/datastore-shim.js
- test/unit/collector/facts.test.js
- test/versioned/otel-bridge/span.test.js
Addendum to #3111. The GCP cloud run hostname was not preserved across our agent because of caching which might have resulted in some UI funkiness. This fixes that.
> fix: getHostnameSafe rewrite

- test/versioned/nestjs/package.json
Apparently Nest dropped support for Node 18, last [November](https://github.com/nestjs/nest/commit/74789282d1dda112571628fe5b87c453553c940f).  It was still working for us, but we are now seeing errors like this:
```sh
error: |-
Command failed: npx nest new --package-manager npm --skip-git test-app
/home/runner/work/node-newrelic/node-newrelic/test/versioned/nestjs/node_modules/glob/node_modules/minimatch/dist/commonjs/index.js:7
const brace_expansion_1 = __importDefault(require("brace-expansion"));
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/node-newrelic/node-newrelic/test/versioned/nestjs/node_modules/glob/node_modules/brace-expansion/index.js from /home/runner/work/node-newrelic/node-newrelic/test/versioned/nestjs/node_modules/glob/node_modules/minimatch/dist/com …
```
> test: Skips running nest 11+ on node 18 due to dropping support

- lib/otel/transformation-rules.json
We had a rule that was for `gcp_pubsub` because it was not adding `message.operation` to producer spans.  This [PR](https://github.com/googleapis/nodejs-pubsub/pull/2030) fixed that and it was released as part of [5.1.0](https://github.com/googleapis/nodejs-pubsub/blob/main/CHANGELOG.md#510-2025-06-04)
> refactor: Updated transformation rules to remove the bespoke rule to appease `@google-cloud/pubsub` < 5.1.0

- .github/workflows/compatibility-report.yml
- bin/pending-prs.js
This PR improves the output of the pending prs script by formatting the links to PRs with the number and title instead of just the URL.
<details>
<summary>Before this change:</summary>
```
*node-newrelic*
There have been 17 PRs merged since `v12.21.0` on *2025-06-04T17:47:36Z*.
:waiting: *PRs not yet released*:
- https://github.com/newrelic/node-newrelic/pull/3155
- https://github.com/newrelic/node-newrelic/pull/3158
- https://github.com/newrelic/node-newrelic/pull/3148
- https://github.com/newrelic/node-newrelic/pull/3154
- https://github.com/newrelic/node-newrelic/pull/3150
- https://github.com/newrelic/node-newrelic/pull/3152
- https://github.com/newrelic/node-newrelic/pull/3151
- https://github.com/newrelic/node-newrelic/pull/3149
- https://github.com/newrelic/node-newrelic/pull/3147 …
```
> chore: Improved output of pending prs script

- test/versioned/undici/package.json
The `undici` v7 line targets Node.js >=20. We've just been lucky so far that it hasn't relied on v20 features. As of 7.11.0, that is no longer the case. https://github.com/nodejs/undici/commit/ccf385ad87c86e582c2fda69dd1eda5057d0ed5d removed a backward compatibility feature. [`toWellFormed`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toWellFormed) is only supported in >=20.
> chore: Updated undici tests to unblock CI

- lib/instrumentations.js
- lib/subscribers/db-operation.js
- lib/subscribers/db-query.js
- lib/subscribers/db.js
- lib/subscribers/elasticsearch.js
- lib/subscribers/index.js
- test/versioned/elastic/elasticsearch.test.js
This PR adds further abstractions on database subscribers.  It adds a new `db-query` subscriber but also an abstract db subscriber for handling of properties and assigning relevant db attributes to segment.  I removed the assertion for `unknown` as database_name for elasticsearch as there truly isn't a databse_name only indicies.
```sh
npm run versioned:internal elastic
```
Closes #3055
> refactor: Updated elasticsearch instrumentation to subscribe to events emitted

- lib/subscribers/elasticsearch.js
- lib/subscribers/opensearch.js
Removed `id` parameter from `opensearch` class because they are not needed in `opensearch`. And added a comment to `elasticsearch` explaining why we need `id` parameter there.
> refactor: Removed `id` parameter from `opensearch` class

- newrelic.js
Since we didn't get approval to disable timers by default in 13.0.0, I want to at least disable it in the sample configuration file.  A lot of new customers use this when they first get started, it will be good to have timers off by default for them.
> feat: Disable timers instrumentation by default in the sample configuration

- test/versioned/aws-sdk-v3/package.json
- test/versioned/google-genai/package.json
- test/versioned/mongodb-esm/package.json
- test/versioned/pg-esm/package.json
- test/versioned/pg/package.json
- test/versioned/undici/package.json
I noticed we still had some engines with `18` in them. Also I'm going to assume when we dropped 18 we had some test stanzas that were split for 18 but are no longer necessary. This PR cleans up all of those issues
> test: cleaned up engines and version ranges in versioned tests

- test/versioned/nestjs/setup.js
I noticed nestjs versioned tests started failing on an older version 10.4.9:
```sh
Error: Command failed: npx nest build
src/app.controller.ts:1:38 - error TS2307: Cannot find module '@nestjs/common' or its corresponding type declarations.
1 import { Controller, Get, Req } from '@nestjs/common';
~~~~~~~~~~~~~~~~
src/app.module.ts:1:24 - error TS2307: Cannot find module '@nestjs/common' or its corresponding type declarations.
1 import { Module } from '@nestjs/common';
~~~~~~~~~~~~~~~~
src/app.service.ts:1:28 - error TS2307: Cannot find module '@nestjs/common' or its corresponding type declarations.
1 import { Injectable } from '@nestjs/common';
~~~~~~~~~~~~~~~~
src/main.ts:1:29 - error TS2307: Cannot find module '@nestjs/core' or its corresponding type declarations.
1 import { NestFactory …
```
> test: force install of peer deps on nestjs test app

- test/integration/instrumentation/http-outbound.test.js
- test/lib/fake-cert.js
- test/versioned/prisma/setup.js
This is 3 separate issues happening on 8/3/25:
* node 24.5.0 causing integration failure in http-outbound
* node 24.5.0 requires cert to be of a certain min size now
* prisma 6.13.0 broke our existing setup of tests(turns out we weren't installed the proper CLI to build the prisma client)
> test: Fixed CI issues with latest 24

- bin/pending-prs.js
This encoding was not helping the Slack notifications. It was was just printing `&DiacriticalGrave;` in the titles being displayed in the channel.
> chore: Remove diacritical grave encoding

- bin/pending-prs.js
Reverts newrelic/node-newrelic#3287
Attempt failed due to the repos not being cloned in the script. The script is querying repos through the GitHub API only. Thus, it never needs to clone them. Unfortunately, solving the issue without cloning the repos seems impossible. The GH API doesn't provide the necessary bits to query for commits to a specific branch.
> revert: Updated PRs notice to only consider the main branch

- index.js
- test/unit/index.test.js
- test/unit/otel-bridge.test.js
This PR resolves #3278.
This implementation should allow the Lambda team to remove the Open Telemetry packages when creating a new Lambda layer. The steps to do so should be:
1. Install with nested dependencies: `npm --install-strategy=nested newrelic`
2. Remove packages: `rm -rf ./node_modules/newrelic/node_modules/@opentelemetry`
3. Proceed with building layer
-----
<details>
<summary>Example:</summary>
```
/tmp/07/foo
❯ npm i --install-strategy=nested ../newrelic-13.0.0.tgz
added 221 packages, and audited 222 packages in 7s
20 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
/tmp/07/foo took 7.2s
❯ ls node_modules
newrelic
/tmp/07/foo
❯ ls node_modules/newrelic
api.js                 index.js               load-externals.js      node_modules …
```
> chore: Add guardrail for OTEL bridge

- .github/workflows/benchmark-tests.yml
- bin/otel-metrics-sender.js
- bin/run-bench.js
Benchmark tests are failing to send metrics because `NEW_RELIC_API_KEY_PRODUCTION` is a user key not an ingest license key. `TEST_LICENSE` should be the correct GH secret we need.
> ci: Change benchmark tests to use `TEST_LICENSE`

- test/unit/spans/batch-span-streamer.test.js
We saw this batch streamer test fail at times in CI. It wasn't flushing the queue after the queueInterval was exceeded:
```sh
Error: Error [ERR_TEST_FAILURE]: SENT metric incremented to 10000
at process.emit (node:events:507:28) {
code: 'ERR_TEST_FAILURE',
failureType: 'uncaughtException',
cause: AssertionError [ERR_ASSERTION]: SENT metric incremented to 10000
at Timeout._onTimeout (/home/runner/work/node-newrelic/node-newrelic/test/unit/spans/batch-span-streamer.test.js:222:14)
at listOnTimeout (node:internal/timers:608:17)
at process.processTimers (node:internal/timers:543:7) {
generatedMessage: false,
code: 'ERR_ASSERTION',
actual: 9750,
expected: 10000,
operator: '=='
}
}
```
I cannot reproduce but my guess is that it was a timing problem. I increased the timeout for the last message …
> test: Hardened `batch-span-streamer.test.js` to avoid random failures in CI

- docker-compose.yml
This PR updates our container for redis to use the official image. I had to change it slightly to configure TLS.
```sh
docker stop nr_node_redis
npm run services
npm run versioned:internal redis
npm run versioned:internal ioredis
```
Today, bitnami is moving their image, [see](https://hub.docker.com/r/bitnami/redis)
> ci: Updated the redis container to use the official `redis` image as `bitnami/redis` is moving and no reason to use a 3rd party image

- test/versioned/langchain/runnables-streaming.test.js
We were inproperly initializing streaming chat models with langchain openai.  This PR fixes it by passing in `streaming: true`.  This started breaking in 0.6.10 of @langchain/openai because of https://github.com/langchain-ai/langchainjs/pull/8807
> test: Fixed langchain openai streaming tests by explicitly passing `streaming: true` to chat model

- lib/instrumentation/core/http-outbound.js
- test/integration/instrumentation/http-outbound.test.js
- test/unit/instrumentation/http/outbound.test.js
Regression from #2209.
Closes #3366
> fix: Added defensive code for obtaining `protocol` in outbound http calls

- lib/subscribers/openai/chat.js
- lib/subscribers/openai/config.js
- test/versioned/openai/chat-completions-res-api.test.js
- test/versioned/openai/chat-completions.test.js
The linked bug found an issue with how we're now instrumenting `openai` with the tracing channel.  I determined this is actually a bug in [Node.js](https://github.com/nodejs/node/issues/59936).  In the meantime, we can work around it by wrapping the functions we need in `traceSync` and propagating and emitting the results in the resolve/reject blocks of the promise.
**Note**: I added a test to prove this no longer crashes, but I can't seem to get it to succeed with our mock server. I want to test with a live openai instance to ensure there aren't more issues, but I don't expect there to be.
```sh
npm run versioned:internal openai
```
Fixes #3379
> fix: Updated `openai` instrumentation to properly return APIPromise to avoid crashing when using `completions.parse` or `responses.parse`

- dashboards/utils.js
- eslint.config.js
- lib/aggregators/event-aggregator.js
- lib/attributes.js
- lib/collector/serverless.js
- lib/config/formatters.js
- lib/config/index.js
- lib/instrumentation/@prisma/client.js
- lib/instrumentation/when/contextualizer.js
- lib/llm-events/aws-bedrock/chat-completion-summary.js
- lib/spans/streaming-span-event-aggregator.js
- lib/subscribers/base.js
- lib/subscribers/openai/utils.js
- lib/subscribers/pino/index.js
- lib/synthetics.js
- lib/transaction/index.js
- lib/util/cat.js
- lib/util/logger.js
- test/lib/proxy-server.js
- test/lib/test-collector.js
- test/versioned/restify/common.js
This PR relates to #2503. This changes the following eslint jsdoc rules:
- `jsdoc/require-returns-check`: warn -> error
- `jsdoc/require-property-description`: warn- > error
- `jsdoc/require-property-name`:  warn -> error
- `jsdoc/require-property-type`: warn -> error
> style: Require jsdoc `require-returns-check` and `require-property-*`

- test/lib/agent_helper.js
- test/versioned/elastic/elasticsearch.test.js
- test/versioned/google-genai/chat-completions.test.js
- test/versioned/google-genai/embeddings.test.js
- test/versioned/mcp-sdk/client-stdio.test.js
- test/versioned/mysql2/basic-pool.test.js
- test/versioned/mysql2/basic.test.js
- test/versioned/mysql2/promises.test.js
- test/versioned/openai/chat-completions-res-api.test.js
- test/versioned/openai/chat-completions.test.js
- test/versioned/openai/embeddings.test.js
- test/versioned/opensearch/opensearch.test.js
- test/versioned/pg/pg.common.js
In #3408 I updated all versioned tests to assert tracking metrics. PRs don't run a full suite and mysql2 was failing because a specific version lacked exporting package.json to require. This PR adds a helper to be used in places where package.json isn't exported and instead read and parsed accordingly. Turns out we had a few places in versioned tests that did the same few lines of code so I updated to use this helper.
> test: Added helper to get version of package when package.json not exported, and updated tests that need it

- lib/instrumentation/fastify.js
- lib/instrumentation/fastify/spec-builders.js
- lib/instrumentation/nextjs/next-server.js
- lib/metrics/recorders/middleware.js
- lib/shim/shim.js
- lib/shim/webframework-shim/middleware.js
- lib/subscriber-configs.js
- lib/subscribers/create-config.js
- lib/subscribers/fastify/add-hook.js
- lib/subscribers/fastify/common.js
- lib/subscribers/fastify/config.js
- lib/subscribers/fastify/decorate.js
- lib/subscribers/fastify/index.js
- lib/transaction/index.js
- test/unit/shim/shim.test.js
- test/unit/shim/webframework-shim.test.js
- test/unit/transaction.test.js
- test/versioned/fastify/add-hook.test.js
- test/versioned/fastify/errors.test.js
- test/versioned/fastify/express-compat-errors.test.js
- test/versioned/fastify/fastify-gte3-naming.test.js
- test/versioned/fastify/fastify-gte3.test.js
- test/versioned/fastify/naming-common.js
- test/versioned/fastify/package.json
This PR is based off of #3408.  This migrates instrumentation for fastify to use a mix of diagnostics channel and tracing channel.
Fastify added support for emitting an event for the `fastify` export but it is only post 3.21.0+. We have to keep a little old instrumentation for those older versions for the time being around registering an app level `onRoute` hook to wrap the handlers.  
This also cleaned up some weirdness around tracking route parameters.  Route parameters are stored on the trace and the web segment as `request.parameters.route.<key>`.  Unlike query parameters that are also stored on trace and web segment as `request.parameters.<key>`, these were assigned through shim because we assigned them as `parameters` on the spec.  We also had some code in shim to prefix all of …
> refactor: Update `fastify` instrumentation to subscribe to events emitted

- lib/config/build-instrumentation-config.js
- test/integration/agent/serverless-harvest.test.js
- test/integration/core/net.test.js
- test/integration/distributed-tracing/transaction-span-attributes.test.js
- test/unit/config/build-instrumentation-config.test.js
- test/unit/shimmer.test.js
- test/unit/spans/span-event.test.js
- test/unit/spans/streaming-span-event.test.js
- test/versioned-external/external-repos.js
- test/versioned/elastic/elasticsearch.test.js
- test/versioned/express/client-disconnect.test.js
- test/versioned/kafkajs/kafka.test.js
- test/versioned/koa/koa.test.js
- test/versioned/mysql/basic.js
- test/versioned/opensearch/opensearch.test.js
The Node.js agent instrumented `setTimeout` and `setInterval`. This was done many years ago to propagate async context through timers.  When we introduced an async context manager based on `AsyncLocalStorage` this instrumentation isn't necessary. On top of that, not only did we propagate context but we created segments/spans for these actions. This caused a lot of unncessary segments/spans to show that a setTimeout or setInterval was called.  This PR disables the timers instrumentation by default.  Aside from creating useless segments/spans, it typically spammed the debug+ level logger because a lot of 3rd party libraries and applications rely on `setTimeout` and `setInterval` to drive internals. You would see a lot of not recording `setTimeout` `setInterval` because it was not in an …
> refactor: Updated `config.instrumentation.timers.enabled` to false to disable `timers.setTimeout` and `timers.setInterval` by default.
